// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package main

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/umayangag/cric-info-scrapers/go-app/internal/contracts"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// PredictBatting provides a mock function for the type MockClient
func (_mock *MockClient) PredictBatting(ctx context.Context, feats []contracts.BattingFeatures) ([]contracts.BattingPrediction, error) {
	ret := _mock.Called(ctx, feats)

	if len(ret) == 0 {
		panic("no return value specified for PredictBatting")
	}

	var r0 []contracts.BattingPrediction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []contracts.BattingFeatures) ([]contracts.BattingPrediction, error)); ok {
		return returnFunc(ctx, feats)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []contracts.BattingFeatures) []contracts.BattingPrediction); ok {
		r0 = returnFunc(ctx, feats)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]contracts.BattingPrediction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []contracts.BattingFeatures) error); ok {
		r1 = returnFunc(ctx, feats)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_PredictBatting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PredictBatting'
type MockClient_PredictBatting_Call struct {
	*mock.Call
}

// PredictBatting is a helper method to define mock.On call
//   - ctx context.Context
//   - feats []contracts.BattingFeatures
func (_e *MockClient_Expecter) PredictBatting(ctx interface{}, feats interface{}) *MockClient_PredictBatting_Call {
	return &MockClient_PredictBatting_Call{Call: _e.mock.On("PredictBatting", ctx, feats)}
}

func (_c *MockClient_PredictBatting_Call) Run(run func(ctx context.Context, feats []contracts.BattingFeatures)) *MockClient_PredictBatting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []contracts.BattingFeatures
		if args[1] != nil {
			arg1 = args[1].([]contracts.BattingFeatures)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_PredictBatting_Call) Return(battingPredictions []contracts.BattingPrediction, err error) *MockClient_PredictBatting_Call {
	_c.Call.Return(battingPredictions, err)
	return _c
}

func (_c *MockClient_PredictBatting_Call) RunAndReturn(run func(ctx context.Context, feats []contracts.BattingFeatures) ([]contracts.BattingPrediction, error)) *MockClient_PredictBatting_Call {
	_c.Call.Return(run)
	return _c
}

// PredictBowling provides a mock function for the type MockClient
func (_mock *MockClient) PredictBowling(ctx context.Context, feats []contracts.BowlingFeatures) ([]contracts.BowlingPrediction, error) {
	ret := _mock.Called(ctx, feats)

	if len(ret) == 0 {
		panic("no return value specified for PredictBowling")
	}

	var r0 []contracts.BowlingPrediction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []contracts.BowlingFeatures) ([]contracts.BowlingPrediction, error)); ok {
		return returnFunc(ctx, feats)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []contracts.BowlingFeatures) []contracts.BowlingPrediction); ok {
		r0 = returnFunc(ctx, feats)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]contracts.BowlingPrediction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []contracts.BowlingFeatures) error); ok {
		r1 = returnFunc(ctx, feats)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_PredictBowling_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PredictBowling'
type MockClient_PredictBowling_Call struct {
	*mock.Call
}

// PredictBowling is a helper method to define mock.On call
//   - ctx context.Context
//   - feats []contracts.BowlingFeatures
func (_e *MockClient_Expecter) PredictBowling(ctx interface{}, feats interface{}) *MockClient_PredictBowling_Call {
	return &MockClient_PredictBowling_Call{Call: _e.mock.On("PredictBowling", ctx, feats)}
}

func (_c *MockClient_PredictBowling_Call) Run(run func(ctx context.Context, feats []contracts.BowlingFeatures)) *MockClient_PredictBowling_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []contracts.BowlingFeatures
		if args[1] != nil {
			arg1 = args[1].([]contracts.BowlingFeatures)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_PredictBowling_Call) Return(bowlingPredictions []contracts.BowlingPrediction, err error) *MockClient_PredictBowling_Call {
	_c.Call.Return(bowlingPredictions, err)
	return _c
}

func (_c *MockClient_PredictBowling_Call) RunAndReturn(run func(ctx context.Context, feats []contracts.BowlingFeatures) ([]contracts.BowlingPrediction, error)) *MockClient_PredictBowling_Call {
	_c.Call.Return(run)
	return _c
}
