// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/umayangag/cric-flow/go-app/internal/auction"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// AddPlayers provides a mock function for the type MockStore
func (_mock *MockStore) AddPlayers(ctx context.Context, auctionID string, playerIDs []int64) (*auction.Auction, error) {
	ret := _mock.Called(ctx, auctionID, playerIDs)

	if len(ret) == 0 {
		panic("no return value specified for AddPlayers")
	}

	var r0 *auction.Auction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []int64) (*auction.Auction, error)); ok {
		return returnFunc(ctx, auctionID, playerIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []int64) *auction.Auction); ok {
		r0 = returnFunc(ctx, auctionID, playerIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auction.Auction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []int64) error); ok {
		r1 = returnFunc(ctx, auctionID, playerIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_AddPlayers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPlayers'
type MockStore_AddPlayers_Call struct {
	*mock.Call
}

// AddPlayers is a helper method to define mock.On call
//   - ctx context.Context
//   - auctionID string
//   - playerIDs []int64
func (_e *MockStore_Expecter) AddPlayers(ctx interface{}, auctionID interface{}, playerIDs interface{}) *MockStore_AddPlayers_Call {
	return &MockStore_AddPlayers_Call{Call: _e.mock.On("AddPlayers", ctx, auctionID, playerIDs)}
}

func (_c *MockStore_AddPlayers_Call) Run(run func(ctx context.Context, auctionID string, playerIDs []int64)) *MockStore_AddPlayers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []int64
		if args[2] != nil {
			arg2 = args[2].([]int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_AddPlayers_Call) Return(auction1 *auction.Auction, err error) *MockStore_AddPlayers_Call {
	_c.Call.Return(auction1, err)
	return _c
}

func (_c *MockStore_AddPlayers_Call) RunAndReturn(run func(ctx context.Context, auctionID string, playerIDs []int64) (*auction.Auction, error)) *MockStore_AddPlayers_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockStore
func (_mock *MockStore) Create(ctx context.Context, auction1 auction.Auction) (*auction.Auction, error) {
	ret := _mock.Called(ctx, auction1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *auction.Auction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auction.Auction) (*auction.Auction, error)); ok {
		return returnFunc(ctx, auction1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, auction.Auction) *auction.Auction); ok {
		r0 = returnFunc(ctx, auction1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auction.Auction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, auction.Auction) error); ok {
		r1 = returnFunc(ctx, auction1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - auction1 auction.Auction
func (_e *MockStore_Expecter) Create(ctx interface{}, auction1 interface{}) *MockStore_Create_Call {
	return &MockStore_Create_Call{Call: _e.mock.On("Create", ctx, auction1)}
}

func (_c *MockStore_Create_Call) Run(run func(ctx context.Context, auction1 auction.Auction)) *MockStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auction.Auction
		if args[1] != nil {
			arg1 = args[1].(auction.Auction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_Create_Call) Return(auction11 *auction.Auction, err error) *MockStore_Create_Call {
	_c.Call.Return(auction11, err)
	return _c
}

func (_c *MockStore_Create_Call) RunAndReturn(run func(ctx context.Context, auction1 auction.Auction) (*auction.Auction, error)) *MockStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockStore
func (_mock *MockStore) Get(ctx context.Context, auctionID string) (*auction.Auction, error) {
	ret := _mock.Called(ctx, auctionID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *auction.Auction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*auction.Auction, error)); ok {
		return returnFunc(ctx, auctionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *auction.Auction); ok {
		r0 = returnFunc(ctx, auctionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auction.Auction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, auctionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - auctionID string
func (_e *MockStore_Expecter) Get(ctx interface{}, auctionID interface{}) *MockStore_Get_Call {
	return &MockStore_Get_Call{Call: _e.mock.On("Get", ctx, auctionID)}
}

func (_c *MockStore_Get_Call) Run(run func(ctx context.Context, auctionID string)) *MockStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_Get_Call) Return(auction1 *auction.Auction, err error) *MockStore_Get_Call {
	_c.Call.Return(auction1, err)
	return _c
}

func (_c *MockStore_Get_Call) RunAndReturn(run func(ctx context.Context, auctionID string) (*auction.Auction, error)) *MockStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockStore
func (_mock *MockStore) List(ctx context.Context) ([]auction.Auction, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []auction.Auction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]auction.Auction, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []auction.Auction); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]auction.Auction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) List(ctx interface{}) *MockStore_List_Call {
	return &MockStore_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockStore_List_Call) Run(run func(ctx context.Context)) *MockStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_List_Call) Return(auctions []auction.Auction, err error) *MockStore_List_Call {
	_c.Call.Return(auctions, err)
	return _c
}

func (_c *MockStore_List_Call) RunAndReturn(run func(ctx context.Context) ([]auction.Auction, error)) *MockStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// RecordOutcome provides a mock function for the type MockStore
func (_mock *MockStore) RecordOutcome(ctx context.Context, auctionID string, outcome auction.Outcome) (*auction.Auction, error) {
	ret := _mock.Called(ctx, auctionID, outcome)

	if len(ret) == 0 {
		panic("no return value specified for RecordOutcome")
	}

	var r0 *auction.Auction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, auction.Outcome) (*auction.Auction, error)); ok {
		return returnFunc(ctx, auctionID, outcome)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, auction.Outcome) *auction.Auction); ok {
		r0 = returnFunc(ctx, auctionID, outcome)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auction.Auction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, auction.Outcome) error); ok {
		r1 = returnFunc(ctx, auctionID, outcome)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_RecordOutcome_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordOutcome'
type MockStore_RecordOutcome_Call struct {
	*mock.Call
}

// RecordOutcome is a helper method to define mock.On call
//   - ctx context.Context
//   - auctionID string
//   - outcome auction.Outcome
func (_e *MockStore_Expecter) RecordOutcome(ctx interface{}, auctionID interface{}, outcome interface{}) *MockStore_RecordOutcome_Call {
	return &MockStore_RecordOutcome_Call{Call: _e.mock.On("RecordOutcome", ctx, auctionID, outcome)}
}

func (_c *MockStore_RecordOutcome_Call) Run(run func(ctx context.Context, auctionID string, outcome auction.Outcome)) *MockStore_RecordOutcome_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 auction.Outcome
		if args[2] != nil {
			arg2 = args[2].(auction.Outcome)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_RecordOutcome_Call) Return(auction1 *auction.Auction, err error) *MockStore_RecordOutcome_Call {
	_c.Call.Return(auction1, err)
	return _c
}

func (_c *MockStore_RecordOutcome_Call) RunAndReturn(run func(ctx context.Context, auctionID string, outcome auction.Outcome) (*auction.Auction, error)) *MockStore_RecordOutcome_Call {
	_c.Call.Return(run)
	return _c
}
