run:
  timeout: 3m
  tests: true
  allow-parallel-runners: true

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - errcheck
    - revive
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

version: "2"