run:
  timeout: 3m
  tests: true
  allow-parallel-runners: true

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - errcheck
    - revive
    - deadcode
    - unused

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number