version: "2"
run:
  tests: true
  allow-parallel-runners: true
linters:
  settings:
    gosec:
      excludes:
        - G703
        - G704
        - G705
        - G706
  enable:
    - revive
    # disable testpackage: noisy; we prefer internal tests to access internals
    # - testpackage
    - errcheck
    - staticcheck
    - ineffassign
    - unparam
    - unused
    - gosec
    - gocritic
    - prealloc
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
