// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/umayangag/cric-flow/go-app/internal/availability"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// DeleteFlag provides a mock function for the type MockStore
func (_mock *MockStore) DeleteFlag(ctx context.Context, actor string, playerID int64) (availability.Flag, bool, error) {
	ret := _mock.Called(ctx, actor, playerID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFlag")
	}

	var r0 availability.Flag
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) (availability.Flag, bool, error)); ok {
		return returnFunc(ctx, actor, playerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) availability.Flag); ok {
		r0 = returnFunc(ctx, actor, playerID)
	} else {
		r0 = ret.Get(0).(availability.Flag)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64) bool); ok {
		r1 = returnFunc(ctx, actor, playerID)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, int64) error); ok {
		r2 = returnFunc(ctx, actor, playerID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockStore_DeleteFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFlag'
type MockStore_DeleteFlag_Call struct {
	*mock.Call
}

// DeleteFlag is a helper method to define mock.On call
//   - ctx context.Context
//   - actor string
//   - playerID int64
func (_e *MockStore_Expecter) DeleteFlag(ctx interface{}, actor interface{}, playerID interface{}) *MockStore_DeleteFlag_Call {
	return &MockStore_DeleteFlag_Call{Call: _e.mock.On("DeleteFlag", ctx, actor, playerID)}
}

func (_c *MockStore_DeleteFlag_Call) Run(run func(ctx context.Context, actor string, playerID int64)) *MockStore_DeleteFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_DeleteFlag_Call) Return(flag availability.Flag, b bool, err error) *MockStore_DeleteFlag_Call {
	_c.Call.Return(flag, b, err)
	return _c
}

func (_c *MockStore_DeleteFlag_Call) RunAndReturn(run func(ctx context.Context, actor string, playerID int64) (availability.Flag, bool, error)) *MockStore_DeleteFlag_Call {
	_c.Call.Return(run)
	return _c
}

// ListFlags provides a mock function for the type MockStore
func (_mock *MockStore) ListFlags(ctx context.Context, actor string) (map[int64]availability.Flag, error) {
	ret := _mock.Called(ctx, actor)

	if len(ret) == 0 {
		panic("no return value specified for ListFlags")
	}

	var r0 map[int64]availability.Flag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[int64]availability.Flag, error)); ok {
		return returnFunc(ctx, actor)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[int64]availability.Flag); ok {
		r0 = returnFunc(ctx, actor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int64]availability.Flag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, actor)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListFlags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFlags'
type MockStore_ListFlags_Call struct {
	*mock.Call
}

// ListFlags is a helper method to define mock.On call
//   - ctx context.Context
//   - actor string
func (_e *MockStore_Expecter) ListFlags(ctx interface{}, actor interface{}) *MockStore_ListFlags_Call {
	return &MockStore_ListFlags_Call{Call: _e.mock.On("ListFlags", ctx, actor)}
}

func (_c *MockStore_ListFlags_Call) Run(run func(ctx context.Context, actor string)) *MockStore_ListFlags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_ListFlags_Call) Return(int64ToFlag map[int64]availability.Flag, err error) *MockStore_ListFlags_Call {
	_c.Call.Return(int64ToFlag, err)
	return _c
}

func (_c *MockStore_ListFlags_Call) RunAndReturn(run func(ctx context.Context, actor string) (map[int64]availability.Flag, error)) *MockStore_ListFlags_Call {
	_c.Call.Return(run)
	return _c
}

// RetirementEvidence provides a mock function for the type MockStore
func (_mock *MockStore) RetirementEvidence(ctx context.Context, playerID int64) (availability.Evidence, error) {
	ret := _mock.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for RetirementEvidence")
	}

	var r0 availability.Evidence
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (availability.Evidence, error)); ok {
		return returnFunc(ctx, playerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) availability.Evidence); ok {
		r0 = returnFunc(ctx, playerID)
	} else {
		r0 = ret.Get(0).(availability.Evidence)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_RetirementEvidence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetirementEvidence'
type MockStore_RetirementEvidence_Call struct {
	*mock.Call
}

// RetirementEvidence is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID int64
func (_e *MockStore_Expecter) RetirementEvidence(ctx interface{}, playerID interface{}) *MockStore_RetirementEvidence_Call {
	return &MockStore_RetirementEvidence_Call{Call: _e.mock.On("RetirementEvidence", ctx, playerID)}
}

func (_c *MockStore_RetirementEvidence_Call) Run(run func(ctx context.Context, playerID int64)) *MockStore_RetirementEvidence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_RetirementEvidence_Call) Return(evidence availability.Evidence, err error) *MockStore_RetirementEvidence_Call {
	_c.Call.Return(evidence, err)
	return _c
}

func (_c *MockStore_RetirementEvidence_Call) RunAndReturn(run func(ctx context.Context, playerID int64) (availability.Evidence, error)) *MockStore_RetirementEvidence_Call {
	_c.Call.Return(run)
	return _c
}

// SaveFlag provides a mock function for the type MockStore
func (_mock *MockStore) SaveFlag(ctx context.Context, flag availability.Flag) error {
	ret := _mock.Called(ctx, flag)

	if len(ret) == 0 {
		panic("no return value specified for SaveFlag")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, availability.Flag) error); ok {
		r0 = returnFunc(ctx, flag)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_SaveFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveFlag'
type MockStore_SaveFlag_Call struct {
	*mock.Call
}

// SaveFlag is a helper method to define mock.On call
//   - ctx context.Context
//   - flag availability.Flag
func (_e *MockStore_Expecter) SaveFlag(ctx interface{}, flag interface{}) *MockStore_SaveFlag_Call {
	return &MockStore_SaveFlag_Call{Call: _e.mock.On("SaveFlag", ctx, flag)}
}

func (_c *MockStore_SaveFlag_Call) Run(run func(ctx context.Context, flag availability.Flag)) *MockStore_SaveFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 availability.Flag
		if args[1] != nil {
			arg1 = args[1].(availability.Flag)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_SaveFlag_Call) Return(err error) *MockStore_SaveFlag_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_SaveFlag_Call) RunAndReturn(run func(ctx context.Context, flag availability.Flag) error) *MockStore_SaveFlag_Call {
	_c.Call.Return(run)
	return _c
}
