// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/umayangag/cric-info-scrapers/go-app/internal/models"
)

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function for the type MockProvider
func (_mock *MockProvider) Fetch(ctx context.Context, matchID int64) ([]models.WeatherData, error) {
	ret := _mock.Called(ctx, matchID)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []models.WeatherData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]models.WeatherData, error)); ok {
		return returnFunc(ctx, matchID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []models.WeatherData); ok {
		r0 = returnFunc(ctx, matchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.WeatherData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, matchID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockProvider_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - matchID int64
func (_e *MockProvider_Expecter) Fetch(ctx interface{}, matchID interface{}) *MockProvider_Fetch_Call {
	return &MockProvider_Fetch_Call{Call: _e.mock.On("Fetch", ctx, matchID)}
}

func (_c *MockProvider_Fetch_Call) Run(run func(ctx context.Context, matchID int64)) *MockProvider_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProvider_Fetch_Call) Return(weatherDatas []models.WeatherData, err error) *MockProvider_Fetch_Call {
	_c.Call.Return(weatherDatas, err)
	return _c
}

func (_c *MockProvider_Fetch_Call) RunAndReturn(run func(ctx context.Context, matchID int64) ([]models.WeatherData, error)) *MockProvider_Fetch_Call {
	_c.Call.Return(run)
	return _c
}
