all: false
inpackage: false
filename: "{{.InterfaceName}}.go"
formatter: goimports
packages:
  github.com/umayangag/cric-flow/go-app/internal/db:
    config:
      dir: internal/db/mocks
      pkgname: mocks
    interfaces:
      DB: {}
      Row: {}
      Rows: {}
  github.com/umayangag/cric-flow/go-app/internal/cricsheet:
    config:
      dir: internal/cricsheet/mocks
      pkgname: mocks
    interfaces:
      CricsheetDB: {}
