all: false
inpackage: false
filename: "{{.InterfaceName}}.go"
formatter: goimports
packages:
  github.com/umayangag/cric-info-scrapers/go-app/internal/predictor:
    config:
      dir: internal/predictor/internal/mocks
      pkgname: mocks
    interfaces:
      Predictor: { }
