all: false
inpackage: false
filename: "{{.InterfaceName}}.go"
formatter: goimports
packages:
  github.com/umayangag/cric-flow/go-app/internal/db:
    config:
      dir: internal/db/mocks
      pkgname: mocks
    interfaces:
      DB: {}
      Row: {}
      Rows: {}
      Tx: {}
  github.com/umayangag/cric-flow/go-app/internal/availability:
    config:
      dir: internal/availability/mocks
      pkgname: mocks
    interfaces:
      Store: {}
  github.com/umayangag/cric-flow/go-app/internal/auction:
    config:
      dir: internal/auction/mocks
      pkgname: mocks
    interfaces:
      Store: {}
  github.com/umayangag/cric-flow/go-app/internal/predictions:
    config:
      dir: internal/predictions/mocks
      pkgname: mocks
    interfaces:
      Recorder: {}
      Reader: {}
  github.com/umayangag/cric-flow/go-app/internal/cricsheet:
    config:
      dir: internal/cricsheet/mocks
      pkgname: mocks
    interfaces:
      CricsheetDB: {}
