# syntax=docker/dockerfile:1
FROM golang:1.24-alpine AS build
WORKDIR /app
COPY go.mod .
RUN --mount=type=cache,target=/go/pkg/mod go mod download
COPY . .
RUN --mount=type=cache,target=/go/pkg/mod CGO_ENABLED=0 go build -o /out/api ./cmd/api

FROM gcr.io/distroless/base-debian12
WORKDIR /
COPY --from=build /out/api /api
# include SQL migrations in the image
COPY --from=build /app/migrations /migrations
EXPOSE 8080
USER 65532:65532
ENTRYPOINT ["/api"]
