# syntax=docker/dockerfile:1
FROM golang:1.22-alpine AS build
WORKDIR /app
COPY go.mod .
RUN --mount=type=cache,target=/go/pkg/mod go mod download
COPY . .
RUN --mount=type=cache,target=/go/pkg/mod CGO_ENABLED=0 go build -o /out/scraper ./cmd/scraper

FROM gcr.io/distroless/base-debian12
WORKDIR /
COPY --from=build /out/scraper /scraper
ENTRYPOINT ["/scraper"]
