// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io/fs"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFS creates a new instance of MockFS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFS(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFS {
	mock := &MockFS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFS is an autogenerated mock type for the FS type
type MockFS struct {
	mock.Mock
}

type MockFS_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFS) EXPECT() *MockFS_Expecter {
	return &MockFS_Expecter{mock: &_m.Mock}
}

// Glob provides a mock function for the type MockFS
func (_mock *MockFS) Glob(pattern string) ([]string, error) {
	ret := _mock.Called(pattern)

	if len(ret) == 0 {
		panic("no return value specified for Glob")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return returnFunc(pattern)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(pattern)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(pattern)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFS_Glob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Glob'
type MockFS_Glob_Call struct {
	*mock.Call
}

// Glob is a helper method to define mock.On call
//   - pattern string
func (_e *MockFS_Expecter) Glob(pattern interface{}) *MockFS_Glob_Call {
	return &MockFS_Glob_Call{Call: _e.mock.On("Glob", pattern)}
}

func (_c *MockFS_Glob_Call) Run(run func(pattern string)) *MockFS_Glob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFS_Glob_Call) Return(strings []string, err error) *MockFS_Glob_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockFS_Glob_Call) RunAndReturn(run func(pattern string) ([]string, error)) *MockFS_Glob_Call {
	_c.Call.Return(run)
	return _c
}

// MkdirAll provides a mock function for the type MockFS
func (_mock *MockFS) MkdirAll(path string, perm fs.FileMode) error {
	ret := _mock.Called(path, perm)

	if len(ret) == 0 {
		panic("no return value specified for MkdirAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, fs.FileMode) error); ok {
		r0 = returnFunc(path, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFS_MkdirAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MkdirAll'
type MockFS_MkdirAll_Call struct {
	*mock.Call
}

// MkdirAll is a helper method to define mock.On call
//   - path string
//   - perm fs.FileMode
func (_e *MockFS_Expecter) MkdirAll(path interface{}, perm interface{}) *MockFS_MkdirAll_Call {
	return &MockFS_MkdirAll_Call{Call: _e.mock.On("MkdirAll", path, perm)}
}

func (_c *MockFS_MkdirAll_Call) Run(run func(path string, perm fs.FileMode)) *MockFS_MkdirAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 fs.FileMode
		if args[1] != nil {
			arg1 = args[1].(fs.FileMode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFS_MkdirAll_Call) Return(err error) *MockFS_MkdirAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFS_MkdirAll_Call) RunAndReturn(run func(path string, perm fs.FileMode) error) *MockFS_MkdirAll_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function for the type MockFS
func (_mock *MockFS) ReadFile(ctx context.Context, path string) ([]byte, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFS_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type MockFS_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockFS_Expecter) ReadFile(ctx interface{}, path interface{}) *MockFS_ReadFile_Call {
	return &MockFS_ReadFile_Call{Call: _e.mock.On("ReadFile", ctx, path)}
}

func (_c *MockFS_ReadFile_Call) Run(run func(ctx context.Context, path string)) *MockFS_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFS_ReadFile_Call) Return(bytes []byte, err error) *MockFS_ReadFile_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockFS_ReadFile_Call) RunAndReturn(run func(ctx context.Context, path string) ([]byte, error)) *MockFS_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFile provides a mock function for the type MockFS
func (_mock *MockFS) WriteFile(ctx context.Context, path string, data []byte, perm fs.FileMode) error {
	ret := _mock.Called(ctx, path, data, perm)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, fs.FileMode) error); ok {
		r0 = returnFunc(ctx, path, data, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFS_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type MockFS_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - data []byte
//   - perm fs.FileMode
func (_e *MockFS_Expecter) WriteFile(ctx interface{}, path interface{}, data interface{}, perm interface{}) *MockFS_WriteFile_Call {
	return &MockFS_WriteFile_Call{Call: _e.mock.On("WriteFile", ctx, path, data, perm)}
}

func (_c *MockFS_WriteFile_Call) Run(run func(ctx context.Context, path string, data []byte, perm fs.FileMode)) *MockFS_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 fs.FileMode
		if args[3] != nil {
			arg3 = args[3].(fs.FileMode)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFS_WriteFile_Call) Return(err error) *MockFS_WriteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFS_WriteFile_Call) RunAndReturn(run func(ctx context.Context, path string, data []byte, perm fs.FileMode) error) *MockFS_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}
