package db

import (
	"context"
	"errors"
)

// PlayerWindowRow represents one upsert row for player_window_features.
// Scope may be one of: overall, opposition, venue, season. For overall use nil ScopeID.
// Role is 'bat' or 'bowl'.
// Rates should be precomputed by caller; server trusts provided values.
// Zero values for non-applicable fields are acceptable.
// AsOfDate uses YYYY-MM-DD string format.
// Note: scope_id0 is generated by the table.
type PlayerWindowRow struct {
	AsOfDate           string // YYYY-MM-DD
	FormatID           int
	Scope              string
	ScopeID            *int64 // nil for overall
	PlayerID           int64
	Role               string // 'bat' | 'bowl'
	Phase              string // powerplay|middle|death|all
	Horizon            int
	Balls              int
	Runs               int
	Dots               int
	Fours              int
	Sixes              int
	Dismissals         int
	SR                 *float64
	BoundaryRate       *float64
	DotRate            *float64
	DismissalHaz       *float64
	Wickets            int
	DotBalls           int
	BoundariesConceded int
	WideNoBall         int
	Econ               *float64
	WicketRate         *float64
}

// UpsertPlayerWindows performs idempotent upserts for player_window_features rows.
func UpsertPlayerWindows(ctx context.Context, rows []PlayerWindowRow) error {
	if Pool == nil {
		return errors.New("db pool not initialized")
	}
	for i := range rows {
		r := rows[i]
		_, err := Pool.Exec(ctx, `
			INSERT INTO player_window_features(
				as_of_date, format_id, scope, scope_id, player_id, role, phase, horizon,
				balls, runs, dots,
				fours, sixes, dismissals, sr, boundary_rate, dot_rate, dismissal_hazard,
				wickets, dot_balls, boundaries_conceded, wide_nb, econ, wicket_rate
			) VALUES (
				$1,$2,$3,$4,$5,$6,$7,$8,
				$9,$10,$11,
				$12,$13,$14,$15,$16,$17,$18,
				$19,$20,$21,$22,$23,$24
			)
			ON CONFLICT (as_of_date, format_id, scope, scope_id0, player_id, role, phase, horizon)
			DO UPDATE SET
				balls = EXCLUDED.balls,
				runs = EXCLUDED.runs,
				dots = EXCLUDED.dots,
				fours = EXCLUDED.fours,
				sixes = EXCLUDED.sixes,
				dismissals = EXCLUDED.dismissals,
				sr = EXCLUDED.sr,
				boundary_rate = EXCLUDED.boundary_rate,
				dot_rate = EXCLUDED.dot_rate,
				dismissal_hazard = EXCLUDED.dismissal_hazard,
				wickets = EXCLUDED.wickets,
				dot_balls = EXCLUDED.dot_balls,
				boundaries_conceded = EXCLUDED.boundaries_conceded,
				wide_nb = EXCLUDED.wide_nb,
				econ = EXCLUDED.econ,
				wicket_rate = EXCLUDED.wicket_rate
		`,
			r.AsOfDate, r.FormatID, r.Scope, r.ScopeID, r.PlayerID, r.Role, r.Phase, r.Horizon,
			r.Balls, r.Runs, r.Dots,
			r.Fours, r.Sixes, r.Dismissals, r.SR, r.BoundaryRate, r.DotRate, r.DismissalHaz,
			r.Wickets, r.DotBalls, r.BoundariesConceded, r.WideNoBall, r.Econ, r.WicketRate,
		)
		if err != nil {
			return err
		}
	}
	return nil
}
