package db

import (
	"context"
	"errors"
)

// ExtrasDisciplineRow mirrors columns for insertion/upsert into extras_discipline_features.
// Scope is currently 'overall' with NULL scope_id as per plan; scope_id0 is generated by the table.
type ExtrasDisciplineRow struct {
	AsOfDate       string // YYYY-MM-DD
	FormatID       int
	Scope          string // 'overall'
	ScopeID        *int64 // nil for overall
	PlayerID       int64  // bowler id
	Phase          string // powerplay|middle|death|all
	Overs          int
	BallsBowled    int
	RunsConceded   int
	Wickets        int
	Wides          int
	NoBalls        int
	Byes           int
	LegByes        int
	PenaltyRuns    int
	ExtrasTotal    int
	WidesPerOver   float64 // precomputed; server trusts inputs
	NoBallsPerOver float64
	ExtrasPerOver  float64
}

// UpsertExtrasDiscipline performs idempotent upserts for extras_discipline_features rows.
func UpsertExtrasDiscipline(ctx context.Context, rows []ExtrasDisciplineRow) error {
	if Pool == nil {
		return errors.New("db pool not initialized")
	}
	for i := range rows {
		r := rows[i]
		if r.Scope == "" {
			r.Scope = "overall"
		}
		_, err := Pool.Exec(ctx, `
			INSERT INTO extras_discipline_features(
				as_of_date, format_id, scope, scope_id, player_id, phase,
				overs, balls_bowled, runs_conceded, wickets,
				wides, no_balls, byes, leg_byes, penalty_runs,
				extras_total, wides_per_over, no_balls_per_over, extras_per_over
			) VALUES (
				$1,$2,$3,$4,$5,$6,
				$7,$8,$9,$10,
				$11,$12,$13,$14,$15,
				$16,$17,$18,$19
			)
			ON CONFLICT (as_of_date, format_id, scope, scope_id0, player_id, phase)
			DO UPDATE SET
				overs = EXCLUDED.overs,
				balls_bowled = EXCLUDED.balls_bowled,
				runs_conceded = EXCLUDED.runs_conceded,
				wickets = EXCLUDED.wickets,
				wides = EXCLUDED.wides,
				no_balls = EXCLUDED.no_balls,
				byes = EXCLUDED.byes,
				leg_byes = EXCLUDED.leg_byes,
				penalty_runs = EXCLUDED.penalty_runs,
				extras_total = EXCLUDED.extras_total,
				wides_per_over = EXCLUDED.wides_per_over,
				no_balls_per_over = EXCLUDED.no_balls_per_over,
				extras_per_over = EXCLUDED.extras_per_over
		`,
			r.AsOfDate, r.FormatID, r.Scope, r.ScopeID, r.PlayerID, r.Phase,
			r.Overs, r.BallsBowled, r.RunsConceded, r.Wickets,
			r.Wides, r.NoBalls, r.Byes, r.LegByes, r.PenaltyRuns,
			r.ExtrasTotal, r.WidesPerOver, r.NoBallsPerOver, r.ExtrasPerOver,
		)
		if err != nil {
			return err
		}
	}
	return nil
}
