// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/umayangag/cric-flow/go-app/internal/mlclient"
)

// NewMockMLClient creates a new instance of MockMLClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMLClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMLClient {
	mock := &MockMLClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMLClient is an autogenerated mock type for the MLClient type
type MockMLClient struct {
	mock.Mock
}

type MockMLClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMLClient) EXPECT() *MockMLClient_Expecter {
	return &MockMLClient_Expecter{mock: &_m.Mock}
}

// PredictTeam provides a mock function for the type MockMLClient
func (_mock *MockMLClient) PredictTeam(ctx context.Context, in mlclient.PredictRequest) (mlclient.PredictResponse, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PredictTeam")
	}

	var r0 mlclient.PredictResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mlclient.PredictRequest) (mlclient.PredictResponse, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, mlclient.PredictRequest) mlclient.PredictResponse); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(mlclient.PredictResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, mlclient.PredictRequest) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMLClient_PredictTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PredictTeam'
type MockMLClient_PredictTeam_Call struct {
	*mock.Call
}

// PredictTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - in mlclient.PredictRequest
func (_e *MockMLClient_Expecter) PredictTeam(ctx interface{}, in interface{}) *MockMLClient_PredictTeam_Call {
	return &MockMLClient_PredictTeam_Call{Call: _e.mock.On("PredictTeam", ctx, in)}
}

func (_c *MockMLClient_PredictTeam_Call) Run(run func(ctx context.Context, in mlclient.PredictRequest)) *MockMLClient_PredictTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mlclient.PredictRequest
		if args[1] != nil {
			arg1 = args[1].(mlclient.PredictRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMLClient_PredictTeam_Call) Return(predictResponse mlclient.PredictResponse, err error) *MockMLClient_PredictTeam_Call {
	_c.Call.Return(predictResponse, err)
	return _c
}

func (_c *MockMLClient_PredictTeam_Call) RunAndReturn(run func(ctx context.Context, in mlclient.PredictRequest) (mlclient.PredictResponse, error)) *MockMLClient_PredictTeam_Call {
	_c.Call.Return(run)
	return _c
}

// Reload provides a mock function for the type MockMLClient
func (_mock *MockMLClient) Reload(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Reload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMLClient_Reload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reload'
type MockMLClient_Reload_Call struct {
	*mock.Call
}

// Reload is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMLClient_Expecter) Reload(ctx interface{}) *MockMLClient_Reload_Call {
	return &MockMLClient_Reload_Call{Call: _e.mock.On("Reload", ctx)}
}

func (_c *MockMLClient_Reload_Call) Run(run func(ctx context.Context)) *MockMLClient_Reload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMLClient_Reload_Call) Return(err error) *MockMLClient_Reload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMLClient_Reload_Call) RunAndReturn(run func(ctx context.Context) error) *MockMLClient_Reload_Call {
	_c.Call.Return(run)
	return _c
}
