// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/umayangag/cric-info-scrapers/go-app/internal/cli/teampredictor"
	"github.com/umayangag/cric-info-scrapers/go-app/internal/mlclient"
)

// NewMockPredictor creates a new instance of MockPredictor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPredictor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPredictor {
	mock := &MockPredictor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPredictor is an autogenerated mock type for the Predictor type
type MockPredictor struct {
	mock.Mock
}

type MockPredictor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPredictor) EXPECT() *MockPredictor_Expecter {
	return &MockPredictor_Expecter{mock: &_m.Mock}
}

// Predict provides a mock function for the type MockPredictor
func (_mock *MockPredictor) Predict(ctx context.Context, opts teampredictor.Options) (mlclient.PredictResponse, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Predict")
	}

	var r0 mlclient.PredictResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, teampredictor.Options) (mlclient.PredictResponse, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, teampredictor.Options) mlclient.PredictResponse); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		r0 = ret.Get(0).(mlclient.PredictResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, teampredictor.Options) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPredictor_Predict_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Predict'
type MockPredictor_Predict_Call struct {
	*mock.Call
}

// Predict is a helper method to define mock.On call
//   - ctx context.Context
//   - opts teampredictor.Options
func (_e *MockPredictor_Expecter) Predict(ctx interface{}, opts interface{}) *MockPredictor_Predict_Call {
	return &MockPredictor_Predict_Call{Call: _e.mock.On("Predict", ctx, opts)}
}

func (_c *MockPredictor_Predict_Call) Run(run func(ctx context.Context, opts teampredictor.Options)) *MockPredictor_Predict_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 teampredictor.Options
		if args[1] != nil {
			arg1 = args[1].(teampredictor.Options)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPredictor_Predict_Call) Return(predictResponse mlclient.PredictResponse, err error) *MockPredictor_Predict_Call {
	_c.Call.Return(predictResponse, err)
	return _c
}

func (_c *MockPredictor_Predict_Call) RunAndReturn(run func(ctx context.Context, opts teampredictor.Options) (mlclient.PredictResponse, error)) *MockPredictor_Predict_Call {
	_c.Call.Return(run)
	return _c
}
