// Code generated by mockery (manually added). DO NOT EDIT.
package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"
	"github.com/umayangag/cric-info-scrapers/go-app/internal/predictor"
)

// Predictor is a testify/mock implementation of mlclient.Predictor.
type Predictor struct{ mock.Mock }

func (m *Predictor) PredictWin(ctx context.Context, players []predictor.PlayerPrediction) ([]predictor.PlayerPrediction, error) {
	args := m.Called(ctx, players)
	var res []predictor.PlayerPrediction
	if v := args.Get(0); v != nil {
		res = v.([]predictor.PlayerPrediction)
	}
	return res, args.Error(1)
}
