"""Pydantic models for ML service HTTP API and reconciliation.

Split by domain; import from ``app.models`` as before (re-exports preserve compatibility).
"""

from .backtest import (
    BacktestMatchAgg,
    BacktestMatchResponse,
    BacktestMetrics,
    BacktestPlayerPred,
    BacktestPlayersResponse,
    BacktestPredictRequest,
    BatchPredictItem,
    BatchPredictRequest,
    BatchPredictResponse,
    BatchPredictResultItem,
    GenerateMatchRequest,
    GenerateMatchResponse,
    HistoricalMatchBacktestRequest,
    HistoricalMatchBacktestResponse,
    HistoricalMatchFilter,
    InningsSummary,
    MatchComparison,
    MatchContext,
    PlayerComparison,
    PlayerPoint,
)
from .constants import BATTING_RAW_STAT_KEYS, BOWLING_RAW_STAT_KEYS
from .features import BattingFeatures, BowlingFeatures
from .predict import (
    BattingPrediction,
    BowlingPrediction,
    ExtrasFeatures,
    ExtrasPrediction,
    TeamOptimizationConstraints,
    TeamOptimizationPoolPlayer,
    TeamOptimizationRequest,
    TeamOptimizationResponse,
    TeamOptimizationSelectedPlayer,
    TeamOptimizationWeights,
    WinFeatures,
    WinFeaturesEnhanced,
    WinPrediction,
)
from .reconciliation import (
    InningsReconciliationPreferences,
    MatchReconciliationInputs,
    PlayerReconciliationPreferences,
)

__all__ = [
    "BATTING_RAW_STAT_KEYS",
    "BOWLING_RAW_STAT_KEYS",
    "BattingFeatures",
    "BowlingFeatures",
    "BattingPrediction",
    "BowlingPrediction",
    "ExtrasFeatures",
    "ExtrasPrediction",
    "WinFeatures",
    "WinFeaturesEnhanced",
    "WinPrediction",
    "MatchContext",
    "BacktestPredictRequest",
    "BacktestPlayerPred",
    "BacktestPlayersResponse",
    "GenerateMatchRequest",
    "InningsSummary",
    "GenerateMatchResponse",
    "BacktestMatchAgg",
    "BacktestMatchResponse",
    "TeamOptimizationPoolPlayer",
    "TeamOptimizationWeights",
    "TeamOptimizationConstraints",
    "TeamOptimizationRequest",
    "TeamOptimizationSelectedPlayer",
    "TeamOptimizationResponse",
    "BatchPredictItem",
    "BatchPredictRequest",
    "BatchPredictResultItem",
    "BatchPredictResponse",
    "HistoricalMatchFilter",
    "HistoricalMatchBacktestRequest",
    "PlayerPoint",
    "PlayerComparison",
    "MatchComparison",
    "BacktestMetrics",
    "HistoricalMatchBacktestResponse",
    "PlayerReconciliationPreferences",
    "InningsReconciliationPreferences",
    "MatchReconciliationInputs",
]
