// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/umayangag/cric-flow/go-app/internal/db"
)

// NewMockCricsheetDB creates a new instance of MockCricsheetDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCricsheetDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCricsheetDB {
	mock := &MockCricsheetDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCricsheetDB is an autogenerated mock type for the CricsheetDB type
type MockCricsheetDB struct {
	mock.Mock
}

type MockCricsheetDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCricsheetDB) EXPECT() *MockCricsheetDB_Expecter {
	return &MockCricsheetDB_Expecter{mock: &_m.Mock}
}

// ApplyTeamLineage provides a mock function for the type MockCricsheetDB
func (_mock *MockCricsheetDB) ApplyTeamLineage(ctx context.Context, renames []db.TeamRename) (int, error) {
	ret := _mock.Called(ctx, renames)

	if len(ret) == 0 {
		panic("no return value specified for ApplyTeamLineage")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []db.TeamRename) (int, error)); ok {
		return returnFunc(ctx, renames)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []db.TeamRename) int); ok {
		r0 = returnFunc(ctx, renames)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []db.TeamRename) error); ok {
		r1 = returnFunc(ctx, renames)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCricsheetDB_ApplyTeamLineage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyTeamLineage'
type MockCricsheetDB_ApplyTeamLineage_Call struct {
	*mock.Call
}

// ApplyTeamLineage is a helper method to define mock.On call
//   - ctx context.Context
//   - renames []db.TeamRename
func (_e *MockCricsheetDB_Expecter) ApplyTeamLineage(ctx interface{}, renames interface{}) *MockCricsheetDB_ApplyTeamLineage_Call {
	return &MockCricsheetDB_ApplyTeamLineage_Call{Call: _e.mock.On("ApplyTeamLineage", ctx, renames)}
}

func (_c *MockCricsheetDB_ApplyTeamLineage_Call) Run(run func(ctx context.Context, renames []db.TeamRename)) *MockCricsheetDB_ApplyTeamLineage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []db.TeamRename
		if args[1] != nil {
			arg1 = args[1].([]db.TeamRename)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCricsheetDB_ApplyTeamLineage_Call) Return(n int, err error) *MockCricsheetDB_ApplyTeamLineage_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockCricsheetDB_ApplyTeamLineage_Call) RunAndReturn(run func(ctx context.Context, renames []db.TeamRename) (int, error)) *MockCricsheetDB_ApplyTeamLineage_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function for the type MockCricsheetDB
func (_mock *MockCricsheetDB) Exec(ctx context.Context, sql string, args ...any) error {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, sql, args)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) error); ok {
		r0 = returnFunc(ctx, sql, args...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCricsheetDB_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockCricsheetDB_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...any
func (_e *MockCricsheetDB_Expecter) Exec(ctx interface{}, sql interface{}, args ...interface{}) *MockCricsheetDB_Exec_Call {
	return &MockCricsheetDB_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *MockCricsheetDB_Exec_Call) Run(run func(ctx context.Context, sql string, args ...any)) *MockCricsheetDB_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCricsheetDB_Exec_Call) Return(err error) *MockCricsheetDB_Exec_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCricsheetDB_Exec_Call) RunAndReturn(run func(ctx context.Context, sql string, args ...any) error) *MockCricsheetDB_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// GetMatchFormatIDByCode provides a mock function for the type MockCricsheetDB
func (_mock *MockCricsheetDB) GetMatchFormatIDByCode(ctx context.Context, code string) (int64, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetMatchFormatIDByCode")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, code)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCricsheetDB_GetMatchFormatIDByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMatchFormatIDByCode'
type MockCricsheetDB_GetMatchFormatIDByCode_Call struct {
	*mock.Call
}

// GetMatchFormatIDByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockCricsheetDB_Expecter) GetMatchFormatIDByCode(ctx interface{}, code interface{}) *MockCricsheetDB_GetMatchFormatIDByCode_Call {
	return &MockCricsheetDB_GetMatchFormatIDByCode_Call{Call: _e.mock.On("GetMatchFormatIDByCode", ctx, code)}
}

func (_c *MockCricsheetDB_GetMatchFormatIDByCode_Call) Run(run func(ctx context.Context, code string)) *MockCricsheetDB_GetMatchFormatIDByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCricsheetDB_GetMatchFormatIDByCode_Call) Return(n int64, err error) *MockCricsheetDB_GetMatchFormatIDByCode_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockCricsheetDB_GetMatchFormatIDByCode_Call) RunAndReturn(run func(ctx context.Context, code string) (int64, error)) *MockCricsheetDB_GetMatchFormatIDByCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrCreateOpposition provides a mock function for the type MockCricsheetDB
func (_mock *MockCricsheetDB) GetOrCreateOpposition(ctx context.Context, name string, gender string) (int64, error) {
	ret := _mock.Called(ctx, name, gender)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreateOpposition")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return returnFunc(ctx, name, gender)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = returnFunc(ctx, name, gender)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, name, gender)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCricsheetDB_GetOrCreateOpposition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreateOpposition'
type MockCricsheetDB_GetOrCreateOpposition_Call struct {
	*mock.Call
}

// GetOrCreateOpposition is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - gender string
func (_e *MockCricsheetDB_Expecter) GetOrCreateOpposition(ctx interface{}, name interface{}, gender interface{}) *MockCricsheetDB_GetOrCreateOpposition_Call {
	return &MockCricsheetDB_GetOrCreateOpposition_Call{Call: _e.mock.On("GetOrCreateOpposition", ctx, name, gender)}
}

func (_c *MockCricsheetDB_GetOrCreateOpposition_Call) Run(run func(ctx context.Context, name string, gender string)) *MockCricsheetDB_GetOrCreateOpposition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCricsheetDB_GetOrCreateOpposition_Call) Return(n int64, err error) *MockCricsheetDB_GetOrCreateOpposition_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockCricsheetDB_GetOrCreateOpposition_Call) RunAndReturn(run func(ctx context.Context, name string, gender string) (int64, error)) *MockCricsheetDB_GetOrCreateOpposition_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrCreatePlayer provides a mock function for the type MockCricsheetDB
func (_mock *MockCricsheetDB) GetOrCreatePlayer(ctx context.Context, externalID string, name string, nameAsOf string) (int64, string, error) {
	ret := _mock.Called(ctx, externalID, name, nameAsOf)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreatePlayer")
	}

	var r0 int64
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (int64, string, error)); ok {
		return returnFunc(ctx, externalID, name, nameAsOf)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) int64); ok {
		r0 = returnFunc(ctx, externalID, name, nameAsOf)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) string); ok {
		r1 = returnFunc(ctx, externalID, name, nameAsOf)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = returnFunc(ctx, externalID, name, nameAsOf)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockCricsheetDB_GetOrCreatePlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreatePlayer'
type MockCricsheetDB_GetOrCreatePlayer_Call struct {
	*mock.Call
}

// GetOrCreatePlayer is a helper method to define mock.On call
//   - ctx context.Context
//   - externalID string
//   - name string
//   - nameAsOf string
func (_e *MockCricsheetDB_Expecter) GetOrCreatePlayer(ctx interface{}, externalID interface{}, name interface{}, nameAsOf interface{}) *MockCricsheetDB_GetOrCreatePlayer_Call {
	return &MockCricsheetDB_GetOrCreatePlayer_Call{Call: _e.mock.On("GetOrCreatePlayer", ctx, externalID, name, nameAsOf)}
}

func (_c *MockCricsheetDB_GetOrCreatePlayer_Call) Run(run func(ctx context.Context, externalID string, name string, nameAsOf string)) *MockCricsheetDB_GetOrCreatePlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCricsheetDB_GetOrCreatePlayer_Call) Return(n int64, s string, err error) *MockCricsheetDB_GetOrCreatePlayer_Call {
	_c.Call.Return(n, s, err)
	return _c
}

func (_c *MockCricsheetDB_GetOrCreatePlayer_Call) RunAndReturn(run func(ctx context.Context, externalID string, name string, nameAsOf string) (int64, string, error)) *MockCricsheetDB_GetOrCreatePlayer_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrCreateSeason provides a mock function for the type MockCricsheetDB
func (_mock *MockCricsheetDB) GetOrCreateSeason(ctx context.Context, name string) (int64, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreateSeason")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCricsheetDB_GetOrCreateSeason_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreateSeason'
type MockCricsheetDB_GetOrCreateSeason_Call struct {
	*mock.Call
}

// GetOrCreateSeason is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockCricsheetDB_Expecter) GetOrCreateSeason(ctx interface{}, name interface{}) *MockCricsheetDB_GetOrCreateSeason_Call {
	return &MockCricsheetDB_GetOrCreateSeason_Call{Call: _e.mock.On("GetOrCreateSeason", ctx, name)}
}

func (_c *MockCricsheetDB_GetOrCreateSeason_Call) Run(run func(ctx context.Context, name string)) *MockCricsheetDB_GetOrCreateSeason_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCricsheetDB_GetOrCreateSeason_Call) Return(n int64, err error) *MockCricsheetDB_GetOrCreateSeason_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockCricsheetDB_GetOrCreateSeason_Call) RunAndReturn(run func(ctx context.Context, name string) (int64, error)) *MockCricsheetDB_GetOrCreateSeason_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrCreateVenue provides a mock function for the type MockCricsheetDB
func (_mock *MockCricsheetDB) GetOrCreateVenue(ctx context.Context, name string) (int64, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreateVenue")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCricsheetDB_GetOrCreateVenue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreateVenue'
type MockCricsheetDB_GetOrCreateVenue_Call struct {
	*mock.Call
}

// GetOrCreateVenue is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockCricsheetDB_Expecter) GetOrCreateVenue(ctx interface{}, name interface{}) *MockCricsheetDB_GetOrCreateVenue_Call {
	return &MockCricsheetDB_GetOrCreateVenue_Call{Call: _e.mock.On("GetOrCreateVenue", ctx, name)}
}

func (_c *MockCricsheetDB_GetOrCreateVenue_Call) Run(run func(ctx context.Context, name string)) *MockCricsheetDB_GetOrCreateVenue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCricsheetDB_GetOrCreateVenue_Call) Return(n int64, err error) *MockCricsheetDB_GetOrCreateVenue_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockCricsheetDB_GetOrCreateVenue_Call) RunAndReturn(run func(ctx context.Context, name string) (int64, error)) *MockCricsheetDB_GetOrCreateVenue_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePlayerDisplayNames provides a mock function for the type MockCricsheetDB
func (_mock *MockCricsheetDB) UpdatePlayerDisplayNames(ctx context.Context, names []db.PlayerDisplayName) error {
	ret := _mock.Called(ctx, names)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePlayerDisplayNames")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []db.PlayerDisplayName) error); ok {
		r0 = returnFunc(ctx, names)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCricsheetDB_UpdatePlayerDisplayNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePlayerDisplayNames'
type MockCricsheetDB_UpdatePlayerDisplayNames_Call struct {
	*mock.Call
}

// UpdatePlayerDisplayNames is a helper method to define mock.On call
//   - ctx context.Context
//   - names []db.PlayerDisplayName
func (_e *MockCricsheetDB_Expecter) UpdatePlayerDisplayNames(ctx interface{}, names interface{}) *MockCricsheetDB_UpdatePlayerDisplayNames_Call {
	return &MockCricsheetDB_UpdatePlayerDisplayNames_Call{Call: _e.mock.On("UpdatePlayerDisplayNames", ctx, names)}
}

func (_c *MockCricsheetDB_UpdatePlayerDisplayNames_Call) Run(run func(ctx context.Context, names []db.PlayerDisplayName)) *MockCricsheetDB_UpdatePlayerDisplayNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []db.PlayerDisplayName
		if args[1] != nil {
			arg1 = args[1].([]db.PlayerDisplayName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCricsheetDB_UpdatePlayerDisplayNames_Call) Return(err error) *MockCricsheetDB_UpdatePlayerDisplayNames_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCricsheetDB_UpdatePlayerDisplayNames_Call) RunAndReturn(run func(ctx context.Context, names []db.PlayerDisplayName) error) *MockCricsheetDB_UpdatePlayerDisplayNames_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertBatting provides a mock function for the type MockCricsheetDB
func (_mock *MockCricsheetDB) UpsertBatting(ctx context.Context, b *db.Batting) error {
	ret := _mock.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for UpsertBatting")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *db.Batting) error); ok {
		r0 = returnFunc(ctx, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCricsheetDB_UpsertBatting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertBatting'
type MockCricsheetDB_UpsertBatting_Call struct {
	*mock.Call
}

// UpsertBatting is a helper method to define mock.On call
//   - ctx context.Context
//   - b *db.Batting
func (_e *MockCricsheetDB_Expecter) UpsertBatting(ctx interface{}, b interface{}) *MockCricsheetDB_UpsertBatting_Call {
	return &MockCricsheetDB_UpsertBatting_Call{Call: _e.mock.On("UpsertBatting", ctx, b)}
}

func (_c *MockCricsheetDB_UpsertBatting_Call) Run(run func(ctx context.Context, b *db.Batting)) *MockCricsheetDB_UpsertBatting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *db.Batting
		if args[1] != nil {
			arg1 = args[1].(*db.Batting)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCricsheetDB_UpsertBatting_Call) Return(err error) *MockCricsheetDB_UpsertBatting_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCricsheetDB_UpsertBatting_Call) RunAndReturn(run func(ctx context.Context, b *db.Batting) error) *MockCricsheetDB_UpsertBatting_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertBattingBatch provides a mock function for the type MockCricsheetDB
func (_mock *MockCricsheetDB) UpsertBattingBatch(ctx context.Context, rows []db.Batting) error {
	ret := _mock.Called(ctx, rows)

	if len(ret) == 0 {
		panic("no return value specified for UpsertBattingBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []db.Batting) error); ok {
		r0 = returnFunc(ctx, rows)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCricsheetDB_UpsertBattingBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertBattingBatch'
type MockCricsheetDB_UpsertBattingBatch_Call struct {
	*mock.Call
}

// UpsertBattingBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - rows []db.Batting
func (_e *MockCricsheetDB_Expecter) UpsertBattingBatch(ctx interface{}, rows interface{}) *MockCricsheetDB_UpsertBattingBatch_Call {
	return &MockCricsheetDB_UpsertBattingBatch_Call{Call: _e.mock.On("UpsertBattingBatch", ctx, rows)}
}

func (_c *MockCricsheetDB_UpsertBattingBatch_Call) Run(run func(ctx context.Context, rows []db.Batting)) *MockCricsheetDB_UpsertBattingBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []db.Batting
		if args[1] != nil {
			arg1 = args[1].([]db.Batting)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCricsheetDB_UpsertBattingBatch_Call) Return(err error) *MockCricsheetDB_UpsertBattingBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCricsheetDB_UpsertBattingBatch_Call) RunAndReturn(run func(ctx context.Context, rows []db.Batting) error) *MockCricsheetDB_UpsertBattingBatch_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertBowling provides a mock function for the type MockCricsheetDB
func (_mock *MockCricsheetDB) UpsertBowling(ctx context.Context, b *db.Bowling) error {
	ret := _mock.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for UpsertBowling")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *db.Bowling) error); ok {
		r0 = returnFunc(ctx, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCricsheetDB_UpsertBowling_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertBowling'
type MockCricsheetDB_UpsertBowling_Call struct {
	*mock.Call
}

// UpsertBowling is a helper method to define mock.On call
//   - ctx context.Context
//   - b *db.Bowling
func (_e *MockCricsheetDB_Expecter) UpsertBowling(ctx interface{}, b interface{}) *MockCricsheetDB_UpsertBowling_Call {
	return &MockCricsheetDB_UpsertBowling_Call{Call: _e.mock.On("UpsertBowling", ctx, b)}
}

func (_c *MockCricsheetDB_UpsertBowling_Call) Run(run func(ctx context.Context, b *db.Bowling)) *MockCricsheetDB_UpsertBowling_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *db.Bowling
		if args[1] != nil {
			arg1 = args[1].(*db.Bowling)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCricsheetDB_UpsertBowling_Call) Return(err error) *MockCricsheetDB_UpsertBowling_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCricsheetDB_UpsertBowling_Call) RunAndReturn(run func(ctx context.Context, b *db.Bowling) error) *MockCricsheetDB_UpsertBowling_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertBowlingBatch provides a mock function for the type MockCricsheetDB
func (_mock *MockCricsheetDB) UpsertBowlingBatch(ctx context.Context, rows []db.Bowling) error {
	ret := _mock.Called(ctx, rows)

	if len(ret) == 0 {
		panic("no return value specified for UpsertBowlingBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []db.Bowling) error); ok {
		r0 = returnFunc(ctx, rows)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCricsheetDB_UpsertBowlingBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertBowlingBatch'
type MockCricsheetDB_UpsertBowlingBatch_Call struct {
	*mock.Call
}

// UpsertBowlingBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - rows []db.Bowling
func (_e *MockCricsheetDB_Expecter) UpsertBowlingBatch(ctx interface{}, rows interface{}) *MockCricsheetDB_UpsertBowlingBatch_Call {
	return &MockCricsheetDB_UpsertBowlingBatch_Call{Call: _e.mock.On("UpsertBowlingBatch", ctx, rows)}
}

func (_c *MockCricsheetDB_UpsertBowlingBatch_Call) Run(run func(ctx context.Context, rows []db.Bowling)) *MockCricsheetDB_UpsertBowlingBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []db.Bowling
		if args[1] != nil {
			arg1 = args[1].([]db.Bowling)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCricsheetDB_UpsertBowlingBatch_Call) Return(err error) *MockCricsheetDB_UpsertBowlingBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCricsheetDB_UpsertBowlingBatch_Call) RunAndReturn(run func(ctx context.Context, rows []db.Bowling) error) *MockCricsheetDB_UpsertBowlingBatch_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertFielding provides a mock function for the type MockCricsheetDB
func (_mock *MockCricsheetDB) UpsertFielding(ctx context.Context, f *db.Fielding) error {
	ret := _mock.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for UpsertFielding")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *db.Fielding) error); ok {
		r0 = returnFunc(ctx, f)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCricsheetDB_UpsertFielding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertFielding'
type MockCricsheetDB_UpsertFielding_Call struct {
	*mock.Call
}

// UpsertFielding is a helper method to define mock.On call
//   - ctx context.Context
//   - f *db.Fielding
func (_e *MockCricsheetDB_Expecter) UpsertFielding(ctx interface{}, f interface{}) *MockCricsheetDB_UpsertFielding_Call {
	return &MockCricsheetDB_UpsertFielding_Call{Call: _e.mock.On("UpsertFielding", ctx, f)}
}

func (_c *MockCricsheetDB_UpsertFielding_Call) Run(run func(ctx context.Context, f *db.Fielding)) *MockCricsheetDB_UpsertFielding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *db.Fielding
		if args[1] != nil {
			arg1 = args[1].(*db.Fielding)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCricsheetDB_UpsertFielding_Call) Return(err error) *MockCricsheetDB_UpsertFielding_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCricsheetDB_UpsertFielding_Call) RunAndReturn(run func(ctx context.Context, f *db.Fielding) error) *MockCricsheetDB_UpsertFielding_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertFieldingBatch provides a mock function for the type MockCricsheetDB
func (_mock *MockCricsheetDB) UpsertFieldingBatch(ctx context.Context, rows []db.Fielding) error {
	ret := _mock.Called(ctx, rows)

	if len(ret) == 0 {
		panic("no return value specified for UpsertFieldingBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []db.Fielding) error); ok {
		r0 = returnFunc(ctx, rows)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCricsheetDB_UpsertFieldingBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertFieldingBatch'
type MockCricsheetDB_UpsertFieldingBatch_Call struct {
	*mock.Call
}

// UpsertFieldingBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - rows []db.Fielding
func (_e *MockCricsheetDB_Expecter) UpsertFieldingBatch(ctx interface{}, rows interface{}) *MockCricsheetDB_UpsertFieldingBatch_Call {
	return &MockCricsheetDB_UpsertFieldingBatch_Call{Call: _e.mock.On("UpsertFieldingBatch", ctx, rows)}
}

func (_c *MockCricsheetDB_UpsertFieldingBatch_Call) Run(run func(ctx context.Context, rows []db.Fielding)) *MockCricsheetDB_UpsertFieldingBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []db.Fielding
		if args[1] != nil {
			arg1 = args[1].([]db.Fielding)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCricsheetDB_UpsertFieldingBatch_Call) Return(err error) *MockCricsheetDB_UpsertFieldingBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCricsheetDB_UpsertFieldingBatch_Call) RunAndReturn(run func(ctx context.Context, rows []db.Fielding) error) *MockCricsheetDB_UpsertFieldingBatch_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertMatch provides a mock function for the type MockCricsheetDB
func (_mock *MockCricsheetDB) UpsertMatch(ctx context.Context, m *db.MatchInsert) error {
	ret := _mock.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for UpsertMatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *db.MatchInsert) error); ok {
		r0 = returnFunc(ctx, m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCricsheetDB_UpsertMatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertMatch'
type MockCricsheetDB_UpsertMatch_Call struct {
	*mock.Call
}

// UpsertMatch is a helper method to define mock.On call
//   - ctx context.Context
//   - m *db.MatchInsert
func (_e *MockCricsheetDB_Expecter) UpsertMatch(ctx interface{}, m interface{}) *MockCricsheetDB_UpsertMatch_Call {
	return &MockCricsheetDB_UpsertMatch_Call{Call: _e.mock.On("UpsertMatch", ctx, m)}
}

func (_c *MockCricsheetDB_UpsertMatch_Call) Run(run func(ctx context.Context, m *db.MatchInsert)) *MockCricsheetDB_UpsertMatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *db.MatchInsert
		if args[1] != nil {
			arg1 = args[1].(*db.MatchInsert)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCricsheetDB_UpsertMatch_Call) Return(err error) *MockCricsheetDB_UpsertMatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCricsheetDB_UpsertMatch_Call) RunAndReturn(run func(ctx context.Context, m *db.MatchInsert) error) *MockCricsheetDB_UpsertMatch_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertMatchInning provides a mock function for the type MockCricsheetDB
func (_mock *MockCricsheetDB) UpsertMatchInning(ctx context.Context, mi *db.MatchInningInsert) error {
	ret := _mock.Called(ctx, mi)

	if len(ret) == 0 {
		panic("no return value specified for UpsertMatchInning")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *db.MatchInningInsert) error); ok {
		r0 = returnFunc(ctx, mi)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCricsheetDB_UpsertMatchInning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertMatchInning'
type MockCricsheetDB_UpsertMatchInning_Call struct {
	*mock.Call
}

// UpsertMatchInning is a helper method to define mock.On call
//   - ctx context.Context
//   - mi *db.MatchInningInsert
func (_e *MockCricsheetDB_Expecter) UpsertMatchInning(ctx interface{}, mi interface{}) *MockCricsheetDB_UpsertMatchInning_Call {
	return &MockCricsheetDB_UpsertMatchInning_Call{Call: _e.mock.On("UpsertMatchInning", ctx, mi)}
}

func (_c *MockCricsheetDB_UpsertMatchInning_Call) Run(run func(ctx context.Context, mi *db.MatchInningInsert)) *MockCricsheetDB_UpsertMatchInning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *db.MatchInningInsert
		if args[1] != nil {
			arg1 = args[1].(*db.MatchInningInsert)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCricsheetDB_UpsertMatchInning_Call) Return(err error) *MockCricsheetDB_UpsertMatchInning_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCricsheetDB_UpsertMatchInning_Call) RunAndReturn(run func(ctx context.Context, mi *db.MatchInningInsert) error) *MockCricsheetDB_UpsertMatchInning_Call {
	_c.Call.Return(run)
	return _c
}
