// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLoader creates a new instance of MockLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoader {
	mock := &MockLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoader is an autogenerated mock type for the Loader type
type MockLoader struct {
	mock.Mock
}

type MockLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoader) EXPECT() *MockLoader_Expecter {
	return &MockLoader_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockLoader
func (_mock *MockLoader) List(ctx context.Context, inDir string) ([]string, error) {
	ret := _mock.Called(ctx, inDir)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, inDir)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, inDir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, inDir)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoader_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockLoader_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - inDir string
func (_e *MockLoader_Expecter) List(ctx interface{}, inDir interface{}) *MockLoader_List_Call {
	return &MockLoader_List_Call{Call: _e.mock.On("List", ctx, inDir)}
}

func (_c *MockLoader_List_Call) Run(run func(ctx context.Context, inDir string)) *MockLoader_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoader_List_Call) Return(strings []string, err error) *MockLoader_List_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockLoader_List_Call) RunAndReturn(run func(ctx context.Context, inDir string) ([]string, error)) *MockLoader_List_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type MockLoader
func (_mock *MockLoader) Load(ctx context.Context, inDir string, id string) ([]byte, error) {
	ret := _mock.Called(ctx, inDir, id)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]byte, error)); ok {
		return returnFunc(ctx, inDir, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []byte); ok {
		r0 = returnFunc(ctx, inDir, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, inDir, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoader_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockLoader_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - inDir string
//   - id string
func (_e *MockLoader_Expecter) Load(ctx interface{}, inDir interface{}, id interface{}) *MockLoader_Load_Call {
	return &MockLoader_Load_Call{Call: _e.mock.On("Load", ctx, inDir, id)}
}

func (_c *MockLoader_Load_Call) Run(run func(ctx context.Context, inDir string, id string)) *MockLoader_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLoader_Load_Call) Return(bytes []byte, err error) *MockLoader_Load_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockLoader_Load_Call) RunAndReturn(run func(ctx context.Context, inDir string, id string) ([]byte, error)) *MockLoader_Load_Call {
	_c.Call.Return(run)
	return _c
}
