// Code generated by mockery (manually added for now). DO NOT EDIT.
package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"
	"github.com/umayangag/cric-info-scrapers/go-app/internal/db"
)

// CricsheetDBMock is a testify/mock implementation of cricsheet.CricsheetDB.
type CricsheetDBMock struct{ mock.Mock }

func (m *CricsheetDBMock) GetMatchFormatIDByCode(ctx context.Context, code string) (int64, error) {
	args := m.Called(ctx, code)
	return args.Get(0).(int64), args.Error(1)
}

func (m *CricsheetDBMock) EnsureMatchWithFormat(ctx context.Context, matchID int64, formatID int64, matchDate string) error {
	args := m.Called(ctx, matchID, formatID, matchDate)
	return args.Error(0)
}

func (m *CricsheetDBMock) GetOrCreateVenue(ctx context.Context, name string) (int64, error) {
	args := m.Called(ctx, name)
	return args.Get(0).(int64), args.Error(1)
}

func (m *CricsheetDBMock) GetOrCreateSeason(ctx context.Context, name string) (int64, error) {
	args := m.Called(ctx, name)
	return args.Get(0).(int64), args.Error(1)
}

func (m *CricsheetDBMock) GetOrCreateOpposition(ctx context.Context, name string) (int64, error) {
	args := m.Called(ctx, name)
	return args.Get(0).(int64), args.Error(1)
}

func (m *CricsheetDBMock) UpdateMatchDetails(ctx context.Context, matchID int64, upd *db.MatchInfoUpdate) error {
	args := m.Called(ctx, matchID, upd)
	return args.Error(0)
}

func (m *CricsheetDBMock) GetOrCreateByName(ctx context.Context, name string) (int64, error) {
	args := m.Called(ctx, name)
	return args.Get(0).(int64), args.Error(1)
}

func (m *CricsheetDBMock) UpsertBatting(ctx context.Context, b *db.Batting) error {
	args := m.Called(ctx, b)
	return args.Error(0)
}

func (m *CricsheetDBMock) UpsertBowling(ctx context.Context, b *db.Bowling) error {
	args := m.Called(ctx, b)
	return args.Error(0)
}

func (m *CricsheetDBMock) UpsertFielding(ctx context.Context, f *db.Fielding) error {
	args := m.Called(ctx, f)
	return args.Error(0)
}

func (m *CricsheetDBMock) Exec(ctx context.Context, sql string, argsIn ...any) error {
	args := m.Called(ctx, sql, argsIn)
	return args.Error(0)
}
