// Code generated by mockery (manually added for now). DO NOT EDIT.
package mocks

import (
	"context"
	"github.com/stretchr/testify/mock"
)

// WeatherClientMock is a testify/mock implementation of cricsheet.WeatherClient.
type WeatherClientMock struct{ mock.Mock }

func (m *WeatherClientMock) EnqueueJob(ctx context.Context, matchID int64, city, venue string, innings int) error {
	args := m.Called(ctx, matchID, city, venue, innings)
	return args.Error(0)
}
