// Code generated by mockery (manually added for now). DO NOT EDIT.
package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"
	"github.com/umayangag/cric-info-scrapers/go-app/internal/db"
)

// CricsheetDBMock is a testify/mock implementation of cricsheet.CricsheetDB.
type CricsheetDBMock struct{ mock.Mock }

func (m *CricsheetDBMock) GetMatchFormatIDByCode(ctx context.Context, code string) (int64, error) {
	args := m.Called(ctx, code)
	return args.Get(0).(int64), args.Error(1)
}

func (m *CricsheetDBMock) UpsertMatch(ctx context.Context, match *db.MatchInsert) error {
	args := m.Called(ctx, match)
	return args.Error(0)
}

func (m *CricsheetDBMock) UpsertMatchInning(ctx context.Context, mi *db.MatchInningInsert) error {
	args := m.Called(ctx, mi)
	return args.Error(0)
}

func (m *CricsheetDBMock) GetOrCreateVenue(ctx context.Context, name string) (int64, error) {
	args := m.Called(ctx, name)
	return args.Get(0).(int64), args.Error(1)
}

func (m *CricsheetDBMock) GetOrCreateSeason(ctx context.Context, name string) (int64, error) {
	args := m.Called(ctx, name)
	return args.Get(0).(int64), args.Error(1)
}

func (m *CricsheetDBMock) GetOrCreateOpposition(ctx context.Context, name string) (int64, error) {
	args := m.Called(ctx, name)
	return args.Get(0).(int64), args.Error(1)
}

func (m *CricsheetDBMock) GetOrCreateByName(ctx context.Context, name string) (int64, error) {
	args := m.Called(ctx, name)
	return args.Get(0).(int64), args.Error(1)
}

func (m *CricsheetDBMock) UpsertBatting(ctx context.Context, b *db.Batting) error {
	args := m.Called(ctx, b)
	return args.Error(0)
}

func (m *CricsheetDBMock) UpsertBattingBatch(ctx context.Context, rows []db.Batting) error {
	args := m.Called(ctx, rows)
	return args.Error(0)
}

func (m *CricsheetDBMock) UpsertBowling(ctx context.Context, b *db.Bowling) error {
	args := m.Called(ctx, b)
	return args.Error(0)
}

func (m *CricsheetDBMock) UpsertBowlingBatch(ctx context.Context, rows []db.Bowling) error {
	args := m.Called(ctx, rows)
	return args.Error(0)
}

func (m *CricsheetDBMock) UpsertFielding(ctx context.Context, f *db.Fielding) error {
	args := m.Called(ctx, f)
	return args.Error(0)
}

func (m *CricsheetDBMock) UpsertFieldingBatch(ctx context.Context, rows []db.Fielding) error {
	args := m.Called(ctx, rows)
	return args.Error(0)
}

func (m *CricsheetDBMock) Exec(ctx context.Context, sql string, argsIn ...any) error {
	args := m.Called(ctx, sql, argsIn)
	return args.Error(0)
}
