// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockWeatherClient creates a new instance of MockWeatherClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWeatherClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWeatherClient {
	mock := &MockWeatherClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWeatherClient is an autogenerated mock type for the WeatherClient type
type MockWeatherClient struct {
	mock.Mock
}

type MockWeatherClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWeatherClient) EXPECT() *MockWeatherClient_Expecter {
	return &MockWeatherClient_Expecter{mock: &_m.Mock}
}

// EnqueueJob provides a mock function for the type MockWeatherClient
func (_mock *MockWeatherClient) EnqueueJob(ctx context.Context, matchID int64, city string, venue string, innings int) error {
	ret := _mock.Called(ctx, matchID, city, venue, innings)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string, int) error); ok {
		r0 = returnFunc(ctx, matchID, city, venue, innings)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWeatherClient_EnqueueJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueJob'
type MockWeatherClient_EnqueueJob_Call struct {
	*mock.Call
}

// EnqueueJob is a helper method to define mock.On call
//   - ctx context.Context
//   - matchID int64
//   - city string
//   - venue string
//   - innings int
func (_e *MockWeatherClient_Expecter) EnqueueJob(ctx interface{}, matchID interface{}, city interface{}, venue interface{}, innings interface{}) *MockWeatherClient_EnqueueJob_Call {
	return &MockWeatherClient_EnqueueJob_Call{Call: _e.mock.On("EnqueueJob", ctx, matchID, city, venue, innings)}
}

func (_c *MockWeatherClient_EnqueueJob_Call) Run(run func(ctx context.Context, matchID int64, city string, venue string, innings int)) *MockWeatherClient_EnqueueJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockWeatherClient_EnqueueJob_Call) Return(err error) *MockWeatherClient_EnqueueJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWeatherClient_EnqueueJob_Call) RunAndReturn(run func(ctx context.Context, matchID int64, city string, venue string, innings int) error) *MockWeatherClient_EnqueueJob_Call {
	_c.Call.Return(run)
	return _c
}
