// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockKeeperRepository creates a new instance of MockKeeperRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeeperRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeeperRepository {
	mock := &MockKeeperRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKeeperRepository is an autogenerated mock type for the KeeperRepository type
type MockKeeperRepository struct {
	mock.Mock
}

type MockKeeperRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeeperRepository) EXPECT() *MockKeeperRepository_Expecter {
	return &MockKeeperRepository_Expecter{mock: &_m.Mock}
}

// CountPlayersByLowerName provides a mock function for the type MockKeeperRepository
func (_mock *MockKeeperRepository) CountPlayersByLowerName(ctx context.Context, lowerName string) (int64, error) {
	ret := _mock.Called(ctx, lowerName)

	if len(ret) == 0 {
		panic("no return value specified for CountPlayersByLowerName")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, lowerName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, lowerName)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, lowerName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeeperRepository_CountPlayersByLowerName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountPlayersByLowerName'
type MockKeeperRepository_CountPlayersByLowerName_Call struct {
	*mock.Call
}

// CountPlayersByLowerName is a helper method to define mock.On call
//   - ctx context.Context
//   - lowerName string
func (_e *MockKeeperRepository_Expecter) CountPlayersByLowerName(ctx interface{}, lowerName interface{}) *MockKeeperRepository_CountPlayersByLowerName_Call {
	return &MockKeeperRepository_CountPlayersByLowerName_Call{Call: _e.mock.On("CountPlayersByLowerName", ctx, lowerName)}
}

func (_c *MockKeeperRepository_CountPlayersByLowerName_Call) Run(run func(ctx context.Context, lowerName string)) *MockKeeperRepository_CountPlayersByLowerName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeeperRepository_CountPlayersByLowerName_Call) Return(n int64, err error) *MockKeeperRepository_CountPlayersByLowerName_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockKeeperRepository_CountPlayersByLowerName_Call) RunAndReturn(run func(ctx context.Context, lowerName string) (int64, error)) *MockKeeperRepository_CountPlayersByLowerName_Call {
	_c.Call.Return(run)
	return _c
}

// SetIsWicketKeeperByLowerName provides a mock function for the type MockKeeperRepository
func (_mock *MockKeeperRepository) SetIsWicketKeeperByLowerName(ctx context.Context, value int, lowerName string) (int64, error) {
	ret := _mock.Called(ctx, value, lowerName)

	if len(ret) == 0 {
		panic("no return value specified for SetIsWicketKeeperByLowerName")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) (int64, error)); ok {
		return returnFunc(ctx, value, lowerName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) int64); ok {
		r0 = returnFunc(ctx, value, lowerName)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = returnFunc(ctx, value, lowerName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeeperRepository_SetIsWicketKeeperByLowerName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetIsWicketKeeperByLowerName'
type MockKeeperRepository_SetIsWicketKeeperByLowerName_Call struct {
	*mock.Call
}

// SetIsWicketKeeperByLowerName is a helper method to define mock.On call
//   - ctx context.Context
//   - value int
//   - lowerName string
func (_e *MockKeeperRepository_Expecter) SetIsWicketKeeperByLowerName(ctx interface{}, value interface{}, lowerName interface{}) *MockKeeperRepository_SetIsWicketKeeperByLowerName_Call {
	return &MockKeeperRepository_SetIsWicketKeeperByLowerName_Call{Call: _e.mock.On("SetIsWicketKeeperByLowerName", ctx, value, lowerName)}
}

func (_c *MockKeeperRepository_SetIsWicketKeeperByLowerName_Call) Run(run func(ctx context.Context, value int, lowerName string)) *MockKeeperRepository_SetIsWicketKeeperByLowerName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKeeperRepository_SetIsWicketKeeperByLowerName_Call) Return(n int64, err error) *MockKeeperRepository_SetIsWicketKeeperByLowerName_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockKeeperRepository_SetIsWicketKeeperByLowerName_Call) RunAndReturn(run func(ctx context.Context, value int, lowerName string) (int64, error)) *MockKeeperRepository_SetIsWicketKeeperByLowerName_Call {
	_c.Call.Return(run)
	return _c
}

// ZeroKeepersExcept provides a mock function for the type MockKeeperRepository
func (_mock *MockKeeperRepository) ZeroKeepersExcept(ctx context.Context, lowerNames []string) (int64, error) {
	ret := _mock.Called(ctx, lowerNames)

	if len(ret) == 0 {
		panic("no return value specified for ZeroKeepersExcept")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (int64, error)); ok {
		return returnFunc(ctx, lowerNames)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) int64); ok {
		r0 = returnFunc(ctx, lowerNames)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, lowerNames)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeeperRepository_ZeroKeepersExcept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ZeroKeepersExcept'
type MockKeeperRepository_ZeroKeepersExcept_Call struct {
	*mock.Call
}

// ZeroKeepersExcept is a helper method to define mock.On call
//   - ctx context.Context
//   - lowerNames []string
func (_e *MockKeeperRepository_Expecter) ZeroKeepersExcept(ctx interface{}, lowerNames interface{}) *MockKeeperRepository_ZeroKeepersExcept_Call {
	return &MockKeeperRepository_ZeroKeepersExcept_Call{Call: _e.mock.On("ZeroKeepersExcept", ctx, lowerNames)}
}

func (_c *MockKeeperRepository_ZeroKeepersExcept_Call) Run(run func(ctx context.Context, lowerNames []string)) *MockKeeperRepository_ZeroKeepersExcept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeeperRepository_ZeroKeepersExcept_Call) Return(n int64, err error) *MockKeeperRepository_ZeroKeepersExcept_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockKeeperRepository_ZeroKeepersExcept_Call) RunAndReturn(run func(ctx context.Context, lowerNames []string) (int64, error)) *MockKeeperRepository_ZeroKeepersExcept_Call {
	_c.Call.Return(run)
	return _c
}
