import type { ModelMetadataResponse } from '../types';

// Fallback when GET /api/ml/model-metadata is unavailable (e.g. ML service down). Kept in sync with ml-service for offline/dev.
export const DEFAULT_MODEL_FEATURES: ModelMetadataResponse = {
  batting: {
    level: 'player',
    hasScaler: true,
    artifactsPattern: {
      perFormat: 'batting_scaler_<FMT>.joblib + batting_model_<FMT>.joblib',
      legacy: 'batting_scaler.joblib + batting_model.joblib',
    },
    features: [
      'batting_consistency',
      'batting_form',
      'batting_form_short',
      'batting_form_long',
      'batting_momentum',
      'batting_temp',
      'batting_wind',
      'batting_rain',
      'batting_humidity',
      'batting_cloud',
      'batting_pressure',
      'batting_viscosity',
      'batting_inning',
      'batting_session',
      'toss',
      'venue',
      'opposition',
      'season',
      'bat_prev_sr',
      'bat_prev_out_rate',
      'bat_window_sr_12_pp',
      'bat_window_boundary_rate_12_pp',
      'bat_entry_sr_1_6',
      'bat_set_sr_13_30',
      'bat_react_after_dot_sr',
      'bat_after_k_dots_boundary_p_k2',
    ],
    outputs: [
      'runs_scored',
      'balls_faced',
      'fours_scored',
      'sixes_scored',
      'batting_position',
      'strike_rate',
    ],
    note: 'Player-level; same feature families used for match-level models. Prediction uses per-format model when format (e.g. T20) is provided and loaded; otherwise legacy.',
  },
  bowling: {
    level: 'player',
    hasScaler: true,
    artifactsPattern: {
      perFormat: 'bowling_scaler_<FMT>.joblib + bowling_model_<FMT>.joblib',
      legacy: 'bowling_scaler.joblib + bowling_model.joblib',
    },
    features: [
      'bowling_consistency',
      'bowling_form',
      'bowling_momentum',
      'bowling_career_avg',
      'bowling_temp',
      'bowling_wind',
      'bowling_rain',
      'bowling_humidity',
      'bowling_cloud',
      'bowling_pressure',
      'bowling_viscosity',
      'batting_inning',
      'bowling_session',
      'toss',
      'bowling_venue',
      'bowling_opposition',
      'season',
      'bowl_prev_wkt_rate',
      'bowl_window_econ_24_death',
      'bowl_window_wkt_rate_24_death',
      'bowl_extras_wide_rate_pp',
      'bowl_react_after_boundary_wkt_rate_next',
      'bowl_spell_first_over_wkt_rate',
      'bowl_over_ball1_wkt_rate',
      'bowl_over_ball6_wkt_rate',
    ],
    outputs: ['runs_conceded', 'deliveries', 'wickets_taken', 'economy'],
    note: 'Player-level; aggregates feed into extras and win. Per-format and legacy same as batting.',
  },
  fielding: {
    level: 'player',
    hasScaler: true,
    artifactsPattern: {
      perFormat: 'fielding_scaler_<FMT>.joblib + fielding_model_<FMT>.joblib',
      legacy: 'fielding_scaler.joblib + fielding_model.joblib',
    },
    features: [
      'fielding_consistency',
      'fielding_form',
      'fielding_temp',
      'fielding_wind',
      'fielding_rain',
      'fielding_humidity',
      'fielding_cloud',
      'fielding_pressure',
      'fielding_viscosity',
      'inning',
      'toss',
      'fielding_venue',
      'fielding_opposition',
      'season_id',
    ],
    outputs: ['catches', 'run_outs', 'stumpings'],
    note: 'Player-level; combined with batting/bowling for team selection. Per-format and legacy same as batting.',
  },
  extras: {
    level: 'match',
    hasScaler: false,
    artifactsPattern: {
      perFormat: 'extras_model_<FMT>.joblib',
      legacy: 'extras_model.joblib',
    },
    features: [
      'format_id',
      'venue_id',
      'season_id',
      'temp',
      'wind',
      'rain',
      'humidity',
      'cloud',
      'pressure',
      'viscosity',
      'bat_consistency_sum',
      'bowl_consistency_sum',
      'bat_form_sum',
      'bowl_form_sum',
    ],
    outputs: ['total_extras'],
    note: 'Match-level; uses same weather + aggregates of player consistency/form from batting/bowling snapshot data. One model per format or legacy.',
  },
  win: {
    level: 'match',
    hasScaler: false,
    artifactsPattern: {
      perFormat: 'win_model_<FMT>.joblib',
      legacy: 'win_model.joblib',
    },
    features: [
      'format_id',
      'venue_id',
      'team1_opposition_id',
      'team2_opposition_id',
      'toss_winner_opposition_id',
      'temp',
      'wind',
      'rain',
      'humidity',
      'cloud',
      'pressure',
      'viscosity',
      'team1_bat_consistency_sum',
      'team1_bowl_consistency_sum',
      'team2_bat_consistency_sum',
      'team2_bowl_consistency_sum',
      'team1_bat_form_sum',
      'team1_bowl_form_sum',
      'team2_bat_form_sum',
      'team2_bowl_form_sum',
    ],
    outputs: ['team1_win_probability'],
    note: 'Match-level; team1 = batting first, team2 = bowling first. Same feature families as batting/bowling/fielding. One model per format or legacy.',
  },
  combination_meta: {
    level: 'meta',
    hasScaler: false,
    artifactsPattern: {
      perFormat: 'Optional per-format weights in combination_meta.json',
      legacy: 'combination_meta.json (unified weights)',
    },
    features: ['bat_score', 'bowl_score', 'field_score', 'is_keeper', 'format (one-hot)'],
    outputs: ['score_weights (Ridge coefficients for team selection)'],
    note: 'Optional. Learns weights to combine batting/bowling/fielding scores from backtest outcomes. Uses CSV with bat_score, bowl_score, field_score, is_keeper, format, target. Output is JSON (not joblib); go-app can load via selection.meta_model_path.',
  },
};

export const MODEL_KEYS = [
  'batting',
  'bowling',
  'fielding',
  'extras',
  'win',
  'combination_meta',
] as const;
