// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/umayangag/cric-info-scrapers/go-app/internal/services/etlimporter"
)

// NewMockIngestor creates a new instance of MockIngestor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIngestor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIngestor {
	mock := &MockIngestor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIngestor is an autogenerated mock type for the Ingestor type
type MockIngestor struct {
	mock.Mock
}

type MockIngestor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIngestor) EXPECT() *MockIngestor_Expecter {
	return &MockIngestor_Expecter{mock: &_m.Mock}
}

// IngestDir provides a mock function for the type MockIngestor
func (_mock *MockIngestor) IngestDir(ctx context.Context, dir string, pattern string, apply bool, conc int) (etlimporter.Stats, error) {
	ret := _mock.Called(ctx, dir, pattern, apply, conc)

	if len(ret) == 0 {
		panic("no return value specified for IngestDir")
	}

	var r0 etlimporter.Stats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool, int) (etlimporter.Stats, error)); ok {
		return returnFunc(ctx, dir, pattern, apply, conc)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool, int) etlimporter.Stats); ok {
		r0 = returnFunc(ctx, dir, pattern, apply, conc)
	} else {
		r0 = ret.Get(0).(etlimporter.Stats)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, bool, int) error); ok {
		r1 = returnFunc(ctx, dir, pattern, apply, conc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIngestor_IngestDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IngestDir'
type MockIngestor_IngestDir_Call struct {
	*mock.Call
}

// IngestDir is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - pattern string
//   - apply bool
//   - conc int
func (_e *MockIngestor_Expecter) IngestDir(ctx interface{}, dir interface{}, pattern interface{}, apply interface{}, conc interface{}) *MockIngestor_IngestDir_Call {
	return &MockIngestor_IngestDir_Call{Call: _e.mock.On("IngestDir", ctx, dir, pattern, apply, conc)}
}

func (_c *MockIngestor_IngestDir_Call) Run(run func(ctx context.Context, dir string, pattern string, apply bool, conc int)) *MockIngestor_IngestDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockIngestor_IngestDir_Call) Return(stats etlimporter.Stats, err error) *MockIngestor_IngestDir_Call {
	_c.Call.Return(stats, err)
	return _c
}

func (_c *MockIngestor_IngestDir_Call) RunAndReturn(run func(ctx context.Context, dir string, pattern string, apply bool, conc int) (etlimporter.Stats, error)) *MockIngestor_IngestDir_Call {
	_c.Call.Return(run)
	return _c
}
