-- 0001_baseline.sql
--
-- Consolidated baseline schema. Replaces migrations 0001-0095, which were squashed
-- because the data is reproducible from the Cricsheet source files: migration 0090
-- already truncated every fact table on exactly that basis, so the incremental chain
-- carried no state worth replaying.
--
-- Generated with:
--   pg_dump --schema-only --no-owner --no-privileges --no-comments \
--           --exclude-table=schema_migrations
-- against a database bootstrapped through the full 0001-0095 chain, then hand-edited
-- to drop psql meta-commands and session SET noise, and to restore the seed rows
-- pg_dump omits (see "Seed data" at the end).
--
-- schema_migrations is deliberately absent: the migration runner creates it itself
-- before applying anything.
--
-- To change the schema, add a new numbered migration; do not edit this file.

BEGIN;

-- Name: mpa_set_updated_at(); Type: FUNCTION; Schema: public

CREATE FUNCTION public.mpa_set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

-- Name: set_updated_at_column(); Type: FUNCTION; Schema: public

CREATE FUNCTION public.set_updated_at_column() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

-- Name: ball_event; Type: TABLE; Schema: public

CREATE TABLE public.ball_event (
    match_id bigint NOT NULL,
    innings smallint NOT NULL,
    over smallint NOT NULL,
    ball smallint NOT NULL,
    ball_seq integer NOT NULL,
    is_legal boolean NOT NULL,
    phase character varying(16) NOT NULL,
    striker_id bigint,
    non_striker_id bigint,
    bowler_id bigint,
    runs_batter smallint DEFAULT 0 NOT NULL,
    runs_extras smallint DEFAULT 0 NOT NULL,
    runs_total smallint DEFAULT 0 NOT NULL,
    extras_kind character varying(16),
    wicket_kind character varying(24),
    player_out_id bigint,
    fielder_ids bigint[]
);

-- Name: batting_data; Type: TABLE; Schema: public

CREATE TABLE public.batting_data (
    id bigint NOT NULL,
    match_id bigint NOT NULL,
    player_id bigint NOT NULL,
    description character varying(250),
    runs integer,
    balls integer,
    minutes integer,
    fours integer,
    sixes integer,
    strike_rate real,
    batting_position integer,
    inning_number smallint DEFAULT 1 NOT NULL
);

-- Name: batting_data_id_seq; Type: SEQUENCE; Schema: public

CREATE SEQUENCE public.batting_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: batting_data_id_seq; Type: SEQUENCE OWNED BY; Schema: public

ALTER SEQUENCE public.batting_data_id_seq OWNED BY public.batting_data.id;

-- Name: batting_transition_features; Type: TABLE; Schema: public

CREATE TABLE public.batting_transition_features (
    as_of_date date NOT NULL,
    format_id smallint NOT NULL,
    scope character varying(16) DEFAULT 'overall'::character varying NOT NULL,
    scope_id bigint DEFAULT 0 NOT NULL,
    prev_batter_id bigint NOT NULL,
    batter_id bigint NOT NULL,
    phase character varying(16) NOT NULL,
    balls integer NOT NULL,
    runs integer NOT NULL,
    dismissals integer NOT NULL,
    fours integer NOT NULL,
    sixes integer NOT NULL,
    strike_rate real GENERATED ALWAYS AS (
CASE
    WHEN (balls > 0) THEN (((runs)::double precision * (100)::double precision) / (balls)::double precision)
    ELSE (0)::double precision
END) STORED,
    out_rate real GENERATED ALWAYS AS (
CASE
    WHEN (balls > 0) THEN ((dismissals)::double precision / (balls)::double precision)
    ELSE (0)::double precision
END) STORED
);

-- Name: bowling_data; Type: TABLE; Schema: public

CREATE TABLE public.bowling_data (
    id bigint NOT NULL,
    match_id bigint NOT NULL,
    player_id bigint NOT NULL,
    overs real,
    balls integer,
    maidens integer,
    runs integer,
    wickets integer,
    dots integer,
    fours integer,
    sixes integer,
    econ real,
    wides integer,
    no_balls integer,
    inning_number smallint DEFAULT 1 NOT NULL
);

-- Name: bowling_data_id_seq; Type: SEQUENCE; Schema: public

CREATE SEQUENCE public.bowling_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: bowling_data_id_seq; Type: SEQUENCE OWNED BY; Schema: public

ALTER SEQUENCE public.bowling_data_id_seq OWNED BY public.bowling_data.id;

-- Name: bowling_sequence_features; Type: TABLE; Schema: public

CREATE TABLE public.bowling_sequence_features (
    as_of_date date NOT NULL,
    format_id smallint NOT NULL,
    scope character varying(16) DEFAULT 'overall'::character varying NOT NULL,
    scope_id bigint,
    scope_id0 bigint GENERATED ALWAYS AS (COALESCE(scope_id, (0)::bigint)) STORED NOT NULL,
    prev_bowler_id bigint NOT NULL,
    bowler_id bigint NOT NULL,
    phase character varying(16) NOT NULL,
    overs_pairs integer NOT NULL,
    balls integer NOT NULL,
    runs integer NOT NULL,
    wickets integer NOT NULL,
    dot_balls integer NOT NULL
);

-- Name: bowling_spell_features; Type: TABLE; Schema: public

CREATE TABLE public.bowling_spell_features (
    as_of_date date NOT NULL,
    format_id integer NOT NULL,
    scope text DEFAULT 'overall'::text NOT NULL,
    scope_id integer,
    scope_id0 integer GENERATED ALWAYS AS (COALESCE(scope_id, 0)) STORED NOT NULL,
    player_id bigint NOT NULL,
    phase text NOT NULL,
    spells integer DEFAULT 0 NOT NULL,
    spell_overs integer DEFAULT 0 NOT NULL,
    first_overs_balls integer DEFAULT 0 NOT NULL,
    first_overs_runs integer DEFAULT 0 NOT NULL,
    first_overs_wickets integer DEFAULT 0 NOT NULL,
    first_overs_dots integer DEFAULT 0 NOT NULL,
    first_overs_boundaries integer DEFAULT 0 NOT NULL,
    later_overs_balls integer DEFAULT 0 NOT NULL,
    later_overs_runs integer DEFAULT 0 NOT NULL,
    later_overs_wickets integer DEFAULT 0 NOT NULL,
    later_overs_dots integer DEFAULT 0 NOT NULL,
    later_overs_boundaries integer DEFAULT 0 NOT NULL,
    first_over_econ double precision DEFAULT 0 NOT NULL,
    later_over_econ double precision DEFAULT 0 NOT NULL
);

-- Name: data_migrations; Type: TABLE; Schema: public

CREATE TABLE public.data_migrations (
    id integer NOT NULL,
    command character varying(255) NOT NULL,
    args jsonb,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone,
    status character varying(50) NOT NULL,
    metadata jsonb,
    error_message text
);

-- Name: data_migrations_id_seq; Type: SEQUENCE; Schema: public

CREATE SEQUENCE public.data_migrations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: data_migrations_id_seq; Type: SEQUENCE OWNED BY; Schema: public

ALTER SEQUENCE public.data_migrations_id_seq OWNED BY public.data_migrations.id;

-- Name: dot_streak_features; Type: TABLE; Schema: public

CREATE TABLE public.dot_streak_features (
    as_of_date date NOT NULL,
    format_id smallint NOT NULL,
    scope character varying(16) DEFAULT 'overall'::character varying NOT NULL,
    scope_id bigint DEFAULT 0 NOT NULL,
    player_id bigint NOT NULL,
    role character varying(8) NOT NULL,
    k smallint NOT NULL,
    phase character varying(16) NOT NULL,
    balls integer NOT NULL,
    runs_next_total integer NOT NULL,
    next_boundary integer NOT NULL,
    next_single integer NOT NULL,
    next_wicket integer NOT NULL,
    next_extra integer NOT NULL,
    next_dot integer NOT NULL,
    avg_runs_next_ball real GENERATED ALWAYS AS (
CASE
    WHEN (balls > 0) THEN ((runs_next_total)::double precision / (balls)::double precision)
    ELSE (0)::double precision
END) STORED,
    p_boundary real GENERATED ALWAYS AS (
CASE
    WHEN (balls > 0) THEN ((next_boundary)::double precision / (balls)::double precision)
    ELSE (0)::double precision
END) STORED,
    p_single real GENERATED ALWAYS AS (
CASE
    WHEN (balls > 0) THEN ((next_single)::double precision / (balls)::double precision)
    ELSE (0)::double precision
END) STORED,
    p_wicket real GENERATED ALWAYS AS (
CASE
    WHEN (balls > 0) THEN ((next_wicket)::double precision / (balls)::double precision)
    ELSE (0)::double precision
END) STORED,
    p_extra real GENERATED ALWAYS AS (
CASE
    WHEN (balls > 0) THEN ((next_extra)::double precision / (balls)::double precision)
    ELSE (0)::double precision
END) STORED,
    p_dot real GENERATED ALWAYS AS (
CASE
    WHEN (balls > 0) THEN ((next_dot)::double precision / (balls)::double precision)
    ELSE (0)::double precision
END) STORED,
    CONSTRAINT dot_streak_features_role_check CHECK (((role)::text = ANY ((ARRAY['bat'::character varying, 'bowl'::character varying])::text[])))
);

-- Name: event_reaction_features; Type: TABLE; Schema: public

CREATE TABLE public.event_reaction_features (
    as_of_date date NOT NULL,
    format_id smallint NOT NULL,
    scope character varying(16) DEFAULT 'overall'::character varying NOT NULL,
    scope_id bigint DEFAULT 0 NOT NULL,
    player_id bigint NOT NULL,
    role character varying(8) NOT NULL,
    prev_event character varying(16) NOT NULL,
    phase character varying(16) NOT NULL,
    balls integer NOT NULL,
    runs integer NOT NULL,
    dismissals integer NOT NULL,
    boundaries integer NOT NULL,
    wickets integer NOT NULL,
    dot_balls integer NOT NULL,
    boundaries_conceded integer NOT NULL,
    sr real GENERATED ALWAYS AS (
CASE
    WHEN (balls > 0) THEN (((runs)::double precision * (100)::double precision) / (balls)::double precision)
    ELSE (0)::double precision
END) STORED,
    boundary_rate real GENERATED ALWAYS AS (
CASE
    WHEN (balls > 0) THEN ((boundaries)::double precision / (balls)::double precision)
    ELSE (0)::double precision
END) STORED,
    dot_rate real GENERATED ALWAYS AS (
CASE
    WHEN (balls > 0) THEN ((dot_balls)::double precision / (balls)::double precision)
    ELSE (0)::double precision
END) STORED,
    wicket_rate real GENERATED ALWAYS AS (
CASE
    WHEN (balls > 0) THEN ((wickets)::double precision / (balls)::double precision)
    ELSE (0)::double precision
END) STORED,
    econ real GENERATED ALWAYS AS (
CASE
    WHEN (balls > 0) THEN (((runs)::double precision * (6)::double precision) / (balls)::double precision)
    ELSE (0)::double precision
END) STORED,
    CONSTRAINT event_reaction_features_role_check CHECK (((role)::text = ANY ((ARRAY['bat'::character varying, 'bowl'::character varying])::text[])))
);

-- Name: extras_discipline_features; Type: TABLE; Schema: public

CREATE TABLE public.extras_discipline_features (
    as_of_date date NOT NULL,
    format_id integer NOT NULL,
    scope text DEFAULT 'overall'::text NOT NULL,
    scope_id integer,
    scope_id0 integer GENERATED ALWAYS AS (COALESCE(scope_id, 0)) STORED NOT NULL,
    player_id bigint NOT NULL,
    phase text NOT NULL,
    overs integer DEFAULT 0 NOT NULL,
    balls_bowled integer DEFAULT 0 NOT NULL,
    runs_conceded integer DEFAULT 0 NOT NULL,
    wickets integer DEFAULT 0 NOT NULL,
    wides integer DEFAULT 0 NOT NULL,
    no_balls integer DEFAULT 0 NOT NULL,
    byes integer DEFAULT 0 NOT NULL,
    leg_byes integer DEFAULT 0 NOT NULL,
    penalty_runs integer DEFAULT 0 NOT NULL,
    extras_total integer DEFAULT 0 NOT NULL,
    wides_per_over double precision DEFAULT 0 NOT NULL,
    no_balls_per_over double precision DEFAULT 0 NOT NULL,
    extras_per_over double precision DEFAULT 0 NOT NULL
);

-- Name: feature_raw_stats_snapshots; Type: TABLE; Schema: public

CREATE TABLE public.feature_raw_stats_snapshots (
    id bigint NOT NULL,
    player_id bigint NOT NULL,
    as_of_date date NOT NULL,
    format_id bigint NOT NULL,
    scope text NOT NULL,
    scope_id bigint,
    batting_mean_w3 double precision DEFAULT 0 NOT NULL,
    batting_mean_w5 double precision DEFAULT 0 NOT NULL,
    batting_mean_w10 double precision DEFAULT 0 NOT NULL,
    batting_mean_w20 double precision DEFAULT 0 NOT NULL,
    batting_std_w5 double precision DEFAULT 0 NOT NULL,
    batting_std_w10 double precision DEFAULT 0 NOT NULL,
    batting_max_w10 double precision DEFAULT 0 NOT NULL,
    batting_min_w10 double precision DEFAULT 0 NOT NULL,
    batting_median_w10 double precision DEFAULT 0 NOT NULL,
    batting_last_1 double precision DEFAULT 0 NOT NULL,
    batting_last_2 double precision DEFAULT 0 NOT NULL,
    batting_last_3 double precision DEFAULT 0 NOT NULL,
    batting_career_mean double precision DEFAULT 0 NOT NULL,
    batting_career_count integer DEFAULT 0 NOT NULL,
    batting_pct_zero_w10 double precision DEFAULT 0 NOT NULL,
    batting_trend_w5 double precision DEFAULT 0 NOT NULL,
    batting_days_since_last double precision DEFAULT 0 NOT NULL,
    batting_innings_in_last_90d integer DEFAULT 0 NOT NULL,
    bowling_mean_w3 double precision DEFAULT 0 NOT NULL,
    bowling_mean_w5 double precision DEFAULT 0 NOT NULL,
    bowling_mean_w10 double precision DEFAULT 0 NOT NULL,
    bowling_mean_w20 double precision DEFAULT 0 NOT NULL,
    bowling_std_w5 double precision DEFAULT 0 NOT NULL,
    bowling_std_w10 double precision DEFAULT 0 NOT NULL,
    bowling_max_w10 double precision DEFAULT 0 NOT NULL,
    bowling_min_w10 double precision DEFAULT 0 NOT NULL,
    bowling_median_w10 double precision DEFAULT 0 NOT NULL,
    bowling_last_1 double precision DEFAULT 0 NOT NULL,
    bowling_last_2 double precision DEFAULT 0 NOT NULL,
    bowling_last_3 double precision DEFAULT 0 NOT NULL,
    bowling_career_mean double precision DEFAULT 0 NOT NULL,
    bowling_career_count integer DEFAULT 0 NOT NULL,
    bowling_pct_zero_w10 double precision DEFAULT 0 NOT NULL,
    bowling_trend_w5 double precision DEFAULT 0 NOT NULL,
    bowling_days_since_last double precision DEFAULT 0 NOT NULL,
    bowling_innings_in_last_90d integer DEFAULT 0 NOT NULL,
    source_version text DEFAULT 'v2'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT feature_raw_stats_snapshots_scope_check CHECK ((scope = ANY (ARRAY['overall'::text, 'venue'::text, 'opposition'::text])))
);

-- Name: feature_raw_stats_snapshots_id_seq; Type: SEQUENCE; Schema: public

CREATE SEQUENCE public.feature_raw_stats_snapshots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: feature_raw_stats_snapshots_id_seq; Type: SEQUENCE OWNED BY; Schema: public

ALTER SEQUENCE public.feature_raw_stats_snapshots_id_seq OWNED BY public.feature_raw_stats_snapshots.id;

-- Name: fielding_data; Type: TABLE; Schema: public

CREATE TABLE public.fielding_data (
    id bigint NOT NULL,
    match_id bigint NOT NULL,
    player_id bigint NOT NULL,
    catches integer,
    run_outs integer,
    dropped_catches integer,
    missed_run_outs integer,
    stumpings integer DEFAULT 0 NOT NULL,
    runouts_direct_hits integer DEFAULT 0 NOT NULL,
    inning_number smallint DEFAULT 1 NOT NULL
);

-- Name: fielding_data_id_seq; Type: SEQUENCE; Schema: public

CREATE SEQUENCE public.fielding_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: fielding_data_id_seq; Type: SEQUENCE OWNED BY; Schema: public

ALTER SEQUENCE public.fielding_data_id_seq OWNED BY public.fielding_data.id;

-- Name: fielding_event; Type: TABLE; Schema: public

CREATE TABLE public.fielding_event (
    id bigint NOT NULL,
    match_id bigint NOT NULL,
    innings smallint NOT NULL,
    over smallint NOT NULL,
    ball smallint NOT NULL,
    batter_out_id bigint,
    fielder_id bigint,
    bowler_id bigint,
    kind text NOT NULL,
    assist_role text DEFAULT ''::text NOT NULL,
    is_direct_hit boolean DEFAULT false NOT NULL,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT fielding_event_kind_check CHECK ((kind = ANY (ARRAY['caught'::text, 'run_out'::text, 'stumped'::text, 'other'::text])))
);

-- Name: fielding_event_id_seq; Type: SEQUENCE; Schema: public

CREATE SEQUENCE public.fielding_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: fielding_event_id_seq; Type: SEQUENCE OWNED BY; Schema: public

ALTER SEQUENCE public.fielding_event_id_seq OWNED BY public.fielding_event.id;

-- Name: match; Type: TABLE; Schema: public

CREATE TABLE public.match (
    match_id bigint NOT NULL,
    format_id bigint NOT NULL,
    match_date date NOT NULL,
    original_match_type character varying(100) NOT NULL,
    venue_id bigint,
    season_id bigint,
    toss_winner_opposition_id bigint,
    toss_decision character varying(16),
    outcome_winner_opposition_id bigint,
    outcome_by_runs integer,
    outcome_by_wickets integer,
    event_name character varying(255),
    match_number integer,
    gender character varying(16),
    balls_per_over smallint DEFAULT 6 NOT NULL,
    scheduled_overs_per_innings integer
);

-- Name: match_format; Type: TABLE; Schema: public

CREATE TABLE public.match_format (
    id bigint NOT NULL,
    code character varying(16) NOT NULL,
    name character varying(100) NOT NULL
);

-- Name: match_format_id_seq; Type: SEQUENCE; Schema: public

CREATE SEQUENCE public.match_format_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: match_format_id_seq; Type: SEQUENCE OWNED BY; Schema: public

ALTER SEQUENCE public.match_format_id_seq OWNED BY public.match_format.id;

-- Name: match_inning; Type: TABLE; Schema: public

CREATE TABLE public.match_inning (
    match_id bigint NOT NULL,
    inning_number smallint NOT NULL,
    batting_team_opposition_id bigint NOT NULL,
    bowling_team_opposition_id bigint NOT NULL,
    runs_scored integer DEFAULT 0 NOT NULL,
    wickets_lost integer DEFAULT 0 NOT NULL,
    overs_bowled real DEFAULT 0 NOT NULL,
    balls_bowled integer DEFAULT 0 NOT NULL,
    run_rate real,
    target_runs integer,
    extras integer DEFAULT 0 NOT NULL,
    winner_opposition_id bigint
);

-- Name: match_prediction_aggregates; Type: TABLE; Schema: public

CREATE TABLE public.match_prediction_aggregates (
    match_id bigint NOT NULL,
    format text NOT NULL,
    team1_code text NOT NULL,
    team2_code text NOT NULL,
    predicted_winner_code text,
    predicted_total_runs double precision,
    model_version text,
    cutoff_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: ml_tuned_params; Type: TABLE; Schema: public

CREATE TABLE public.ml_tuned_params (
    id integer NOT NULL,
    model character varying(64) NOT NULL,
    format character varying(32) DEFAULT ''::character varying NOT NULL,
    params jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    metrics jsonb,
    data_migration_id integer
);

-- Name: ml_tuned_params_id_seq; Type: SEQUENCE; Schema: public

CREATE SEQUENCE public.ml_tuned_params_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: ml_tuned_params_id_seq; Type: SEQUENCE OWNED BY; Schema: public

ALTER SEQUENCE public.ml_tuned_params_id_seq OWNED BY public.ml_tuned_params.id;

-- Name: opposition; Type: TABLE; Schema: public

CREATE TABLE public.opposition (
    id bigint NOT NULL,
    opposition_name character varying(100) NOT NULL
);

-- Name: opposition_id_seq; Type: SEQUENCE; Schema: public

CREATE SEQUENCE public.opposition_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: opposition_id_seq; Type: SEQUENCE OWNED BY; Schema: public

ALTER SEQUENCE public.opposition_id_seq OWNED BY public.opposition.id;

-- Name: over_boundary_wicket_features; Type: TABLE; Schema: public

CREATE TABLE public.over_boundary_wicket_features (
    as_of_date date NOT NULL,
    format_id integer NOT NULL,
    scope text DEFAULT 'overall'::text NOT NULL,
    scope_id integer,
    scope_id0 integer GENERATED ALWAYS AS (COALESCE(scope_id, 0)) STORED NOT NULL,
    player_id bigint NOT NULL,
    phase text NOT NULL,
    "position" integer NOT NULL,
    balls integer DEFAULT 0 NOT NULL,
    boundaries integer DEFAULT 0 NOT NULL,
    wickets integer DEFAULT 0 NOT NULL,
    boundary_rate double precision DEFAULT 0 NOT NULL,
    wicket_rate double precision DEFAULT 0 NOT NULL
);

-- Name: over_end_pressure_features; Type: TABLE; Schema: public

CREATE TABLE public.over_end_pressure_features (
    as_of_date date NOT NULL,
    format_id integer NOT NULL,
    scope text DEFAULT 'overall'::text NOT NULL,
    scope_id integer,
    scope_id0 integer GENERATED ALWAYS AS (COALESCE(scope_id, 0)) STORED NOT NULL,
    player_id bigint NOT NULL,
    phase text NOT NULL,
    "position" integer NOT NULL,
    balls integer DEFAULT 0 NOT NULL,
    boundaries integer DEFAULT 0 NOT NULL,
    wickets integer DEFAULT 0 NOT NULL,
    boundary_rate double precision DEFAULT 0 NOT NULL,
    wicket_rate double precision DEFAULT 0 NOT NULL
);

-- Name: player; Type: TABLE; Schema: public

CREATE TABLE public.player (
    id bigint NOT NULL,
    player_name character varying(250) NOT NULL,
    is_wicket_keeper smallint DEFAULT 0,
    is_retired smallint DEFAULT 0
);

-- Name: player_id_seq; Type: SEQUENCE; Schema: public

CREATE SEQUENCE public.player_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: player_id_seq; Type: SEQUENCE OWNED BY; Schema: public

ALTER SEQUENCE public.player_id_seq OWNED BY public.player.id;

-- Name: player_window_features; Type: TABLE; Schema: public

CREATE TABLE public.player_window_features (
    as_of_date date NOT NULL,
    format_id smallint NOT NULL,
    scope character varying(32) NOT NULL,
    scope_id bigint,
    scope_id0 bigint GENERATED ALWAYS AS (COALESCE(scope_id, (0)::bigint)) STORED NOT NULL,
    player_id bigint NOT NULL,
    role character varying(8) NOT NULL,
    phase character varying(16) NOT NULL,
    horizon integer NOT NULL,
    balls integer NOT NULL,
    runs integer NOT NULL,
    dots integer DEFAULT 0 NOT NULL,
    fours integer,
    sixes integer,
    dismissals integer,
    sr real,
    boundary_rate real,
    dot_rate real,
    dismissal_hazard real,
    wickets integer,
    dot_balls integer,
    boundaries_conceded integer,
    wide_nb integer,
    econ real,
    wicket_rate real
);

-- Name: season; Type: TABLE; Schema: public

CREATE TABLE public.season (
    id bigint NOT NULL,
    season_name character varying(100) NOT NULL
);

-- Name: season_id_seq; Type: SEQUENCE; Schema: public

CREATE SEQUENCE public.season_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: season_id_seq; Type: SEQUENCE OWNED BY; Schema: public

ALTER SEQUENCE public.season_id_seq OWNED BY public.season.id;

-- Name: venue; Type: TABLE; Schema: public

CREATE TABLE public.venue (
    id bigint NOT NULL,
    venue_name character varying(100) NOT NULL,
    normalized_name text,
    display_name text,
    city text,
    country text,
    latitude double precision,
    longitude double precision,
    timezone text,
    source text DEFAULT 'open-meteo-geocoding'::text,
    confidence real,
    verified_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: venue_id_seq; Type: SEQUENCE; Schema: public

CREATE SEQUENCE public.venue_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: venue_id_seq; Type: SEQUENCE OWNED BY; Schema: public

ALTER SEQUENCE public.venue_id_seq OWNED BY public.venue.id;

-- Name: weather_data; Type: TABLE; Schema: public

CREATE TABLE public.weather_data (
    id bigint NOT NULL,
    match_id bigint NOT NULL,
    session character varying(100) NOT NULL,
    temp integer,
    feels integer,
    wind integer,
    gust integer,
    rain integer,
    humidity integer,
    cloud integer,
    pressure integer,
    viscosity character varying(100)
);

-- Name: weather_data_id_seq; Type: SEQUENCE; Schema: public

CREATE SEQUENCE public.weather_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: weather_data_id_seq; Type: SEQUENCE OWNED BY; Schema: public

ALTER SEQUENCE public.weather_data_id_seq OWNED BY public.weather_data.id;

-- Name: weather_job; Type: TABLE; Schema: public

CREATE TABLE public.weather_job (
    id bigint NOT NULL,
    match_id bigint NOT NULL,
    normalized_venue text NOT NULL,
    city text,
    country text,
    start_at_local timestamp with time zone,
    end_at_local timestamp with time zone,
    sessions jsonb DEFAULT '[]'::jsonb NOT NULL,
    status text DEFAULT 'queued'::text NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    last_error text,
    scheduled_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Name: weather_job_id_seq; Type: SEQUENCE; Schema: public

CREATE SEQUENCE public.weather_job_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Name: weather_job_id_seq; Type: SEQUENCE OWNED BY; Schema: public

ALTER SEQUENCE public.weather_job_id_seq OWNED BY public.weather_job.id;

-- Name: wicket_mode_features; Type: TABLE; Schema: public

CREATE TABLE public.wicket_mode_features (
    as_of_date date NOT NULL,
    format_id integer NOT NULL,
    scope text DEFAULT 'overall'::text NOT NULL,
    scope_id integer,
    scope_id0 integer GENERATED ALWAYS AS (COALESCE(scope_id, 0)) STORED NOT NULL,
    player_id bigint NOT NULL,
    phase text NOT NULL,
    mode text NOT NULL,
    balls integer DEFAULT 0 NOT NULL,
    wickets integer DEFAULT 0 NOT NULL,
    wickets_per_100 double precision DEFAULT 0 NOT NULL
);

-- Name: batting_data id; Type: DEFAULT; Schema: public

ALTER TABLE ONLY public.batting_data ALTER COLUMN id SET DEFAULT nextval('public.batting_data_id_seq'::regclass);

-- Name: bowling_data id; Type: DEFAULT; Schema: public

ALTER TABLE ONLY public.bowling_data ALTER COLUMN id SET DEFAULT nextval('public.bowling_data_id_seq'::regclass);

-- Name: data_migrations id; Type: DEFAULT; Schema: public

ALTER TABLE ONLY public.data_migrations ALTER COLUMN id SET DEFAULT nextval('public.data_migrations_id_seq'::regclass);

-- Name: feature_raw_stats_snapshots id; Type: DEFAULT; Schema: public

ALTER TABLE ONLY public.feature_raw_stats_snapshots ALTER COLUMN id SET DEFAULT nextval('public.feature_raw_stats_snapshots_id_seq'::regclass);

-- Name: fielding_data id; Type: DEFAULT; Schema: public

ALTER TABLE ONLY public.fielding_data ALTER COLUMN id SET DEFAULT nextval('public.fielding_data_id_seq'::regclass);

-- Name: fielding_event id; Type: DEFAULT; Schema: public

ALTER TABLE ONLY public.fielding_event ALTER COLUMN id SET DEFAULT nextval('public.fielding_event_id_seq'::regclass);

-- Name: match_format id; Type: DEFAULT; Schema: public

ALTER TABLE ONLY public.match_format ALTER COLUMN id SET DEFAULT nextval('public.match_format_id_seq'::regclass);

-- Name: ml_tuned_params id; Type: DEFAULT; Schema: public

ALTER TABLE ONLY public.ml_tuned_params ALTER COLUMN id SET DEFAULT nextval('public.ml_tuned_params_id_seq'::regclass);

-- Name: opposition id; Type: DEFAULT; Schema: public

ALTER TABLE ONLY public.opposition ALTER COLUMN id SET DEFAULT nextval('public.opposition_id_seq'::regclass);

-- Name: player id; Type: DEFAULT; Schema: public

ALTER TABLE ONLY public.player ALTER COLUMN id SET DEFAULT nextval('public.player_id_seq'::regclass);

-- Name: season id; Type: DEFAULT; Schema: public

ALTER TABLE ONLY public.season ALTER COLUMN id SET DEFAULT nextval('public.season_id_seq'::regclass);

-- Name: venue id; Type: DEFAULT; Schema: public

ALTER TABLE ONLY public.venue ALTER COLUMN id SET DEFAULT nextval('public.venue_id_seq'::regclass);

-- Name: weather_data id; Type: DEFAULT; Schema: public

ALTER TABLE ONLY public.weather_data ALTER COLUMN id SET DEFAULT nextval('public.weather_data_id_seq'::regclass);

-- Name: weather_job id; Type: DEFAULT; Schema: public

ALTER TABLE ONLY public.weather_job ALTER COLUMN id SET DEFAULT nextval('public.weather_job_id_seq'::regclass);

-- Name: ball_event ball_event_pkey; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.ball_event
    ADD CONSTRAINT ball_event_pkey PRIMARY KEY (match_id, innings, over, ball);

-- Name: batting_data batting_data_pkey; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.batting_data
    ADD CONSTRAINT batting_data_pkey PRIMARY KEY (id);

-- Name: batting_transition_features batting_transition_features_pkey; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.batting_transition_features
    ADD CONSTRAINT batting_transition_features_pkey PRIMARY KEY (as_of_date, format_id, scope, scope_id, prev_batter_id, batter_id, phase);

-- Name: bowling_data bowling_data_pkey; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.bowling_data
    ADD CONSTRAINT bowling_data_pkey PRIMARY KEY (id);

-- Name: bowling_sequence_features bowling_sequence_features_pkey; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.bowling_sequence_features
    ADD CONSTRAINT bowling_sequence_features_pkey PRIMARY KEY (as_of_date, format_id, scope, scope_id0, prev_bowler_id, bowler_id, phase);

-- Name: bowling_spell_features bowling_spell_features_pkey; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.bowling_spell_features
    ADD CONSTRAINT bowling_spell_features_pkey PRIMARY KEY (as_of_date, format_id, scope, scope_id0, player_id, phase);

-- Name: data_migrations data_migrations_pkey; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.data_migrations
    ADD CONSTRAINT data_migrations_pkey PRIMARY KEY (id);

-- Name: dot_streak_features dot_streak_features_pkey; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.dot_streak_features
    ADD CONSTRAINT dot_streak_features_pkey PRIMARY KEY (as_of_date, format_id, scope, scope_id, player_id, role, k, phase);

-- Name: event_reaction_features event_reaction_features_pkey; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.event_reaction_features
    ADD CONSTRAINT event_reaction_features_pkey PRIMARY KEY (as_of_date, format_id, scope, scope_id, player_id, role, prev_event, phase);

-- Name: extras_discipline_features extras_discipline_features_pkey; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.extras_discipline_features
    ADD CONSTRAINT extras_discipline_features_pkey PRIMARY KEY (as_of_date, format_id, scope, scope_id0, player_id, phase);

-- Name: feature_raw_stats_snapshots feature_raw_stats_snapshots_pkey; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.feature_raw_stats_snapshots
    ADD CONSTRAINT feature_raw_stats_snapshots_pkey PRIMARY KEY (id);

-- Name: feature_raw_stats_snapshots feature_raw_stats_snapshots_player_id_as_of_date_format_id__key; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.feature_raw_stats_snapshots
    ADD CONSTRAINT feature_raw_stats_snapshots_player_id_as_of_date_format_id__key UNIQUE (player_id, as_of_date, format_id, scope, scope_id);

-- Name: fielding_data fielding_data_match_id_inning_number_player_id_key; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.fielding_data
    ADD CONSTRAINT fielding_data_match_id_inning_number_player_id_key UNIQUE (match_id, inning_number, player_id);

-- Name: fielding_data fielding_data_pkey; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.fielding_data
    ADD CONSTRAINT fielding_data_pkey PRIMARY KEY (id);

-- Name: fielding_event fielding_event_pkey; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.fielding_event
    ADD CONSTRAINT fielding_event_pkey PRIMARY KEY (id);

-- Name: match_format match_format_code_key; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.match_format
    ADD CONSTRAINT match_format_code_key UNIQUE (code);

-- Name: match_format match_format_pkey; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.match_format
    ADD CONSTRAINT match_format_pkey PRIMARY KEY (id);

-- Name: match_inning match_inning_pkey; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.match_inning
    ADD CONSTRAINT match_inning_pkey PRIMARY KEY (match_id, inning_number);

-- Name: match match_pkey; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.match
    ADD CONSTRAINT match_pkey PRIMARY KEY (match_id);

-- Name: match_prediction_aggregates match_prediction_aggregates_pkey; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.match_prediction_aggregates
    ADD CONSTRAINT match_prediction_aggregates_pkey PRIMARY KEY (match_id);

-- Name: ml_tuned_params ml_tuned_params_pkey; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.ml_tuned_params
    ADD CONSTRAINT ml_tuned_params_pkey PRIMARY KEY (id);

-- Name: opposition opposition_opposition_name_key; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.opposition
    ADD CONSTRAINT opposition_opposition_name_key UNIQUE (opposition_name);

-- Name: opposition opposition_pkey; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.opposition
    ADD CONSTRAINT opposition_pkey PRIMARY KEY (id);

-- Name: over_boundary_wicket_features over_boundary_wicket_features_pkey; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.over_boundary_wicket_features
    ADD CONSTRAINT over_boundary_wicket_features_pkey PRIMARY KEY (as_of_date, format_id, scope, scope_id0, player_id, phase, "position");

-- Name: over_end_pressure_features over_end_pressure_features_pkey; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.over_end_pressure_features
    ADD CONSTRAINT over_end_pressure_features_pkey PRIMARY KEY (as_of_date, format_id, scope, scope_id0, player_id, phase, "position");

-- Name: player player_pkey; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.player
    ADD CONSTRAINT player_pkey PRIMARY KEY (id);

-- Name: player player_player_name_key; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.player
    ADD CONSTRAINT player_player_name_key UNIQUE (player_name);

-- Name: player_window_features player_window_features_pkey; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.player_window_features
    ADD CONSTRAINT player_window_features_pkey PRIMARY KEY (as_of_date, format_id, scope, scope_id0, player_id, role, phase, horizon);

-- Name: season season_pkey; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.season
    ADD CONSTRAINT season_pkey PRIMARY KEY (id);

-- Name: season season_season_name_key; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.season
    ADD CONSTRAINT season_season_name_key UNIQUE (season_name);

-- Name: batting_data uq_batting_match_inning_player; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.batting_data
    ADD CONSTRAINT uq_batting_match_inning_player UNIQUE (match_id, inning_number, player_id);

-- Name: bowling_data uq_bowling_match_inning_player; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.bowling_data
    ADD CONSTRAINT uq_bowling_match_inning_player UNIQUE (match_id, inning_number, player_id);

-- Name: weather_data uq_weather_match_session; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.weather_data
    ADD CONSTRAINT uq_weather_match_session UNIQUE (match_id, session);

-- Name: venue venue_pkey; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.venue
    ADD CONSTRAINT venue_pkey PRIMARY KEY (id);

-- Name: venue venue_venue_name_key; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.venue
    ADD CONSTRAINT venue_venue_name_key UNIQUE (venue_name);

-- Name: weather_data weather_data_match_id_session_key; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.weather_data
    ADD CONSTRAINT weather_data_match_id_session_key UNIQUE (match_id, session);

-- Name: weather_data weather_data_pkey; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.weather_data
    ADD CONSTRAINT weather_data_pkey PRIMARY KEY (id);

-- Name: weather_job weather_job_match_id_key; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.weather_job
    ADD CONSTRAINT weather_job_match_id_key UNIQUE (match_id);

-- Name: weather_job weather_job_pkey; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.weather_job
    ADD CONSTRAINT weather_job_pkey PRIMARY KEY (id);

-- Name: wicket_mode_features wicket_mode_features_pkey; Type: CONSTRAINT; Schema: public

ALTER TABLE ONLY public.wicket_mode_features
    ADD CONSTRAINT wicket_mode_features_pkey PRIMARY KEY (as_of_date, format_id, scope, scope_id0, player_id, phase, mode);

-- Name: idx_ball_event_bowler_seq; Type: INDEX; Schema: public

CREATE INDEX idx_ball_event_bowler_seq ON public.ball_event USING btree (bowler_id, match_id, innings, ball_seq) WHERE (bowler_id IS NOT NULL);

-- Name: idx_ball_event_match_innings_seq; Type: INDEX; Schema: public

CREATE INDEX idx_ball_event_match_innings_seq ON public.ball_event USING btree (match_id, innings, ball_seq);

-- Name: idx_ball_event_phase; Type: INDEX; Schema: public

CREATE INDEX idx_ball_event_phase ON public.ball_event USING btree (phase);

-- Name: idx_ball_event_striker_seq; Type: INDEX; Schema: public

CREATE INDEX idx_ball_event_striker_seq ON public.ball_event USING btree (striker_id, match_id, innings, ball_seq) WHERE (striker_id IS NOT NULL);

-- Name: idx_bat_trans_latest; Type: INDEX; Schema: public

CREATE INDEX idx_bat_trans_latest ON public.batting_transition_features USING btree (batter_id, format_id, as_of_date DESC) INCLUDE (prev_batter_id, phase, balls, runs, strike_rate) WHERE (((scope)::text = 'overall'::text) AND (scope_id = 0));

-- Name: idx_batting_data_match_inning; Type: INDEX; Schema: public

CREATE INDEX idx_batting_data_match_inning ON public.batting_data USING btree (match_id, inning_number);

-- Name: idx_batting_match; Type: INDEX; Schema: public

CREATE INDEX idx_batting_match ON public.batting_data USING btree (match_id);

-- Name: idx_batting_player; Type: INDEX; Schema: public

CREATE INDEX idx_batting_player ON public.batting_data USING btree (player_id);

-- Name: idx_bowl_seq_latest; Type: INDEX; Schema: public

CREATE INDEX idx_bowl_seq_latest ON public.bowling_sequence_features USING btree (bowler_id, format_id, as_of_date DESC) INCLUDE (prev_bowler_id, phase, overs_pairs, balls, runs, wickets, dot_balls) WHERE (((scope)::text = 'overall'::text) AND (scope_id IS NULL));

-- Name: idx_bowling_data_match_inning; Type: INDEX; Schema: public

CREATE INDEX idx_bowling_data_match_inning ON public.bowling_data USING btree (match_id, inning_number);

-- Name: idx_bowling_match; Type: INDEX; Schema: public

CREATE INDEX idx_bowling_match ON public.bowling_data USING btree (match_id);

-- Name: idx_bowling_player; Type: INDEX; Schema: public

CREATE INDEX idx_bowling_player ON public.bowling_data USING btree (player_id);

-- Name: idx_bowling_spell_latest; Type: INDEX; Schema: public

CREATE INDEX idx_bowling_spell_latest ON public.bowling_spell_features USING btree (player_id, format_id, scope, scope_id0, phase, as_of_date DESC);

-- Name: idx_data_migrations_command; Type: INDEX; Schema: public

CREATE INDEX idx_data_migrations_command ON public.data_migrations USING btree (command);

-- Name: idx_data_migrations_started_at; Type: INDEX; Schema: public

CREATE INDEX idx_data_migrations_started_at ON public.data_migrations USING btree (started_at DESC);

-- Name: idx_data_migrations_status; Type: INDEX; Schema: public

CREATE INDEX idx_data_migrations_status ON public.data_migrations USING btree (status);

-- Name: idx_dot_streak_latest; Type: INDEX; Schema: public

CREATE INDEX idx_dot_streak_latest ON public.dot_streak_features USING btree (player_id, role, format_id, as_of_date DESC) INCLUDE (k, phase, balls, runs_next_total) WHERE (((scope)::text = 'overall'::text) AND (scope_id = 0));

-- Name: idx_event_reaction_latest; Type: INDEX; Schema: public

CREATE INDEX idx_event_reaction_latest ON public.event_reaction_features USING btree (player_id, role, format_id, as_of_date DESC) INCLUDE (prev_event, phase, balls, runs) WHERE (((scope)::text = 'overall'::text) AND (scope_id = 0));

-- Name: idx_extras_disc_latest; Type: INDEX; Schema: public

CREATE INDEX idx_extras_disc_latest ON public.extras_discipline_features USING btree (player_id, format_id, scope, scope_id0, phase, as_of_date DESC);

-- Name: idx_feature_raw_stats_player_fmt_date; Type: INDEX; Schema: public

CREATE INDEX idx_feature_raw_stats_player_fmt_date ON public.feature_raw_stats_snapshots USING btree (player_id, format_id, as_of_date);

-- Name: idx_feature_raw_stats_scope; Type: INDEX; Schema: public

CREATE INDEX idx_feature_raw_stats_scope ON public.feature_raw_stats_snapshots USING btree (scope, scope_id, player_id, as_of_date);

-- Name: idx_fielding_event_match; Type: INDEX; Schema: public

CREATE INDEX idx_fielding_event_match ON public.fielding_event USING btree (match_id);

-- Name: idx_fielding_event_player; Type: INDEX; Schema: public

CREATE INDEX idx_fielding_event_player ON public.fielding_event USING btree (fielder_id);

-- Name: idx_fielding_match; Type: INDEX; Schema: public

CREATE INDEX idx_fielding_match ON public.fielding_data USING btree (match_id);

-- Name: idx_fielding_match_inning; Type: INDEX; Schema: public

CREATE INDEX idx_fielding_match_inning ON public.fielding_data USING btree (match_id, inning_number);

-- Name: idx_fielding_player; Type: INDEX; Schema: public

CREATE INDEX idx_fielding_player ON public.fielding_data USING btree (player_id);

-- Name: idx_match_format_id; Type: INDEX; Schema: public

CREATE INDEX idx_match_format_id ON public.match USING btree (format_id);

-- Name: idx_match_inning_batting_team; Type: INDEX; Schema: public

CREATE INDEX idx_match_inning_batting_team ON public.match_inning USING btree (batting_team_opposition_id);

-- Name: idx_match_inning_bowling_team; Type: INDEX; Schema: public

CREATE INDEX idx_match_inning_bowling_team ON public.match_inning USING btree (bowling_team_opposition_id);

-- Name: idx_match_inning_match_id; Type: INDEX; Schema: public

CREATE INDEX idx_match_inning_match_id ON public.match_inning USING btree (match_id);

-- Name: idx_match_match_date; Type: INDEX; Schema: public

CREATE INDEX idx_match_match_date ON public.match USING btree (match_date);

-- Name: idx_match_season_id; Type: INDEX; Schema: public

CREATE INDEX idx_match_season_id ON public.match USING btree (season_id);

-- Name: idx_match_venue_id; Type: INDEX; Schema: public

CREATE INDEX idx_match_venue_id ON public.match USING btree (venue_id);

-- Name: idx_ml_tuned_params_data_migration_id; Type: INDEX; Schema: public

CREATE INDEX idx_ml_tuned_params_data_migration_id ON public.ml_tuned_params USING btree (data_migration_id) WHERE (data_migration_id IS NOT NULL);

-- Name: idx_ml_tuned_params_model_format_created; Type: INDEX; Schema: public

CREATE INDEX idx_ml_tuned_params_model_format_created ON public.ml_tuned_params USING btree (model, format, created_at DESC);

-- Name: idx_mpa_format_date; Type: INDEX; Schema: public

CREATE INDEX idx_mpa_format_date ON public.match_prediction_aggregates USING btree (format, cutoff_at);

-- Name: idx_mpa_teams_date; Type: INDEX; Schema: public

CREATE INDEX idx_mpa_teams_date ON public.match_prediction_aggregates USING btree (team1_code, team2_code, cutoff_at);

-- Name: idx_over_end_pressure_latest; Type: INDEX; Schema: public

CREATE INDEX idx_over_end_pressure_latest ON public.over_end_pressure_features USING btree (player_id, format_id, scope, scope_id0, phase, as_of_date DESC);

-- Name: idx_overpos_latest; Type: INDEX; Schema: public

CREATE INDEX idx_overpos_latest ON public.over_boundary_wicket_features USING btree (player_id, format_id, scope, scope_id0, phase, as_of_date DESC);

-- Name: idx_player_window_features_latest; Type: INDEX; Schema: public

CREATE INDEX idx_player_window_features_latest ON public.player_window_features USING btree (player_id, role, format_id, as_of_date DESC) INCLUDE (phase, horizon, balls, runs, dots, fours, sixes, dismissals, sr, boundary_rate, dot_rate, dismissal_hazard, wickets, dot_balls, boundaries_conceded, wide_nb, econ, wicket_rate) WHERE (((scope)::text = 'overall'::text) AND (scope_id IS NULL));

-- Name: idx_weather_job_status; Type: INDEX; Schema: public

CREATE INDEX idx_weather_job_status ON public.weather_job USING btree (status, scheduled_at);

-- Name: idx_weather_job_venue; Type: INDEX; Schema: public

CREATE INDEX idx_weather_job_venue ON public.weather_job USING btree (normalized_venue);

-- Name: idx_weather_match_id; Type: INDEX; Schema: public

CREATE INDEX idx_weather_match_id ON public.weather_data USING btree (match_id);

-- Name: idx_weather_session; Type: INDEX; Schema: public

CREATE INDEX idx_weather_session ON public.weather_data USING btree (session);

-- Name: idx_wicket_mode_latest; Type: INDEX; Schema: public

CREATE INDEX idx_wicket_mode_latest ON public.wicket_mode_features USING btree (player_id, format_id, scope, scope_id0, phase, as_of_date DESC);

-- Name: uq_fielding_event_natural; Type: INDEX; Schema: public

CREATE UNIQUE INDEX uq_fielding_event_natural ON public.fielding_event USING btree (match_id, innings, over, ball, fielder_id, kind, assist_role);

-- Name: ux_venue_normalized_name; Type: INDEX; Schema: public

CREATE UNIQUE INDEX ux_venue_normalized_name ON public.venue USING btree (normalized_name);

-- Name: match_prediction_aggregates tr_mpa_set_updated_at; Type: TRIGGER; Schema: public

CREATE TRIGGER tr_mpa_set_updated_at BEFORE UPDATE ON public.match_prediction_aggregates FOR EACH ROW EXECUTE FUNCTION public.mpa_set_updated_at();

-- Name: batting_data batting_data_player_id_fkey; Type: FK CONSTRAINT; Schema: public

ALTER TABLE ONLY public.batting_data
    ADD CONSTRAINT batting_data_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.player(id);

-- Name: bowling_data bowling_data_player_id_fkey; Type: FK CONSTRAINT; Schema: public

ALTER TABLE ONLY public.bowling_data
    ADD CONSTRAINT bowling_data_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.player(id);

-- Name: feature_raw_stats_snapshots feature_raw_stats_snapshots_format_id_fkey; Type: FK CONSTRAINT; Schema: public

ALTER TABLE ONLY public.feature_raw_stats_snapshots
    ADD CONSTRAINT feature_raw_stats_snapshots_format_id_fkey FOREIGN KEY (format_id) REFERENCES public.match_format(id);

-- Name: feature_raw_stats_snapshots feature_raw_stats_snapshots_player_id_fkey; Type: FK CONSTRAINT; Schema: public

ALTER TABLE ONLY public.feature_raw_stats_snapshots
    ADD CONSTRAINT feature_raw_stats_snapshots_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.player(id);

-- Name: fielding_data fielding_data_player_id_fkey; Type: FK CONSTRAINT; Schema: public

ALTER TABLE ONLY public.fielding_data
    ADD CONSTRAINT fielding_data_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.player(id);

-- Name: fielding_event fielding_event_batter_out_id_fkey; Type: FK CONSTRAINT; Schema: public

ALTER TABLE ONLY public.fielding_event
    ADD CONSTRAINT fielding_event_batter_out_id_fkey FOREIGN KEY (batter_out_id) REFERENCES public.player(id);

-- Name: fielding_event fielding_event_bowler_id_fkey; Type: FK CONSTRAINT; Schema: public

ALTER TABLE ONLY public.fielding_event
    ADD CONSTRAINT fielding_event_bowler_id_fkey FOREIGN KEY (bowler_id) REFERENCES public.player(id);

-- Name: fielding_event fielding_event_fielder_id_fkey; Type: FK CONSTRAINT; Schema: public

ALTER TABLE ONLY public.fielding_event
    ADD CONSTRAINT fielding_event_fielder_id_fkey FOREIGN KEY (fielder_id) REFERENCES public.player(id);

-- Name: match match_format_id_fkey; Type: FK CONSTRAINT; Schema: public

ALTER TABLE ONLY public.match
    ADD CONSTRAINT match_format_id_fkey FOREIGN KEY (format_id) REFERENCES public.match_format(id);

-- Name: match_inning match_inning_batting_team_opposition_id_fkey; Type: FK CONSTRAINT; Schema: public

ALTER TABLE ONLY public.match_inning
    ADD CONSTRAINT match_inning_batting_team_opposition_id_fkey FOREIGN KEY (batting_team_opposition_id) REFERENCES public.opposition(id);

-- Name: match_inning match_inning_bowling_team_opposition_id_fkey; Type: FK CONSTRAINT; Schema: public

ALTER TABLE ONLY public.match_inning
    ADD CONSTRAINT match_inning_bowling_team_opposition_id_fkey FOREIGN KEY (bowling_team_opposition_id) REFERENCES public.opposition(id);

-- Name: match_inning match_inning_match_id_fkey; Type: FK CONSTRAINT; Schema: public

ALTER TABLE ONLY public.match_inning
    ADD CONSTRAINT match_inning_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.match(match_id) ON DELETE CASCADE;

-- Name: match_inning match_inning_winner_opposition_id_fkey; Type: FK CONSTRAINT; Schema: public

ALTER TABLE ONLY public.match_inning
    ADD CONSTRAINT match_inning_winner_opposition_id_fkey FOREIGN KEY (winner_opposition_id) REFERENCES public.opposition(id);

-- Name: match match_outcome_winner_opposition_id_fkey; Type: FK CONSTRAINT; Schema: public

ALTER TABLE ONLY public.match
    ADD CONSTRAINT match_outcome_winner_opposition_id_fkey FOREIGN KEY (outcome_winner_opposition_id) REFERENCES public.opposition(id);

-- Name: match match_season_id_fkey; Type: FK CONSTRAINT; Schema: public

ALTER TABLE ONLY public.match
    ADD CONSTRAINT match_season_id_fkey FOREIGN KEY (season_id) REFERENCES public.season(id);

-- Name: match match_toss_winner_opposition_id_fkey; Type: FK CONSTRAINT; Schema: public

ALTER TABLE ONLY public.match
    ADD CONSTRAINT match_toss_winner_opposition_id_fkey FOREIGN KEY (toss_winner_opposition_id) REFERENCES public.opposition(id);

-- Name: match match_venue_id_fkey; Type: FK CONSTRAINT; Schema: public

ALTER TABLE ONLY public.match
    ADD CONSTRAINT match_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.venue(id);

-- Name: ml_tuned_params ml_tuned_params_data_migration_id_fkey; Type: FK CONSTRAINT; Schema: public

ALTER TABLE ONLY public.ml_tuned_params
    ADD CONSTRAINT ml_tuned_params_data_migration_id_fkey FOREIGN KEY (data_migration_id) REFERENCES public.data_migrations(id);

-- Seed data
--
-- pg_dump --schema-only omits rows, but match_format is a dimension table whose ids
-- are hardcoded in go-app/internal/formats (IDTest=1, IDODI=2, IDT20=3, IDT20I=4).
-- Inserting with explicit ids keeps that contract; the sequence is then advanced past
-- them so later inserts do not collide.

INSERT INTO public.match_format (id, code, name) VALUES
    (1, 'TEST', 'Test'),
    (2, 'ODI',  'One Day International'),
    (3, 'T20',  'T20 (All)'),
    (4, 'T20I', 'T20 International')
ON CONFLICT (code) DO NOTHING;

SELECT setval('public.match_format_id_seq', (SELECT COALESCE(MAX(id), 1) FROM public.match_format), true);

COMMIT;
