-- 0015_auction.sql
--
-- The auction record (P3-1): what the operator entered while an auction ran.
--
-- Nothing in this schema held an auction. A player list that spans clubs, a price, a
-- buyer, a squad in progress -- none of it existed anywhere, and the module Phase 3
-- opens on is a function of exactly those facts. These three tables are that record.
--
-- What this is: facts the operator types in as a live auction happens. Who was listed,
-- who has been sold, to whom, for how much, and who went unsold. Every row here was
-- entered by hand, one operator, one local stack. Nothing is fetched: a live auction
-- feed is a paid or account-gated source and is not built (roadmap § 6).
--
-- What this is not:
--   * Not a prediction. `issued_prediction` (0013) holds answers this API *issued* about
--     fixtures, and P2-4 scores them once the match is imported. Nothing here is a
--     forecast of anything, so nothing here is on the track record and nothing here is
--     ever scored (roadmap § 6, clause 6).
--   * Not a cache. Migration 0007 dropped one of those and says why. No row here can be
--     recomputed from anything else in the database, because no other source of it
--     exists -- which is the whole reason for the table.
--   * Not a feed. No importer writes it, no job refreshes it, and no scheduler reads it.
--
-- Why the roles are absent from these tables. A player's role -- keeper, bowling option
-- -- is not a fact about the auction; it is what the served rating vectors say about him
-- *today*, read from ml-service through `POST /xi/player-roles` on every read of an
-- auction and stamped with the run and date it came from. Storing it here would freeze
-- one run's answer into a record that outlives the run, and the surface would then show
-- a role with no date on it. The database's `player.is_wicket_keeper` is a name-set flag
-- and is not the model's role either; where the surface shows it at all it says so.
--
-- Why the eleven's constraints live on the auction. `squad_size`, `min_bowlers` and
-- `require_keeper` are the same three the predict path takes, so "which slots are still
-- open, and by role" is answered with the objective's own constraint vocabulary rather
-- than a second one invented here.

BEGIN;

-- One auction: the format it is for, the side doing the buying, and the constraints its
-- squad is being assembled under.
CREATE TABLE IF NOT EXISTS public.auction (
    -- Generated by go-app before the insert, the way an issued prediction's is: the id
    -- names the record in every later request that changes it.
    id                    uuid        PRIMARY KEY,
    created_at            timestamptz NOT NULL DEFAULT now(),
    name                  text        NOT NULL,

    -- One of the simulator's formats (T20, T20I, ODI) -- an auction is for a competition
    -- with an innings length, because every later item projects a total. T20 first: the
    -- IPL is domestic T20 and is what this module was opened on.
    format_code           text        NOT NULL,

    -- The buyer: the side whose squad this auction is filling, as an opposition id. Other
    -- franchises are recorded per sold player by name (see auction_player), because they
    -- are facts the operator observes and not sides this record is keeping a squad for.
    buyer_opposition_id   bigint      NOT NULL REFERENCES public.opposition (id),

    -- The eleven's constraints, which are the auction's: the same `min_bowlers` and
    -- `require_keeper` the predict path takes, plus the squad the operator is filling.
    squad_size            integer     NOT NULL,
    min_bowlers           integer     NOT NULL,
    require_keeper        boolean     NOT NULL
);

COMMENT ON TABLE public.auction IS
    'One auction as the operator entered it (P3-1): its format, the buying side, and the squad constraints. Not a prediction, not a cache, not a feed';
COMMENT ON COLUMN public.auction.buyer_opposition_id IS
    'The side this auction fills a squad for; a sold row naming this id is in the squad';

-- The grounds the auction is for, as venue ids. A child table rather than an array so the
-- reference to `venue` is a real one: a ground that is not in the database cannot be named
-- here, and a projection at a ground nobody can resolve is the silent substitution §8.7
-- forbids.
CREATE TABLE IF NOT EXISTS public.auction_venue (
    auction_id  uuid   NOT NULL REFERENCES public.auction (id) ON DELETE CASCADE,
    venue_id    bigint NOT NULL REFERENCES public.venue (id),
    PRIMARY KEY (auction_id, venue_id)
);

COMMENT ON TABLE public.auction_venue IS
    'The grounds one auction is for, as venue ids (P3-1)';

-- One listed player and where he currently stands.
CREATE TABLE IF NOT EXISTS public.auction_player (
    auction_id        uuid        NOT NULL REFERENCES public.auction (id) ON DELETE CASCADE,
    player_id         bigint      NOT NULL REFERENCES public.player (id),

    -- 'available', 'sold' or 'unsold' -- go-app's auction vocabulary, declared in
    -- contracts/ops-console.contract.json and asserted from every side (H-24). An undo
    -- puts a player back to 'available' and clears the buyer and the price with him,
    -- because the operator mistyped and the record must not keep half of a sale that did
    -- not happen.
    state             text        NOT NULL,

    -- The buyer, on a sold row only. `buyer_name` is what the operator typed and is
    -- always present on a sale; `buyer_opposition_id` is set where the buyer is a side
    -- this database knows, and is how the auction's own squad is found.
    buyer_name        text,
    buyer_opposition_id bigint    REFERENCES public.opposition (id),

    -- The price, in the auction's own unit. An integer because that is what an operator
    -- types at an auction -- a bid is a whole number of whatever the room is counting in
    -- -- and the unit is the room's, not this system's, so no currency is implied.
    price             bigint,

    listed_at         timestamptz NOT NULL DEFAULT now(),
    -- When the state last changed. It is the order the surface reads recent activity in,
    -- and it is what an undo moves.
    state_changed_at  timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (auction_id, player_id),

    -- A sale carries a buyer and a price; anything else carries neither. The record is
    -- entered by hand, so the one thing the database can do about a typo is refuse the
    -- shapes that are not states of an auction at all.
    CONSTRAINT auction_player_state_is_known
        CHECK (state IN ('available', 'sold', 'unsold')),
    CONSTRAINT auction_player_sale_is_whole
        CHECK (
            (state = 'sold' AND buyer_name IS NOT NULL AND price IS NOT NULL)
            OR (state <> 'sold' AND buyer_name IS NULL AND buyer_opposition_id IS NULL AND price IS NULL)
        ),
    CONSTRAINT auction_player_price_is_not_negative
        CHECK (price IS NULL OR price >= 0)
);

COMMENT ON TABLE public.auction_player IS
    'One player on one auction list, with the state the operator last recorded for him (P3-1)';
COMMENT ON COLUMN public.auction_player.price IS
    'What the buyer paid, in the auction room''s own unit; no currency is implied';

-- An auction is read whole, so the list is fetched by auction id every time.
CREATE INDEX IF NOT EXISTS auction_player_auction_idx
    ON public.auction_player (auction_id);

-- The auction listing reads newest first.
CREATE INDEX IF NOT EXISTS auction_created_at_idx
    ON public.auction (created_at DESC);

COMMIT;
