// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/umayangag/cric-info-scrapers/go-app/internal/models"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// UpsertWeather provides a mock function for the type MockRepository
func (_mock *MockRepository) UpsertWeather(ctx context.Context, r models.WeatherData) error {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for UpsertWeather")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.WeatherData) error); ok {
		r0 = returnFunc(ctx, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpsertWeather_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertWeather'
type MockRepository_UpsertWeather_Call struct {
	*mock.Call
}

// UpsertWeather is a helper method to define mock.On call
//   - ctx context.Context
//   - r models.WeatherData
func (_e *MockRepository_Expecter) UpsertWeather(ctx interface{}, r interface{}) *MockRepository_UpsertWeather_Call {
	return &MockRepository_UpsertWeather_Call{Call: _e.mock.On("UpsertWeather", ctx, r)}
}

func (_c *MockRepository_UpsertWeather_Call) Run(run func(ctx context.Context, r models.WeatherData)) *MockRepository_UpsertWeather_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.WeatherData
		if args[1] != nil {
			arg1 = args[1].(models.WeatherData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UpsertWeather_Call) Return(err error) *MockRepository_UpsertWeather_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpsertWeather_Call) RunAndReturn(run func(ctx context.Context, r models.WeatherData) error) *MockRepository_UpsertWeather_Call {
	_c.Call.Return(run)
	return _c
}
