// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSource creates a new instance of MockSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSource {
	mock := &MockSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSource is an autogenerated mock type for the Source type
type MockSource struct {
	mock.Mock
}

type MockSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSource) EXPECT() *MockSource_Expecter {
	return &MockSource_Expecter{mock: &_m.Mock}
}

// Next provides a mock function for the type MockSource
func (_mock *MockSource) Next(ctx context.Context, batch int) ([]int64, bool, error) {
	ret := _mock.Called(ctx, batch)

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 []int64
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]int64, bool, error)); ok {
		return returnFunc(ctx, batch)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []int64); ok {
		r0 = returnFunc(ctx, batch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) bool); ok {
		r1 = returnFunc(ctx, batch)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = returnFunc(ctx, batch)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSource_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type MockSource_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
//   - ctx context.Context
//   - batch int
func (_e *MockSource_Expecter) Next(ctx interface{}, batch interface{}) *MockSource_Next_Call {
	return &MockSource_Next_Call{Call: _e.mock.On("Next", ctx, batch)}
}

func (_c *MockSource_Next_Call) Run(run func(ctx context.Context, batch int)) *MockSource_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSource_Next_Call) Return(ids []int64, ok bool, err error) *MockSource_Next_Call {
	_c.Call.Return(ids, ok, err)
	return _c
}

func (_c *MockSource_Next_Call) RunAndReturn(run func(ctx context.Context, batch int) ([]int64, bool, error)) *MockSource_Next_Call {
	_c.Call.Return(run)
	return _c
}
