package exportqueries

// Column orders for every dataset export.
//
// These live here rather than inline in the query functions so they can be asserted
// against the shared contract without a database -- see export_headers_test.go. Each
// list must stay in lockstep with the SELECT order of its query: the rows are read
// with scanx.ScanToStrings(rows, len(headers)), so a count mismatch fails at scan
// time, but a same-count reordering would silently shift columns.

// BattingInferenceHeaders is the column order of the batting inference export (batting_infer_<FMT>.csv).
func BattingInferenceHeaders() []string {
	return []string{
		"batting_mean_w3",
		"batting_mean_w5",
		"batting_mean_w10",
		"batting_mean_w20",
		"batting_std_w5",
		"batting_std_w10",
		"batting_max_w10",
		"batting_min_w10",
		"batting_median_w10",
		"batting_last_1",
		"batting_last_2",
		"batting_last_3",
		"batting_career_mean",
		"batting_career_count",
		"batting_pct_zero_w10",
		"batting_trend_w5",
		"batting_days_since_last",
		"batting_innings_in_last_90d",
		"batting_temp",
		"batting_wind",
		"batting_rain",
		"batting_humidity",
		"batting_cloud",
		"batting_pressure",
		"batting_viscosity",
		"batting_inning",
		"batting_session",
		"toss",
		"venue",
		"opposition",
		"player_name",
		"catches",
		"run_outs",
		"stumpings",
		"runouts_direct_hits",
		"fielding_involvements",
	}
}

// BattingFormatHeaders is the column order of the per-format batting training export (batting_encoded_<FMT>.csv).
func BattingFormatHeaders() []string {
	return []string{
		"runs",
		"balls",
		"fours",
		"sixes",
		"batting_position",
		"batting_mean_w3",
		"batting_mean_w5",
		"batting_mean_w10",
		"batting_mean_w20",
		"batting_std_w5",
		"batting_std_w10",
		"batting_max_w10",
		"batting_min_w10",
		"batting_median_w10",
		"batting_last_1",
		"batting_last_2",
		"batting_last_3",
		"batting_career_mean",
		"batting_career_count",
		"batting_pct_zero_w10",
		"batting_trend_w5",
		"batting_days_since_last",
		"batting_innings_in_last_90d",
		"temp",
		"wind",
		"rain",
		"humidity",
		"cloud",
		"pressure",
		"viscosity",
		"inning",
		"batting_session",
		"toss",
		"batting_venue",
		"batting_opposition",
		"player_name",
		"catches",
		"run_outs",
		"stumpings",
		"runouts_direct_hits",
		"fielding_involvements",
	}
}

// BattingTrainingHeaders is the column order of the cross-format batting training export (batting_encoded_all.csv).
func BattingTrainingHeaders() []string {
	return []string{
		"runs",
		"innings_runs",
		"balls",
		"fours",
		"sixes",
		"batting_position",
		"batting_mean_w3",
		"batting_mean_w5",
		"batting_mean_w10",
		"batting_mean_w20",
		"batting_std_w5",
		"batting_std_w10",
		"batting_max_w10",
		"batting_min_w10",
		"batting_median_w10",
		"batting_last_1",
		"batting_last_2",
		"batting_last_3",
		"batting_career_mean",
		"batting_career_count",
		"batting_pct_zero_w10",
		"batting_trend_w5",
		"batting_days_since_last",
		"batting_innings_in_last_90d",
		"temp",
		"wind",
		"rain",
		"humidity",
		"cloud",
		"pressure",
		"viscosity",
		"inning",
		"batting_session",
		"toss",
		"batting_venue",
		"batting_opposition",
		"player_name",
		"catches",
		"run_outs",
		"stumpings",
		"runouts_direct_hits",
		"fielding_involvements",
		"match_date",
	}
}

// BowlingInferenceHeaders is the column order of the bowling inference export (bowling_infer_<FMT>.csv).
func BowlingInferenceHeaders() []string {
	return []string{
		"bowling_mean_w3",
		"bowling_mean_w5",
		"bowling_mean_w10",
		"bowling_mean_w20",
		"bowling_std_w5",
		"bowling_std_w10",
		"bowling_max_w10",
		"bowling_min_w10",
		"bowling_median_w10",
		"bowling_last_1",
		"bowling_last_2",
		"bowling_last_3",
		"bowling_career_mean",
		"bowling_career_count",
		"bowling_pct_zero_w10",
		"bowling_trend_w5",
		"bowling_days_since_last",
		"bowling_innings_in_last_90d",
		"bowling_temp",
		"bowling_wind",
		"bowling_rain",
		"bowling_humidity",
		"bowling_cloud",
		"bowling_pressure",
		"bowling_viscosity",
		"batting_inning",
		"bowling_session",
		"toss",
		"bowling_venue",
		"bowling_opposition",
		"player_name",
		"catches",
		"run_outs",
		"stumpings",
		"runouts_direct_hits",
		"fielding_involvements",
	}
}

// BowlingFormatHeaders is the column order of the per-format bowling training export (bowling_encoded_<FMT>.csv).
func BowlingFormatHeaders() []string {
	return []string{
		"runs",
		"balls",
		"wickets",
		"bowling_mean_w3",
		"bowling_mean_w5",
		"bowling_mean_w10",
		"bowling_mean_w20",
		"bowling_std_w5",
		"bowling_std_w10",
		"bowling_max_w10",
		"bowling_min_w10",
		"bowling_median_w10",
		"bowling_last_1",
		"bowling_last_2",
		"bowling_last_3",
		"bowling_career_mean",
		"bowling_career_count",
		"bowling_pct_zero_w10",
		"bowling_trend_w5",
		"bowling_days_since_last",
		"bowling_innings_in_last_90d",
		"temp",
		"wind",
		"rain",
		"humidity",
		"cloud",
		"pressure",
		"viscosity",
		"inning",
		"bowling_session",
		"toss",
		"bowling_venue",
		"bowling_opposition",
		"player_name",
		"catches",
		"run_outs",
		"stumpings",
		"runouts_direct_hits",
		"fielding_involvements",
		"format_code",
	}
}

// BowlingTrainingHeaders is the column order of the cross-format bowling training export (bowling_encoded_all.csv).
func BowlingTrainingHeaders() []string {
	return []string{
		"runs",
		"balls",
		"wickets",
		"innings_runs",
		"innings_wickets",
		"bowling_mean_w3",
		"bowling_mean_w5",
		"bowling_mean_w10",
		"bowling_mean_w20",
		"bowling_std_w5",
		"bowling_std_w10",
		"bowling_max_w10",
		"bowling_min_w10",
		"bowling_median_w10",
		"bowling_last_1",
		"bowling_last_2",
		"bowling_last_3",
		"bowling_career_mean",
		"bowling_career_count",
		"bowling_pct_zero_w10",
		"bowling_trend_w5",
		"bowling_days_since_last",
		"bowling_innings_in_last_90d",
		"temp",
		"wind",
		"rain",
		"humidity",
		"cloud",
		"pressure",
		"viscosity",
		"inning",
		"bowling_session",
		"toss",
		"bowling_venue",
		"bowling_opposition",
		"player_name",
		"catches",
		"run_outs",
		"stumpings",
		"runouts_direct_hits",
		"fielding_involvements",
		"format_code",
		"match_date",
	}
}

// ExtrasTrainingHeaders is the column order of the extras training export (extras_encoded_all.csv).
func ExtrasTrainingHeaders() []string {
	return []string{
		"match_id",
		"venue_id",
		"total_extras",
		"format_code",
		"match_date",
		"temp",
		"wind",
		"rain",
		"humidity",
		"cloud",
		"pressure",
		"viscosity",
		"bat_consistency_sum",
		"bowl_consistency_sum",
		"bat_form_sum",
		"bowl_form_sum",
	}
}

// InningsTrainingHeaders is the column order of the innings training export (innings_encoded_all.csv).
func InningsTrainingHeaders() []string {
	return []string{
		"match_id",
		"inning_number",
		"innings_runs",
		"innings_wickets",
		"venue_id",
		"opposition_id",
		"format_code",
		"match_date",
		"temp",
		"wind",
		"rain",
		"humidity",
		"cloud",
		"pressure",
		"viscosity",
		"bat_consistency_sum",
		"bowl_consistency_sum",
		"bat_form_sum",
		"bowl_form_sum",
	}
}

// FieldingTrainingHeaders is the column order of the fielding training export (fielding_encoded_all.csv).
func FieldingTrainingHeaders() []string {
	return []string{
		"catches",
		"run_outs",
		"stumpings",
		"fielding_consistency",
		"fielding_form",
		"temp",
		"wind",
		"rain",
		"humidity",
		"cloud",
		"pressure",
		"viscosity",
		"inning",
		"toss",
		"fielding_venue",
		"fielding_opposition",
		"player_name",
		"format_code",
		"match_date",
	}
}

// FieldingHoldoutHeaders is the column order of the fielding holdout export.
func FieldingHoldoutHeaders() []string {
	return []string{
		"catches",
		"run_outs",
		"stumpings",
		"fielding_consistency",
		"fielding_form",
		"temp",
		"wind",
		"rain",
		"humidity",
		"cloud",
		"pressure",
		"viscosity",
		"inning",
		"toss",
		"fielding_venue",
		"fielding_opposition",
		"player_name",
		"format_code",
		"match_date",
	}
}
