// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/umayangag/cric-flow/go-app/internal/predictor"
)

// NewMockPredictor creates a new instance of MockPredictor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPredictor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPredictor {
	mock := &MockPredictor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPredictor is an autogenerated mock type for the Predictor type
type MockPredictor struct {
	mock.Mock
}

type MockPredictor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPredictor) EXPECT() *MockPredictor_Expecter {
	return &MockPredictor_Expecter{mock: &_m.Mock}
}

// PredictWin provides a mock function for the type MockPredictor
func (_mock *MockPredictor) PredictWin(ctx context.Context, players []predictor.PlayerPrediction) ([]predictor.PlayerPrediction, error) {
	ret := _mock.Called(ctx, players)

	if len(ret) == 0 {
		panic("no return value specified for PredictWin")
	}

	var r0 []predictor.PlayerPrediction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []predictor.PlayerPrediction) ([]predictor.PlayerPrediction, error)); ok {
		return returnFunc(ctx, players)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []predictor.PlayerPrediction) []predictor.PlayerPrediction); ok {
		r0 = returnFunc(ctx, players)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]predictor.PlayerPrediction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []predictor.PlayerPrediction) error); ok {
		r1 = returnFunc(ctx, players)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPredictor_PredictWin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PredictWin'
type MockPredictor_PredictWin_Call struct {
	*mock.Call
}

// PredictWin is a helper method to define mock.On call
//   - ctx context.Context
//   - players []predictor.PlayerPrediction
func (_e *MockPredictor_Expecter) PredictWin(ctx interface{}, players interface{}) *MockPredictor_PredictWin_Call {
	return &MockPredictor_PredictWin_Call{Call: _e.mock.On("PredictWin", ctx, players)}
}

func (_c *MockPredictor_PredictWin_Call) Run(run func(ctx context.Context, players []predictor.PlayerPrediction)) *MockPredictor_PredictWin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []predictor.PlayerPrediction
		if args[1] != nil {
			arg1 = args[1].([]predictor.PlayerPrediction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPredictor_PredictWin_Call) Return(playerPredictions []predictor.PlayerPrediction, err error) *MockPredictor_PredictWin_Call {
	_c.Call.Return(playerPredictions, err)
	return _c
}

func (_c *MockPredictor_PredictWin_Call) RunAndReturn(run func(ctx context.Context, players []predictor.PlayerPrediction) ([]predictor.PlayerPrediction, error)) *MockPredictor_PredictWin_Call {
	_c.Call.Return(run)
	return _c
}
