// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBattingExporter creates a new instance of MockBattingExporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBattingExporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBattingExporter {
	mock := &MockBattingExporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBattingExporter is an autogenerated mock type for the BattingExporter type
type MockBattingExporter struct {
	mock.Mock
}

type MockBattingExporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBattingExporter) EXPECT() *MockBattingExporter_Expecter {
	return &MockBattingExporter_Expecter{mock: &_m.Mock}
}

// ExportFormat provides a mock function for the type MockBattingExporter
func (_mock *MockBattingExporter) ExportFormat(ctx context.Context, format string, w io.Writer) error {
	ret := _mock.Called(ctx, format, w)

	if len(ret) == 0 {
		panic("no return value specified for ExportFormat")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Writer) error); ok {
		r0 = returnFunc(ctx, format, w)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBattingExporter_ExportFormat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportFormat'
type MockBattingExporter_ExportFormat_Call struct {
	*mock.Call
}

// ExportFormat is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
//   - w io.Writer
func (_e *MockBattingExporter_Expecter) ExportFormat(ctx interface{}, format interface{}, w interface{}) *MockBattingExporter_ExportFormat_Call {
	return &MockBattingExporter_ExportFormat_Call{Call: _e.mock.On("ExportFormat", ctx, format, w)}
}

func (_c *MockBattingExporter_ExportFormat_Call) Run(run func(ctx context.Context, format string, w io.Writer)) *MockBattingExporter_ExportFormat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Writer
		if args[2] != nil {
			arg2 = args[2].(io.Writer)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBattingExporter_ExportFormat_Call) Return(err error) *MockBattingExporter_ExportFormat_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBattingExporter_ExportFormat_Call) RunAndReturn(run func(ctx context.Context, format string, w io.Writer) error) *MockBattingExporter_ExportFormat_Call {
	_c.Call.Return(run)
	return _c
}

// ExportInference provides a mock function for the type MockBattingExporter
func (_mock *MockBattingExporter) ExportInference(ctx context.Context, format string, w io.Writer) error {
	ret := _mock.Called(ctx, format, w)

	if len(ret) == 0 {
		panic("no return value specified for ExportInference")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Writer) error); ok {
		r0 = returnFunc(ctx, format, w)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBattingExporter_ExportInference_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportInference'
type MockBattingExporter_ExportInference_Call struct {
	*mock.Call
}

// ExportInference is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
//   - w io.Writer
func (_e *MockBattingExporter_Expecter) ExportInference(ctx interface{}, format interface{}, w interface{}) *MockBattingExporter_ExportInference_Call {
	return &MockBattingExporter_ExportInference_Call{Call: _e.mock.On("ExportInference", ctx, format, w)}
}

func (_c *MockBattingExporter_ExportInference_Call) Run(run func(ctx context.Context, format string, w io.Writer)) *MockBattingExporter_ExportInference_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Writer
		if args[2] != nil {
			arg2 = args[2].(io.Writer)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBattingExporter_ExportInference_Call) Return(err error) *MockBattingExporter_ExportInference_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBattingExporter_ExportInference_Call) RunAndReturn(run func(ctx context.Context, format string, w io.Writer) error) *MockBattingExporter_ExportInference_Call {
	_c.Call.Return(run)
	return _c
}

// ExportLegacy provides a mock function for the type MockBattingExporter
func (_mock *MockBattingExporter) ExportLegacy(ctx context.Context, w io.Writer) error {
	ret := _mock.Called(ctx, w)

	if len(ret) == 0 {
		panic("no return value specified for ExportLegacy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Writer) error); ok {
		r0 = returnFunc(ctx, w)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBattingExporter_ExportLegacy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportLegacy'
type MockBattingExporter_ExportLegacy_Call struct {
	*mock.Call
}

// ExportLegacy is a helper method to define mock.On call
//   - ctx context.Context
//   - w io.Writer
func (_e *MockBattingExporter_Expecter) ExportLegacy(ctx interface{}, w interface{}) *MockBattingExporter_ExportLegacy_Call {
	return &MockBattingExporter_ExportLegacy_Call{Call: _e.mock.On("ExportLegacy", ctx, w)}
}

func (_c *MockBattingExporter_ExportLegacy_Call) Run(run func(ctx context.Context, w io.Writer)) *MockBattingExporter_ExportLegacy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Writer
		if args[1] != nil {
			arg1 = args[1].(io.Writer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBattingExporter_ExportLegacy_Call) Return(err error) *MockBattingExporter_ExportLegacy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBattingExporter_ExportLegacy_Call) RunAndReturn(run func(ctx context.Context, w io.Writer) error) *MockBattingExporter_ExportLegacy_Call {
	_c.Call.Return(run)
	return _c
}

// ExportUnified provides a mock function for the type MockBattingExporter
func (_mock *MockBattingExporter) ExportUnified(ctx context.Context, w io.Writer) error {
	ret := _mock.Called(ctx, w)

	if len(ret) == 0 {
		panic("no return value specified for ExportUnified")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Writer) error); ok {
		r0 = returnFunc(ctx, w)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBattingExporter_ExportUnified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportUnified'
type MockBattingExporter_ExportUnified_Call struct {
	*mock.Call
}

// ExportUnified is a helper method to define mock.On call
//   - ctx context.Context
//   - w io.Writer
func (_e *MockBattingExporter_Expecter) ExportUnified(ctx interface{}, w interface{}) *MockBattingExporter_ExportUnified_Call {
	return &MockBattingExporter_ExportUnified_Call{Call: _e.mock.On("ExportUnified", ctx, w)}
}

func (_c *MockBattingExporter_ExportUnified_Call) Run(run func(ctx context.Context, w io.Writer)) *MockBattingExporter_ExportUnified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Writer
		if args[1] != nil {
			arg1 = args[1].(io.Writer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBattingExporter_ExportUnified_Call) Return(err error) *MockBattingExporter_ExportUnified_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBattingExporter_ExportUnified_Call) RunAndReturn(run func(ctx context.Context, w io.Writer) error) *MockBattingExporter_ExportUnified_Call {
	_c.Call.Return(run)
	return _c
}
