// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockExtrasExporter creates a new instance of MockExtrasExporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExtrasExporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExtrasExporter {
	mock := &MockExtrasExporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExtrasExporter is an autogenerated mock type for the ExtrasExporter type
type MockExtrasExporter struct {
	mock.Mock
}

type MockExtrasExporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExtrasExporter) EXPECT() *MockExtrasExporter_Expecter {
	return &MockExtrasExporter_Expecter{mock: &_m.Mock}
}

// ExportFormat provides a mock function for the type MockExtrasExporter
func (_mock *MockExtrasExporter) ExportFormat(ctx context.Context, format string, w io.Writer) error {
	ret := _mock.Called(ctx, format, w)

	if len(ret) == 0 {
		panic("no return value specified for ExportFormat")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Writer) error); ok {
		r0 = returnFunc(ctx, format, w)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExtrasExporter_ExportFormat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportFormat'
type MockExtrasExporter_ExportFormat_Call struct {
	*mock.Call
}

// ExportFormat is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
//   - w io.Writer
func (_e *MockExtrasExporter_Expecter) ExportFormat(ctx interface{}, format interface{}, w interface{}) *MockExtrasExporter_ExportFormat_Call {
	return &MockExtrasExporter_ExportFormat_Call{Call: _e.mock.On("ExportFormat", ctx, format, w)}
}

func (_c *MockExtrasExporter_ExportFormat_Call) Run(run func(ctx context.Context, format string, w io.Writer)) *MockExtrasExporter_ExportFormat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Writer
		if args[2] != nil {
			arg2 = args[2].(io.Writer)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockExtrasExporter_ExportFormat_Call) Return(err error) *MockExtrasExporter_ExportFormat_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExtrasExporter_ExportFormat_Call) RunAndReturn(run func(ctx context.Context, format string, w io.Writer) error) *MockExtrasExporter_ExportFormat_Call {
	_c.Call.Return(run)
	return _c
}

// ExportUnified provides a mock function for the type MockExtrasExporter
func (_mock *MockExtrasExporter) ExportUnified(ctx context.Context, w io.Writer) error {
	ret := _mock.Called(ctx, w)

	if len(ret) == 0 {
		panic("no return value specified for ExportUnified")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Writer) error); ok {
		r0 = returnFunc(ctx, w)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExtrasExporter_ExportUnified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportUnified'
type MockExtrasExporter_ExportUnified_Call struct {
	*mock.Call
}

// ExportUnified is a helper method to define mock.On call
//   - ctx context.Context
//   - w io.Writer
func (_e *MockExtrasExporter_Expecter) ExportUnified(ctx interface{}, w interface{}) *MockExtrasExporter_ExportUnified_Call {
	return &MockExtrasExporter_ExportUnified_Call{Call: _e.mock.On("ExportUnified", ctx, w)}
}

func (_c *MockExtrasExporter_ExportUnified_Call) Run(run func(ctx context.Context, w io.Writer)) *MockExtrasExporter_ExportUnified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Writer
		if args[1] != nil {
			arg1 = args[1].(io.Writer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExtrasExporter_ExportUnified_Call) Return(err error) *MockExtrasExporter_ExportUnified_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExtrasExporter_ExportUnified_Call) RunAndReturn(run func(ctx context.Context, w io.Writer) error) *MockExtrasExporter_ExportUnified_Call {
	_c.Call.Return(run)
	return _c
}
