// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockWinExporter creates a new instance of MockWinExporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWinExporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWinExporter {
	mock := &MockWinExporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWinExporter is an autogenerated mock type for the WinExporter type
type MockWinExporter struct {
	mock.Mock
}

type MockWinExporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWinExporter) EXPECT() *MockWinExporter_Expecter {
	return &MockWinExporter_Expecter{mock: &_m.Mock}
}

// ExportFormat provides a mock function for the type MockWinExporter
func (_mock *MockWinExporter) ExportFormat(ctx context.Context, format string, w io.Writer) error {
	ret := _mock.Called(ctx, format, w)

	if len(ret) == 0 {
		panic("no return value specified for ExportFormat")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Writer) error); ok {
		r0 = returnFunc(ctx, format, w)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWinExporter_ExportFormat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportFormat'
type MockWinExporter_ExportFormat_Call struct {
	*mock.Call
}

// ExportFormat is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
//   - w io.Writer
func (_e *MockWinExporter_Expecter) ExportFormat(ctx interface{}, format interface{}, w interface{}) *MockWinExporter_ExportFormat_Call {
	return &MockWinExporter_ExportFormat_Call{Call: _e.mock.On("ExportFormat", ctx, format, w)}
}

func (_c *MockWinExporter_ExportFormat_Call) Run(run func(ctx context.Context, format string, w io.Writer)) *MockWinExporter_ExportFormat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Writer
		if args[2] != nil {
			arg2 = args[2].(io.Writer)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWinExporter_ExportFormat_Call) Return(err error) *MockWinExporter_ExportFormat_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWinExporter_ExportFormat_Call) RunAndReturn(run func(ctx context.Context, format string, w io.Writer) error) *MockWinExporter_ExportFormat_Call {
	_c.Call.Return(run)
	return _c
}

// ExportUnified provides a mock function for the type MockWinExporter
func (_mock *MockWinExporter) ExportUnified(ctx context.Context, w io.Writer) error {
	ret := _mock.Called(ctx, w)

	if len(ret) == 0 {
		panic("no return value specified for ExportUnified")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Writer) error); ok {
		r0 = returnFunc(ctx, w)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWinExporter_ExportUnified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportUnified'
type MockWinExporter_ExportUnified_Call struct {
	*mock.Call
}

// ExportUnified is a helper method to define mock.On call
//   - ctx context.Context
//   - w io.Writer
func (_e *MockWinExporter_Expecter) ExportUnified(ctx interface{}, w interface{}) *MockWinExporter_ExportUnified_Call {
	return &MockWinExporter_ExportUnified_Call{Call: _e.mock.On("ExportUnified", ctx, w)}
}

func (_c *MockWinExporter_ExportUnified_Call) Run(run func(ctx context.Context, w io.Writer)) *MockWinExporter_ExportUnified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Writer
		if args[1] != nil {
			arg1 = args[1].(io.Writer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWinExporter_ExportUnified_Call) Return(err error) *MockWinExporter_ExportUnified_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWinExporter_ExportUnified_Call) RunAndReturn(run func(ctx context.Context, w io.Writer) error) *MockWinExporter_ExportUnified_Call {
	_c.Call.Return(run)
	return _c
}
