batting_dataset_query = (
    "SELECT runs, batting_data.balls, batting_data.fours, batting_data.sixes, "
    "batting_position, "
    "player.batting_consistency, player_form_data.batting_form, "
    "weather.temp, weather.wind, weather.rain, weather.humidity, weather.cloud, "
    "weather.pressure, weather.viscosity, match_details.inning, "
    "match_details.batting_session, match_details.toss, "
    "player_venue_data.batting_venue, player_opposition_data.batting_opposition, "
    "season.id as season_id, player.player_name "
    "FROM `batting_data` "
    "LEFT JOIN player ON player_id = player.id "
    "LEFT JOIN (SELECT * FROM weather_data WHERE SESSION LIKE 'batting') AS weather "
    "ON batting_data.match_id = weather.match_id "
    "LEFT JOIN match_details ON match_details.match_id = weather.match_id "
    "LEFT JOIN venue ON venue.id = match_details.venue_id "
    "LEFT JOIN opposition ON opposition.id = match_details.opposition_id "
    "LEFT JOIN season ON season.id = match_details.season_id "
    "LEFT JOIN player_venue_data ON batting_data.player_id = player_venue_data.player_id "
    "AND match_details.venue_id = player_venue_data.venue_id "
    "LEFT JOIN player_opposition_data ON batting_data.player_id = player_opposition_data.player_id "
    "AND match_details.opposition_id = player_opposition_data.opposition_id "
    "LEFT JOIN player_form_data ON batting_data.player_id = player_form_data.player_id "
    "AND match_details.season_id = player_form_data.season_id"
)

batting_win_dataset_query = (
    "SELECT match_details.score, match_details.balls, runs, batting_data.balls, "
    "batting_data.fours, batting_data.sixes, strike_rate, batting_data.match_id, batting_position, "
    "player.player_name, player.batting_consistency, player_form_data.batting_form, "
    "weather.temp, weather.wind, weather.rain, weather.humidity, weather.cloud, weather.pressure, "
    "weather.viscosity, match_details.inning, match_details.batting_session, match_details.toss, "
    "player_venue_data.batting_venue, player_opposition_data.batting_opposition, "
    "season.id as season_id, match_details.result "
    "FROM `batting_data` LEFT JOIN player ON player_id = player.id "
    "LEFT JOIN (SELECT * FROM weather_data WHERE SESSION LIKE 'batting') AS weather "
    "ON batting_data.match_id = weather.match_id "
    "LEFT JOIN match_details ON match_details.match_id = weather.match_id "
    "LEFT JOIN venue ON venue.id = match_details.venue_id "
    "LEFT JOIN opposition ON opposition.id = match_details.opposition_id "
    "LEFT JOIN season ON season.id = match_details.season_id "
    "LEFT JOIN player_venue_data ON batting_data.player_id = player_venue_data.player_id "
    "AND match_details.venue_id = player_venue_data.venue_id "
    "LEFT JOIN player_opposition_data ON batting_data.player_id = player_opposition_data.player_id "
    "AND match_details.opposition_id = player_opposition_data.opposition_id "
    "LEFT JOIN player_form_data ON batting_data.player_id = player_form_data.player_id "
    "AND match_details.season_id = player_form_data.season_id"
)

bowling_dataset_query = (
    "SELECT bowling_data.runs, bowling_data.balls, bowling_data.wickets, "
    "player.bowling_consistency, player_form_data.bowling_form, "
    "weather.temp, weather.wind, weather.rain, weather.humidity, weather.cloud, "
    "weather.pressure, weather.viscosity, match_details.inning, match_details.bowling_session, "
    "match_details.toss, player_venue_data.bowling_venue, player_opposition_data.bowling_opposition, "
    "season.id as season_id, player.player_name "
    "FROM `bowling_data` LEFT JOIN player ON player_id = player.id "
    "LEFT JOIN (SELECT * FROM weather_data WHERE SESSION LIKE 'bowling') AS weather "
    "ON bowling_data.match_id = weather.match_id "
    "LEFT JOIN match_details ON match_details.match_id = weather.match_id "
    "LEFT JOIN venue ON venue.id = match_details.venue_id "
    "LEFT JOIN opposition ON opposition.id = match_details.opposition_id "
    "LEFT JOIN season ON season.id = match_details.season_id "
    "LEFT JOIN player_venue_data ON bowling_data.player_id = player_venue_data.player_id "
    "AND match_details.venue_id = player_venue_data.venue_id "
    "LEFT JOIN player_opposition_data ON bowling_data.player_id = player_opposition_data.player_id "
    "AND match_details.opposition_id = player_opposition_data.opposition_id "
    "LEFT JOIN player_form_data ON bowling_data.player_id = player_form_data.player_id "
    "AND match_details.season_id = player_form_data.season_id"
)
