// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDatasetRepo creates a new instance of MockDatasetRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatasetRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatasetRepo {
	mock := &MockDatasetRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDatasetRepo is an autogenerated mock type for the DatasetRepo type
type MockDatasetRepo struct {
	mock.Mock
}

type MockDatasetRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatasetRepo) EXPECT() *MockDatasetRepo_Expecter {
	return &MockDatasetRepo_Expecter{mock: &_m.Mock}
}

// BattingFormatRows provides a mock function for the type MockDatasetRepo
func (_mock *MockDatasetRepo) BattingFormatRows(ctx context.Context, format string) ([][]string, error) {
	ret := _mock.Called(ctx, format)

	if len(ret) == 0 {
		panic("no return value specified for BattingFormatRows")
	}

	var r0 [][]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([][]string, error)); ok {
		return returnFunc(ctx, format)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) [][]string); ok {
		r0 = returnFunc(ctx, format)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, format)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatasetRepo_BattingFormatRows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BattingFormatRows'
type MockDatasetRepo_BattingFormatRows_Call struct {
	*mock.Call
}

// BattingFormatRows is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
func (_e *MockDatasetRepo_Expecter) BattingFormatRows(ctx interface{}, format interface{}) *MockDatasetRepo_BattingFormatRows_Call {
	return &MockDatasetRepo_BattingFormatRows_Call{Call: _e.mock.On("BattingFormatRows", ctx, format)}
}

func (_c *MockDatasetRepo_BattingFormatRows_Call) Run(run func(ctx context.Context, format string)) *MockDatasetRepo_BattingFormatRows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatasetRepo_BattingFormatRows_Call) Return(stringss [][]string, err error) *MockDatasetRepo_BattingFormatRows_Call {
	_c.Call.Return(stringss, err)
	return _c
}

func (_c *MockDatasetRepo_BattingFormatRows_Call) RunAndReturn(run func(ctx context.Context, format string) ([][]string, error)) *MockDatasetRepo_BattingFormatRows_Call {
	_c.Call.Return(run)
	return _c
}

// BattingInferenceRows provides a mock function for the type MockDatasetRepo
func (_mock *MockDatasetRepo) BattingInferenceRows(ctx context.Context, format string) ([][]string, error) {
	ret := _mock.Called(ctx, format)

	if len(ret) == 0 {
		panic("no return value specified for BattingInferenceRows")
	}

	var r0 [][]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([][]string, error)); ok {
		return returnFunc(ctx, format)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) [][]string); ok {
		r0 = returnFunc(ctx, format)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, format)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatasetRepo_BattingInferenceRows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BattingInferenceRows'
type MockDatasetRepo_BattingInferenceRows_Call struct {
	*mock.Call
}

// BattingInferenceRows is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
func (_e *MockDatasetRepo_Expecter) BattingInferenceRows(ctx interface{}, format interface{}) *MockDatasetRepo_BattingInferenceRows_Call {
	return &MockDatasetRepo_BattingInferenceRows_Call{Call: _e.mock.On("BattingInferenceRows", ctx, format)}
}

func (_c *MockDatasetRepo_BattingInferenceRows_Call) Run(run func(ctx context.Context, format string)) *MockDatasetRepo_BattingInferenceRows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatasetRepo_BattingInferenceRows_Call) Return(stringss [][]string, err error) *MockDatasetRepo_BattingInferenceRows_Call {
	_c.Call.Return(stringss, err)
	return _c
}

func (_c *MockDatasetRepo_BattingInferenceRows_Call) RunAndReturn(run func(ctx context.Context, format string) ([][]string, error)) *MockDatasetRepo_BattingInferenceRows_Call {
	_c.Call.Return(run)
	return _c
}

// BattingUnifiedRows provides a mock function for the type MockDatasetRepo
func (_mock *MockDatasetRepo) BattingUnifiedRows(ctx context.Context) ([][]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BattingUnifiedRows")
	}

	var r0 [][]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([][]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) [][]string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatasetRepo_BattingUnifiedRows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BattingUnifiedRows'
type MockDatasetRepo_BattingUnifiedRows_Call struct {
	*mock.Call
}

// BattingUnifiedRows is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatasetRepo_Expecter) BattingUnifiedRows(ctx interface{}) *MockDatasetRepo_BattingUnifiedRows_Call {
	return &MockDatasetRepo_BattingUnifiedRows_Call{Call: _e.mock.On("BattingUnifiedRows", ctx)}
}

func (_c *MockDatasetRepo_BattingUnifiedRows_Call) Run(run func(ctx context.Context)) *MockDatasetRepo_BattingUnifiedRows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDatasetRepo_BattingUnifiedRows_Call) Return(stringss [][]string, err error) *MockDatasetRepo_BattingUnifiedRows_Call {
	_c.Call.Return(stringss, err)
	return _c
}

func (_c *MockDatasetRepo_BattingUnifiedRows_Call) RunAndReturn(run func(ctx context.Context) ([][]string, error)) *MockDatasetRepo_BattingUnifiedRows_Call {
	_c.Call.Return(run)
	return _c
}

// BowlingFormatRows provides a mock function for the type MockDatasetRepo
func (_mock *MockDatasetRepo) BowlingFormatRows(ctx context.Context, format string) ([][]string, error) {
	ret := _mock.Called(ctx, format)

	if len(ret) == 0 {
		panic("no return value specified for BowlingFormatRows")
	}

	var r0 [][]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([][]string, error)); ok {
		return returnFunc(ctx, format)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) [][]string); ok {
		r0 = returnFunc(ctx, format)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, format)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatasetRepo_BowlingFormatRows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BowlingFormatRows'
type MockDatasetRepo_BowlingFormatRows_Call struct {
	*mock.Call
}

// BowlingFormatRows is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
func (_e *MockDatasetRepo_Expecter) BowlingFormatRows(ctx interface{}, format interface{}) *MockDatasetRepo_BowlingFormatRows_Call {
	return &MockDatasetRepo_BowlingFormatRows_Call{Call: _e.mock.On("BowlingFormatRows", ctx, format)}
}

func (_c *MockDatasetRepo_BowlingFormatRows_Call) Run(run func(ctx context.Context, format string)) *MockDatasetRepo_BowlingFormatRows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatasetRepo_BowlingFormatRows_Call) Return(stringss [][]string, err error) *MockDatasetRepo_BowlingFormatRows_Call {
	_c.Call.Return(stringss, err)
	return _c
}

func (_c *MockDatasetRepo_BowlingFormatRows_Call) RunAndReturn(run func(ctx context.Context, format string) ([][]string, error)) *MockDatasetRepo_BowlingFormatRows_Call {
	_c.Call.Return(run)
	return _c
}

// BowlingInferenceRows provides a mock function for the type MockDatasetRepo
func (_mock *MockDatasetRepo) BowlingInferenceRows(ctx context.Context, format string) ([][]string, error) {
	ret := _mock.Called(ctx, format)

	if len(ret) == 0 {
		panic("no return value specified for BowlingInferenceRows")
	}

	var r0 [][]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([][]string, error)); ok {
		return returnFunc(ctx, format)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) [][]string); ok {
		r0 = returnFunc(ctx, format)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, format)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatasetRepo_BowlingInferenceRows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BowlingInferenceRows'
type MockDatasetRepo_BowlingInferenceRows_Call struct {
	*mock.Call
}

// BowlingInferenceRows is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
func (_e *MockDatasetRepo_Expecter) BowlingInferenceRows(ctx interface{}, format interface{}) *MockDatasetRepo_BowlingInferenceRows_Call {
	return &MockDatasetRepo_BowlingInferenceRows_Call{Call: _e.mock.On("BowlingInferenceRows", ctx, format)}
}

func (_c *MockDatasetRepo_BowlingInferenceRows_Call) Run(run func(ctx context.Context, format string)) *MockDatasetRepo_BowlingInferenceRows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatasetRepo_BowlingInferenceRows_Call) Return(stringss [][]string, err error) *MockDatasetRepo_BowlingInferenceRows_Call {
	_c.Call.Return(stringss, err)
	return _c
}

func (_c *MockDatasetRepo_BowlingInferenceRows_Call) RunAndReturn(run func(ctx context.Context, format string) ([][]string, error)) *MockDatasetRepo_BowlingInferenceRows_Call {
	_c.Call.Return(run)
	return _c
}

// BowlingUnifiedRows provides a mock function for the type MockDatasetRepo
func (_mock *MockDatasetRepo) BowlingUnifiedRows(ctx context.Context) ([][]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BowlingUnifiedRows")
	}

	var r0 [][]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([][]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) [][]string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatasetRepo_BowlingUnifiedRows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BowlingUnifiedRows'
type MockDatasetRepo_BowlingUnifiedRows_Call struct {
	*mock.Call
}

// BowlingUnifiedRows is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatasetRepo_Expecter) BowlingUnifiedRows(ctx interface{}) *MockDatasetRepo_BowlingUnifiedRows_Call {
	return &MockDatasetRepo_BowlingUnifiedRows_Call{Call: _e.mock.On("BowlingUnifiedRows", ctx)}
}

func (_c *MockDatasetRepo_BowlingUnifiedRows_Call) Run(run func(ctx context.Context)) *MockDatasetRepo_BowlingUnifiedRows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDatasetRepo_BowlingUnifiedRows_Call) Return(stringss [][]string, err error) *MockDatasetRepo_BowlingUnifiedRows_Call {
	_c.Call.Return(stringss, err)
	return _c
}

func (_c *MockDatasetRepo_BowlingUnifiedRows_Call) RunAndReturn(run func(ctx context.Context) ([][]string, error)) *MockDatasetRepo_BowlingUnifiedRows_Call {
	_c.Call.Return(run)
	return _c
}

// ExtrasFormatRows provides a mock function for the type MockDatasetRepo
func (_mock *MockDatasetRepo) ExtrasFormatRows(ctx context.Context, format string) ([][]string, error) {
	ret := _mock.Called(ctx, format)

	if len(ret) == 0 {
		panic("no return value specified for ExtrasFormatRows")
	}

	var r0 [][]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([][]string, error)); ok {
		return returnFunc(ctx, format)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) [][]string); ok {
		r0 = returnFunc(ctx, format)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, format)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatasetRepo_ExtrasFormatRows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtrasFormatRows'
type MockDatasetRepo_ExtrasFormatRows_Call struct {
	*mock.Call
}

// ExtrasFormatRows is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
func (_e *MockDatasetRepo_Expecter) ExtrasFormatRows(ctx interface{}, format interface{}) *MockDatasetRepo_ExtrasFormatRows_Call {
	return &MockDatasetRepo_ExtrasFormatRows_Call{Call: _e.mock.On("ExtrasFormatRows", ctx, format)}
}

func (_c *MockDatasetRepo_ExtrasFormatRows_Call) Run(run func(ctx context.Context, format string)) *MockDatasetRepo_ExtrasFormatRows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatasetRepo_ExtrasFormatRows_Call) Return(stringss [][]string, err error) *MockDatasetRepo_ExtrasFormatRows_Call {
	_c.Call.Return(stringss, err)
	return _c
}

func (_c *MockDatasetRepo_ExtrasFormatRows_Call) RunAndReturn(run func(ctx context.Context, format string) ([][]string, error)) *MockDatasetRepo_ExtrasFormatRows_Call {
	_c.Call.Return(run)
	return _c
}

// ExtrasUnifiedRows provides a mock function for the type MockDatasetRepo
func (_mock *MockDatasetRepo) ExtrasUnifiedRows(ctx context.Context) ([][]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ExtrasUnifiedRows")
	}

	var r0 [][]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([][]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) [][]string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatasetRepo_ExtrasUnifiedRows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtrasUnifiedRows'
type MockDatasetRepo_ExtrasUnifiedRows_Call struct {
	*mock.Call
}

// ExtrasUnifiedRows is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatasetRepo_Expecter) ExtrasUnifiedRows(ctx interface{}) *MockDatasetRepo_ExtrasUnifiedRows_Call {
	return &MockDatasetRepo_ExtrasUnifiedRows_Call{Call: _e.mock.On("ExtrasUnifiedRows", ctx)}
}

func (_c *MockDatasetRepo_ExtrasUnifiedRows_Call) Run(run func(ctx context.Context)) *MockDatasetRepo_ExtrasUnifiedRows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDatasetRepo_ExtrasUnifiedRows_Call) Return(stringss [][]string, err error) *MockDatasetRepo_ExtrasUnifiedRows_Call {
	_c.Call.Return(stringss, err)
	return _c
}

func (_c *MockDatasetRepo_ExtrasUnifiedRows_Call) RunAndReturn(run func(ctx context.Context) ([][]string, error)) *MockDatasetRepo_ExtrasUnifiedRows_Call {
	_c.Call.Return(run)
	return _c
}

// FieldingFormatRows provides a mock function for the type MockDatasetRepo
func (_mock *MockDatasetRepo) FieldingFormatRows(ctx context.Context, format string) ([][]string, error) {
	ret := _mock.Called(ctx, format)

	if len(ret) == 0 {
		panic("no return value specified for FieldingFormatRows")
	}

	var r0 [][]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([][]string, error)); ok {
		return returnFunc(ctx, format)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) [][]string); ok {
		r0 = returnFunc(ctx, format)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, format)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatasetRepo_FieldingFormatRows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FieldingFormatRows'
type MockDatasetRepo_FieldingFormatRows_Call struct {
	*mock.Call
}

// FieldingFormatRows is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
func (_e *MockDatasetRepo_Expecter) FieldingFormatRows(ctx interface{}, format interface{}) *MockDatasetRepo_FieldingFormatRows_Call {
	return &MockDatasetRepo_FieldingFormatRows_Call{Call: _e.mock.On("FieldingFormatRows", ctx, format)}
}

func (_c *MockDatasetRepo_FieldingFormatRows_Call) Run(run func(ctx context.Context, format string)) *MockDatasetRepo_FieldingFormatRows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatasetRepo_FieldingFormatRows_Call) Return(stringss [][]string, err error) *MockDatasetRepo_FieldingFormatRows_Call {
	_c.Call.Return(stringss, err)
	return _c
}

func (_c *MockDatasetRepo_FieldingFormatRows_Call) RunAndReturn(run func(ctx context.Context, format string) ([][]string, error)) *MockDatasetRepo_FieldingFormatRows_Call {
	_c.Call.Return(run)
	return _c
}

// FieldingUnifiedRows provides a mock function for the type MockDatasetRepo
func (_mock *MockDatasetRepo) FieldingUnifiedRows(ctx context.Context) ([][]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FieldingUnifiedRows")
	}

	var r0 [][]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([][]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) [][]string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatasetRepo_FieldingUnifiedRows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FieldingUnifiedRows'
type MockDatasetRepo_FieldingUnifiedRows_Call struct {
	*mock.Call
}

// FieldingUnifiedRows is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatasetRepo_Expecter) FieldingUnifiedRows(ctx interface{}) *MockDatasetRepo_FieldingUnifiedRows_Call {
	return &MockDatasetRepo_FieldingUnifiedRows_Call{Call: _e.mock.On("FieldingUnifiedRows", ctx)}
}

func (_c *MockDatasetRepo_FieldingUnifiedRows_Call) Run(run func(ctx context.Context)) *MockDatasetRepo_FieldingUnifiedRows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDatasetRepo_FieldingUnifiedRows_Call) Return(stringss [][]string, err error) *MockDatasetRepo_FieldingUnifiedRows_Call {
	_c.Call.Return(stringss, err)
	return _c
}

func (_c *MockDatasetRepo_FieldingUnifiedRows_Call) RunAndReturn(run func(ctx context.Context) ([][]string, error)) *MockDatasetRepo_FieldingUnifiedRows_Call {
	_c.Call.Return(run)
	return _c
}

// WinFormatRows provides a mock function for the type MockDatasetRepo
func (_mock *MockDatasetRepo) WinFormatRows(ctx context.Context, format string) ([][]string, error) {
	ret := _mock.Called(ctx, format)

	if len(ret) == 0 {
		panic("no return value specified for WinFormatRows")
	}

	var r0 [][]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([][]string, error)); ok {
		return returnFunc(ctx, format)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) [][]string); ok {
		r0 = returnFunc(ctx, format)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, format)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatasetRepo_WinFormatRows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WinFormatRows'
type MockDatasetRepo_WinFormatRows_Call struct {
	*mock.Call
}

// WinFormatRows is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
func (_e *MockDatasetRepo_Expecter) WinFormatRows(ctx interface{}, format interface{}) *MockDatasetRepo_WinFormatRows_Call {
	return &MockDatasetRepo_WinFormatRows_Call{Call: _e.mock.On("WinFormatRows", ctx, format)}
}

func (_c *MockDatasetRepo_WinFormatRows_Call) Run(run func(ctx context.Context, format string)) *MockDatasetRepo_WinFormatRows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatasetRepo_WinFormatRows_Call) Return(stringss [][]string, err error) *MockDatasetRepo_WinFormatRows_Call {
	_c.Call.Return(stringss, err)
	return _c
}

func (_c *MockDatasetRepo_WinFormatRows_Call) RunAndReturn(run func(ctx context.Context, format string) ([][]string, error)) *MockDatasetRepo_WinFormatRows_Call {
	_c.Call.Return(run)
	return _c
}

// WinUnifiedRows provides a mock function for the type MockDatasetRepo
func (_mock *MockDatasetRepo) WinUnifiedRows(ctx context.Context) ([][]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for WinUnifiedRows")
	}

	var r0 [][]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([][]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) [][]string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatasetRepo_WinUnifiedRows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WinUnifiedRows'
type MockDatasetRepo_WinUnifiedRows_Call struct {
	*mock.Call
}

// WinUnifiedRows is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatasetRepo_Expecter) WinUnifiedRows(ctx interface{}) *MockDatasetRepo_WinUnifiedRows_Call {
	return &MockDatasetRepo_WinUnifiedRows_Call{Call: _e.mock.On("WinUnifiedRows", ctx)}
}

func (_c *MockDatasetRepo_WinUnifiedRows_Call) Run(run func(ctx context.Context)) *MockDatasetRepo_WinUnifiedRows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDatasetRepo_WinUnifiedRows_Call) Return(stringss [][]string, err error) *MockDatasetRepo_WinUnifiedRows_Call {
	_c.Call.Return(stringss, err)
	return _c
}

func (_c *MockDatasetRepo_WinUnifiedRows_Call) RunAndReturn(run func(ctx context.Context) ([][]string, error)) *MockDatasetRepo_WinUnifiedRows_Call {
	_c.Call.Return(run)
	return _c
}
