// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/umayangag/cric-info-scrapers/go-app/internal/db"
)

// NewMockFieldingRepo creates a new instance of MockFieldingRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFieldingRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFieldingRepo {
	mock := &MockFieldingRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFieldingRepo is an autogenerated mock type for the FieldingRepo type
type MockFieldingRepo struct {
	mock.Mock
}

type MockFieldingRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFieldingRepo) EXPECT() *MockFieldingRepo_Expecter {
	return &MockFieldingRepo_Expecter{mock: &_m.Mock}
}

// ListFieldingEvents provides a mock function for the type MockFieldingRepo
func (_mock *MockFieldingRepo) ListFieldingEvents(ctx context.Context, matchID *int64) ([]db.BackfillEvent, error) {
	ret := _mock.Called(ctx, matchID)

	if len(ret) == 0 {
		panic("no return value specified for ListFieldingEvents")
	}

	var r0 []db.BackfillEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int64) ([]db.BackfillEvent, error)); ok {
		return returnFunc(ctx, matchID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int64) []db.BackfillEvent); ok {
		r0 = returnFunc(ctx, matchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.BackfillEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *int64) error); ok {
		r1 = returnFunc(ctx, matchID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFieldingRepo_ListFieldingEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFieldingEvents'
type MockFieldingRepo_ListFieldingEvents_Call struct {
	*mock.Call
}

// ListFieldingEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - matchID *int64
func (_e *MockFieldingRepo_Expecter) ListFieldingEvents(ctx interface{}, matchID interface{}) *MockFieldingRepo_ListFieldingEvents_Call {
	return &MockFieldingRepo_ListFieldingEvents_Call{Call: _e.mock.On("ListFieldingEvents", ctx, matchID)}
}

func (_c *MockFieldingRepo_ListFieldingEvents_Call) Run(run func(ctx context.Context, matchID *int64)) *MockFieldingRepo_ListFieldingEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *int64
		if args[1] != nil {
			arg1 = args[1].(*int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFieldingRepo_ListFieldingEvents_Call) Return(backfillEvents []db.BackfillEvent, err error) *MockFieldingRepo_ListFieldingEvents_Call {
	_c.Call.Return(backfillEvents, err)
	return _c
}

func (_c *MockFieldingRepo_ListFieldingEvents_Call) RunAndReturn(run func(ctx context.Context, matchID *int64) ([]db.BackfillEvent, error)) *MockFieldingRepo_ListFieldingEvents_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertFieldingAggregates provides a mock function for the type MockFieldingRepo
func (_mock *MockFieldingRepo) UpsertFieldingAggregates(ctx context.Context, rows []db.FieldingAggregateRow) error {
	ret := _mock.Called(ctx, rows)

	if len(ret) == 0 {
		panic("no return value specified for UpsertFieldingAggregates")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []db.FieldingAggregateRow) error); ok {
		r0 = returnFunc(ctx, rows)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFieldingRepo_UpsertFieldingAggregates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertFieldingAggregates'
type MockFieldingRepo_UpsertFieldingAggregates_Call struct {
	*mock.Call
}

// UpsertFieldingAggregates is a helper method to define mock.On call
//   - ctx context.Context
//   - rows []db.FieldingAggregateRow
func (_e *MockFieldingRepo_Expecter) UpsertFieldingAggregates(ctx interface{}, rows interface{}) *MockFieldingRepo_UpsertFieldingAggregates_Call {
	return &MockFieldingRepo_UpsertFieldingAggregates_Call{Call: _e.mock.On("UpsertFieldingAggregates", ctx, rows)}
}

func (_c *MockFieldingRepo_UpsertFieldingAggregates_Call) Run(run func(ctx context.Context, rows []db.FieldingAggregateRow)) *MockFieldingRepo_UpsertFieldingAggregates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []db.FieldingAggregateRow
		if args[1] != nil {
			arg1 = args[1].([]db.FieldingAggregateRow)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFieldingRepo_UpsertFieldingAggregates_Call) Return(err error) *MockFieldingRepo_UpsertFieldingAggregates_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFieldingRepo_UpsertFieldingAggregates_Call) RunAndReturn(run func(ctx context.Context, rows []db.FieldingAggregateRow) error) *MockFieldingRepo_UpsertFieldingAggregates_Call {
	_c.Call.Return(run)
	return _c
}
