// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/umayangag/cric-info-scrapers/go-app/internal/models"
)

// NewMockMatchRepo creates a new instance of MockMatchRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMatchRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMatchRepo {
	mock := &MockMatchRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMatchRepo is an autogenerated mock type for the MatchRepo type
type MockMatchRepo struct {
	mock.Mock
}

type MockMatchRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMatchRepo) EXPECT() *MockMatchRepo_Expecter {
	return &MockMatchRepo_Expecter{mock: &_m.Mock}
}

// UpsertMatches provides a mock function for the type MockMatchRepo
func (_mock *MockMatchRepo) UpsertMatches(ctx context.Context, ms []models.Match) error {
	ret := _mock.Called(ctx, ms)

	if len(ret) == 0 {
		panic("no return value specified for UpsertMatches")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []models.Match) error); ok {
		r0 = returnFunc(ctx, ms)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMatchRepo_UpsertMatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertMatches'
type MockMatchRepo_UpsertMatches_Call struct {
	*mock.Call
}

// UpsertMatches is a helper method to define mock.On call
//   - ctx context.Context
//   - ms []models.Match
func (_e *MockMatchRepo_Expecter) UpsertMatches(ctx interface{}, ms interface{}) *MockMatchRepo_UpsertMatches_Call {
	return &MockMatchRepo_UpsertMatches_Call{Call: _e.mock.On("UpsertMatches", ctx, ms)}
}

func (_c *MockMatchRepo_UpsertMatches_Call) Run(run func(ctx context.Context, ms []models.Match)) *MockMatchRepo_UpsertMatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []models.Match
		if args[1] != nil {
			arg1 = args[1].([]models.Match)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMatchRepo_UpsertMatches_Call) Return(err error) *MockMatchRepo_UpsertMatches_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMatchRepo_UpsertMatches_Call) RunAndReturn(run func(ctx context.Context, ms []models.Match) error) *MockMatchRepo_UpsertMatches_Call {
	_c.Call.Return(run)
	return _c
}
