// Code generated by mockery (manually added). DO NOT EDIT.
package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"
)

// Connector is a testify/mock implementation of db.Connector.
type Connector struct{ mock.Mock }

func (m *Connector) Connect(ctx context.Context) error {
	args := m.Called(ctx)
	return args.Error(0)
}
