// Code generated by mockery-style pattern (handwritten for now). DO NOT EDIT.
package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"
	"github.com/umayangag/cric-info-scrapers/go-app/internal/db"
)

// DBMock implements db.DB using testify/mock.
type DBMock struct{ mock.Mock }

func (m *DBMock) Exec(ctx context.Context, sql string, args ...any) error {
	callArgs := []any{ctx, sql}
	callArgs = append(callArgs, args...)
	ret := m.Called(callArgs...)
	return ret.Error(0)
}

func (m *DBMock) Query(ctx context.Context, sql string, args ...any) (db.Rows, error) {
	callArgs := []any{ctx, sql}
	callArgs = append(callArgs, args...)
	ret := m.Called(callArgs...)
	r0, _ := ret.Get(0).(db.Rows)
	return r0, ret.Error(1)
}

func (m *DBMock) QueryRow(ctx context.Context, sql string, args ...any) db.Row {
	callArgs := []any{ctx, sql}
	callArgs = append(callArgs, args...)
	ret := m.Called(callArgs...)
	r0, _ := ret.Get(0).(db.Row)
	return r0
}

func (m *DBMock) Begin(ctx context.Context) (db.Tx, error) {
	ret := m.Called(ctx)
	r0, _ := ret.Get(0).(db.Tx)
	return r0, ret.Error(1)
}

// RowsMock implements db.Rows with an internal slice.
type RowsMock struct {
	mock.Mock
	vals []string
	idx  int
}

func NewRowsMock(vals []string) *RowsMock { return &RowsMock{vals: vals} }

func (r *RowsMock) Next() bool {
	if r.idx < len(r.vals) {
		r.idx++
		return true
	}
	return false
}

func (r *RowsMock) Scan(dest ...any) error {
	ret := r.Called(dest...) // allow hooks if needed
	if r.idx == 0 || r.idx > len(r.vals) {
		return ret.Error(0)
	}
	if len(dest) == 0 {
		return ret.Error(0)
	}
	if p, ok := dest[0].(*string); ok {
		*p = r.vals[r.idx-1]
		return nil
	}
	return ret.Error(0)
}

func (r *RowsMock) Close() { r.Called() }

func (r *RowsMock) Err() error { return nil }

// RowMock implements db.Row (unused in these tests).
type RowMock struct{ mock.Mock }

func (r *RowMock) Scan(dest ...any) error { return r.Called(dest...).Error(0) }

// TxMock implements db.Tx (unused in these tests).
type TxMock struct{ mock.Mock }

func (t *TxMock) Exec(ctx context.Context, sql string, args ...any) error {
	callArgs := []any{ctx, sql}
	callArgs = append(callArgs, args...)
	return t.Called(callArgs...).Error(0)
}
func (t *TxMock) Query(ctx context.Context, sql string, args ...any) (db.Rows, error) {
	callArgs := []any{ctx, sql}
	callArgs = append(callArgs, args...)
	ret := t.Called(callArgs...)
	r0, _ := ret.Get(0).(db.Rows)
	return r0, ret.Error(1)
}
func (t *TxMock) QueryRow(ctx context.Context, sql string, args ...any) db.Row {
	callArgs := []any{ctx, sql}
	callArgs = append(callArgs, args...)
	ret := t.Called(callArgs...)
	r0, _ := ret.Get(0).(db.Row)
	return r0
}
func (t *TxMock) Commit(ctx context.Context) error   { return t.Called(ctx).Error(0) }
func (t *TxMock) Rollback(ctx context.Context) error { return t.Called(ctx).Error(0) }
